### ISSUE TITLE
eula.txt文件换行编码不正确

### ISSUE THREAD

**Issue by paopaofeng** [DigitalPlatform/dp2#1]
dp2Circulation和dp2Catalog两个工程下的eula.txt换行编码有问题，二进制查看文件的换行编码为 0A，在Windows操作系统自带的记事本中打开分行就乱了。

**Comment by DigitalPlatform** [comment]
已经修改了读取 eula.txt 文件的模块，读入每行结尾为 LF 的文件也能正确显示了。
