### ISSUE TITLE
dp2OPAC 报表下载异常

### ISSUE THREAD

**Issue by paopaofeng** [DigitalPlatform/dp2#103]
在 dp2opac 统计信息报表栏目中下载 Excel 文件格式报表出现异常：

>未能加载文件或程序集“DocumentFormat.OpenXml, Version=2.8.1.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)

**Comment by DigitalPlatform** [comment]
是 DocumentFormat.OpenXml.dll 的 Nuget 包版本不一致引起的。已经解决。
