### ISSUE TITLE
SQLite.Interop.dll 无法拷贝的错误

### ISSUE THREAD

**Issue by ladliulivecn** [DigitalPlatform/dp2#1121]
编译时候提示错误：
![image](https://user-images.githubusercontent.com/76149915/167788088-4711b559-5866-4d75-a07b-c3cb21f19229.png)
本机在项目中搜索当前的文件有：
![image](https://user-images.githubusercontent.com/76149915/167788172-f74f796e-202d-4eae-8ff0-82e36b29ca82.png)
@DigitalPlatform 不知道这个问题如何解决？

**Comment by DigitalPlatform** [comment]
已改进 .gitignore 文件，添加了 
```
!dp2Circulation/x86/SQLite.Interop.dll
!dp2Circulation/x64/SQLite.Interop.dll

!dp2Inventory/x86/SQLite.Interop.dll
!dp2Inventory/x64/SQLite.Interop.dll
```
把两个 .dll 文件包含在 Project 内

您再 pull 一下最新代码试试看
