### ISSUE TITLE
编译打包时错误

### ISSUE THREAD

**Issue by ladliulivecn** [DigitalPlatform/dp2#1122]
错误信息如下：
![image](https://user-images.githubusercontent.com/76149915/167825917-1c2619f7-9658-4355-aff0-c51f4cdec131.png)
![image](https://user-images.githubusercontent.com/76149915/167825991-4b32bcd7-cc82-455f-85c8-b83f0d1178c7.png)
![image](https://user-images.githubusercontent.com/76149915/167826042-4afe3bae-9faa-470a-bedc-335d2bd06ed8.png)
不知道是否是项目文件缺失？还是哪里编译有问题？
copypalm.bat，copygate.bat 这两个文件，不存在，不知道是否正常？

**Comment by DigitalPlatform** [comment]
这是因为 palmcenter 和 dp2gate 这两个 Project 还没有开源，相关目录和文件缺失的缘故。
我改进了一下 dp2installer 的生成事件：
```
echo "准备安装包 .zip 文件 ..."
CD /D $(ProjectDir)
CALL copykernel.bat
CALL copylibrary.bat
CALL copyopac.bat
CALL copyzserver.bat

if exist "..\palmcenter\program.cs" (
CALL copypalm.bat
) else (
echo "palmcenter not found"
)

if exist "..\dp2gate\program.cs" (
CALL copygate.bat
) else (
echo "dp2gate not found"
)
```

这样当 palmcenter 和 dp2gate 两个 project 不存在的时候能跳过两个 .bat 命令。

您再 pull 一下最新代码看看问题是否解决。

**Comment by DigitalPlatform** [comment]
DOS 批处理文件中的 if exist 命令用法可参考：
https://blog.csdn.net/clever101/article/details/102488225

**Comment by ladliulivecn** [comment]
@DigitalPlatform 谢谢，这两个项目是什么目的呢？支持网络使用，目前开源的只能是单机使用？

**Comment by ladliulivecn** [comment]
![image](https://user-images.githubusercontent.com/76149915/167982034-a792d87a-9a93-4949-8303-11af14639f31.png)
可是这个zip不存在，编译da'b打包会失败，如何处理呢？

**Comment by DigitalPlatform** [comment]
> 可是这个zip不存在，编译打包会失败，如何处理呢？如果这两个项目没有打包，那么运行时，有什么影响呢？

哦，忘了 palm_app.zip 还是 dp2installer Project 里面的文件(构建阶段要自动复制到 debug 子目录)。

我从 dp2installer Project 包含的文件中去掉了 palm_app.zip，改为用 copypalm.bat 拷贝到 bin 子目录：
https://github.com/DigitalPlatform/dp2/commit/0e5963a33f1df731f2d34f908c43aebc47035a73

您再 pull 一下最新代码，编译构建一下 dp2installer project 看看是否还有报错

**Comment by DigitalPlatform** [comment]
> 这两个项目是什么目的呢？支持网络使用，目前开源的只能是单机使用？

palmcenter 是“掌纹中心”，相当于一个设备驱动层，提供对掌纹仪的支持。有了它内务等前端里面就可以实现读者用登记的掌纹借书了。

dp2gate 是“RFID 门禁模块”，允许门禁和 dp2library 相连，根据册记录状态来决定图书 RFID 标签经过门禁时候是否要报警。

这两个模块无论是标准版还是单机版都可以搭配它们使用。只是暂时没有开源而已。(标准版和单机版都是同一套源代码，要开源两者一般是同时开源的)

**Comment by ladliulivecn** [comment]
> > 可是这个zip不存在，编译打包会失败，如何处理呢？如果这两个项目没有打包，那么运行时，有什么影响呢？
> 
> 哦，忘了 palm_app.zip 还是 dp2installer Project 里面的文件(构建阶段要自动复制到 debug 子目录)。
> 
> 我从 dp2installer Project 包含的文件中去掉了 palm_app.zip，改为用 copypalm.bat 拷贝到 bin 子目录： [0e5963a](https://github.com/DigitalPlatform/dp2/commit/0e5963a33f1df731f2d34f908c43aebc47035a73)
> 
> 您再 pull 一下最新代码，编译构建一下 dp2installer project 看看是否还有报错

重新拉取了，但是错误提示：
![image](https://user-images.githubusercontent.com/76149915/168013047-e8fe5b55-5fb7-426c-9e4b-27cd66912671.png)
从你提交的修改看，还是没有这个zip，所以这个项目还是没法打包成功吧？是我哪里编译的有问题吗？

**Comment by ladliulivecn** [comment]
![image](https://user-images.githubusercontent.com/76149915/168021197-240fa5e0-e552-4b73-9653-99bd49205b8d.png)
从这里看，项目确实排除了palm_app.zip的打包
![image](https://user-images.githubusercontent.com/76149915/168021091-3f03c64e-fe0c-4d73-b711-51db77405892.png)
但是编译打包的结果还是这个报错呢？是我哪里设置不对吗？
@DigitalPlatform

**Comment by DigitalPlatform** [comment]
> 重新拉取了，但是错误提示：
> ![image](https://user-images.githubusercontent.com/76149915/168013047-e8fe5b55-5fb7-426c-9e4b-27cd66912671.png)
> 从你提交的修改看，还是没有这个zip，所以这个项目还是没法打包成功吧？是我哪里编译的有问题吗？

最新的 dp2installer Project 里面确实没有包含这个 palm_app.zip 了。所以编译和构建的时候理应是不应该去复制这个文件的。您截图中的“复制”动作非常奇怪，看起来好像旧的代码的构建行为。

除了 pull最新代码，是不是 VS 需要重启一次试试？

**Comment by DigitalPlatform** [comment]
![image](https://user-images.githubusercontent.com/10781446/168025871-1f955e53-ef27-4fdf-bd15-6dbffb1ee3c1.png)

您看，最新的状态，应用程序文件里面已经没有这个 palm_app.zip 了。从您的截图来看，应该还是旧的 project 效果

**Comment by ladliulivecn** [comment]
确实是我的本地代码的问题，重新生成就可以了，谢谢。
