### ISSUE TITLE
（已迁移至131 ）Mysql8.0版后dp2kernel安装时出现的问题测试

### ISSUE THREAD

**Issue by zhulinjianke** [DigitalPlatform/dp2#113]
系统安装了MySQL8.0(安装时勾选TCP/IP)，MySQL8.0的安装方法可参考
“MySQL8.0的安装步骤及测试 #114”
[https://github.com/DigitalPlatform/dp2/issues/114](url)

升级到最新版本的dp2Installer。
1、进入到dp2Installer，点击“dp2kernel”--“安装dp2kernel”命令，进入到安装“实例设置”页面。
2、在“实例设置”页面，点击“新增”按钮，进入到“创建一个新实例”窗口。实例名为“test”，数据目录为“c:\kernel_data”，SQL服务器名为“MySQL Server”，然后点击“...”命令，设置服务器名。
3、进入到“MYSQL Server相关参数设置”页面，SQL服务器名为“127.0.0.1”，MySQL用户名为“root”，密码为“12345678”，再次输入密码为“12345678”，内核实例名为“dp2kernel_test”，点击确定按钮后，则会出连接SQL数据库出错：Authentication method 'caching_sha2_password' not supported by any of the available plugings

安装了最新MySQL8.0版后，再安装dp2kernel时会出现报错，这是一个bug。

**Comment by DigitalPlatform** [comment]
这个 issue 为什么要和另外一个 issue 分开写？建议合并到一起

**Comment by DigitalPlatform** [comment]
出现这个报错，是因为 MySQL 8.0 安装过程中关键的一步：

![image](https://user-images.githubusercontent.com/10781446/41808575-331f90b8-7712-11e8-909e-c31c98516fc8.png)
