### ISSUE TITLE
MySQL8.0的安装步骤及测试

### ISSUE THREAD

**Issue by zhulinjianke** [DigitalPlatform/dp2#114]
1、从网页上下载[https://dev.mysql.com/downloads/](url)下载MySQL8.0版。
2、下载完成后，点击安装文件，进入到如下
![default](https://user-images.githubusercontent.com/40415270/41705965-2763775e-756d-11e8-9b5c-d99054c31fd9.png)
3、点击下一步，进入到“Choosing a Setup Type”阶段安装，选择“Custom”项后，点击“Next”按钮。
4、进入到“Select Products and Features”,选中双击“MySQL Servers”下的“MySQL 8.0-X64”装入到右边框内，点击“Next”。
5、进入到“Installation”安装阶段，点击“Excute”进行安装。
6、分别点击“Next”,进入到“Type and networking”阶段，进行安装配置。勾选TCP/IP和Name Pipe项，点击“Next”，经测试如果这阶段设置里面不勾选TCP/IP，则安装starting server阶段会出现错误。
7、进入到“Accounts and Roles”页面，设置密码为“huoliwei”,不要配置其它用户，点击“Next”。
8、其它安装页面分别为默认设置，点击“Next”，进入“Apply Server Configuration”后，进行安装，安装成功。
9、进入到mysql的my.ini文件，在里加入bind-address=127.0.0.1
备注：出于安全性考虑，在mysql的my.ini文件里加bind-address=127.0.0.1，限制只能本机访问。注意不能使用localhost，localhost会引起了速度慢的问题。

**Comment by DigitalPlatform** [comment]
@zhulinjianke 

> 经测试如果这阶段设置里面不勾选TCP/IP，则安装starting server阶段会出现错误

会出现什么错误呢？希望能详细描述一下。这里正好是关键信息，省略不得。
