### ISSUE TITLE
dp2Library 定期升级提醒功能

### ISSUE THREAD

**Issue by paopaofeng** [DigitalPlatform/dp2#122]
目前 dp2Library 中设置了定期强制升级，但缺少提前提醒机制，有用户单位提出（服务器）“系统维护或升级，能不能提前有个通知。这样我们也能提前安排好工作。”

**Comment by DigitalPlatform** [comment]
最新版 dp2library 和 dp2libraryxe 为 GetSystemParamter() API 增加了 system/expire 获取 dp2library 失效期的功能。从最新版内务前端的“关于”对话框中能看到。这些模块的更新发布要等几天，和其他功能一起发布。
