### ISSUE TITLE
测试计划：为读者配置书评管理权限

### ISSUE THREAD

**Issue by renyh** [DigitalPlatform/dp2#139]
### 测试目的

*已知工作人员如果配置了managecomment 权限，则可以对所有书评进行管理，包括编辑、修改状态、删除。尚不清楚读者帐号如果配了书评管理权限，是否也可以管理书评。*

测试读者帐号如果配了 managecomment 权限，是否可以管理书评。

### 测试步骤
1）在给读者配书评管理权前，先在OPAC上，用指定读者帐户登录，在书评界面，看到对于他人的书评只能查看，不能修改。对于自己的书评可以编辑或删除。

2）打开dp2内务，在 读者查询窗 查到该读者记录，双击加载到读者窗。
   
3）在读者窗，在权限字段中输入managecomment，保存记录。

4）到OPAC界面，退出登录，重新用读者帐号登录。在书评界面，发现针对他人的书评下面出现了管理用的按钮（ 编辑、状态、删除）。
<img src='https://user-images.githubusercontent.com/13568719/44112057-aa770248-a036-11e8-91c3-074041d503a8.png' width='360px'>

5）针对一条他人书评，点 状态 按钮，然后将状态设为审查， 提交评注，提示 "读者身份的用户不能修改由其他用户创建的评注记录"。

### 测试结果

20180815-renyh：看来读者帐户即使配了书评管理的权限，实际也不能修改其它用户创建的评注记录。既然这样，那第4）步骤就不要出现管理按钮了。还好第5）步真正保存时卡住了。

**Comment by DigitalPlatform** [comment]
> 看来读者帐户即使配了书评管理的权限，实际也不能修改其它用户创建的评注记录。既然这样，那第4）步骤就不要出现管理按钮了。还好第5）步真正保存时卡住了

**Comment by renyh** [comment]
## 测试用例 TC-RYH-20180815-02

### 测试目的
根据开发设计，读者如果配置了managecomment 权限的话，可以使用全部书评管理功能，即可以对全部用户创建的书评都可以编辑、修改状态、和删除。
同时支持批量操作。

### 准备工作
1）dp2libraryxe升级到3.4版本。
2）挑一条用于测试权限的特定读者记录A，没有管理权限。

### 测试步骤
1）先用其它帐户，1工作人员1读者，分别创建2条书评记录，共4条。
2）先不给读者A配置书评管理权限。在OPAC，读者A登录，在书评页面，对于其它人创建的书评只能查看，没有管理按钮。
3）在内务的读者窗，为读者A的权限字段中输入managecomment，保存记录。
4）到OPAC界面，退出登录，重新用读者A登录。在书评界面，因为有了权限，应对其它人的书评可以管理，即应出现了管理用的按钮（ 编辑、状态、删除）。
5）针对一条他人书评，点 编辑 按钮，修改内容， 提交评注，应该保存成功。
6）针对一条他人书评，点 状态 按钮，设状态为审查， 提交评注，应该保存成功。
7）针对一条他人书评，点 删除 按钮，应该删除成功。
8）批量选2条，点最下方的 修改状态 按钮，增加/减少 屏蔽 ，修改状态应该成功。
9）批量选2条，点最下方的 删除 按钮，应批量删除成功。

### 测试结果
20180815-renyh：**第7）与 第9）的删除，未成功，提示“读者身份的用户不能删除由其他用户创建的评注记录”。**

**Comment by DigitalPlatform** [comment]
@renyh 

读者具有 managecomment 权限不能删除别人创建的评注记录的问题已经修复，dp2installer 和 dp2library 均已更新，请重新测试一下

**Comment by renyh** [comment]
已在wiki里做了关联目录，特关闭该issue。
