### ISSUE TITLE
读者薄的证卡格式，单独实例时没有输出学校名称

### ISSUE THREAD

**Issue by renyh1013** [DigitalPlatform/dp2#18]

**Comment by DigitalPlatform** [comment]
原先是对于分馆的读者，可以打印出分馆名。而总馆(不属于某个分馆)的读者则没打印出图书馆名。

最新版已经做了改进，总馆读者也可以打印出总馆名了。总馆名是在 dp2library 数据目录下的 library.xml 中 libraryInfo/libraryName 元素中配置的名字：
    <libraryInfo>
        <libraryName>本地图书馆</libraryName>
    </libraryInfo>
通常在安装 dp2library 的时候设置。
