### ISSUE TITLE
使用分列功能在EXCEL中实现按中图法分类号或者种次号排序。

### ISSUE THREAD

**Issue by jay2505** [DigitalPlatform/dp2#189]
某用户单位需要把实体查询窗检索出的书目信息，导出来做成EXCEL表格，  并按分类号 筛选排序统计。因为dp2内务系统中的分类号和种次号是一个数据，用分割符区分开，所以需要分离这个数据。这种情况下可以使用EXCEL中的分列功能。

1.首先需要把实体查询窗的书目信息导出来。

<img src='https://user-images.githubusercontent.com/42714760/47689742-2c020d00-dc26-11e8-98fa-bbfcf6ae3873.png' width='480px'/>

可以看到索取号和种次号在一个列中用分隔符/隔开，按分类号或者种次号排序无法实现。

2.第二步按照下图，点击 索取号 上方的方格选中整个列，点击上方的分列图标，在弹出的 文本分列导向窗口，选择 分割符号 选项。

<img src='https://user-images.githubusercontent.com/42714760/47689695-e6454480-dc25-11e8-9b89-22e14937aeab.png' width='480px'/>

 3.第三步在 文本分列向导 窗口下，按图所示，选择 分割符号 属性页下，选择其他，填入分割符“/”，最后点击下一步

<img src='https://user-images.githubusercontent.com/42714760/47718552-af058080-dc83-11e8-9dc8-cab1ea8f90e1.png' width='480px'/>

4.第四步，在 本文分列向导 窗口下，按图所示，数据预览 属性页 默认为第一项 文本模 列数据格式 的属性选择 文本 选项，
<img src='https://user-images.githubusercontent.com/42714760/47689271-2d323a80-dc24-11e8-8d31-3e813cd03d0e.png' width='480px'/>

5.用上述第四步骤，点击下方 常规 按钮， 列数据格式属性页 也选择 本文。最后点击完成。

6.如下图所示，已经在EXCEL格式下把索取号按照分割符把分列好了 。可以根据分类号或者种次号排序了。

<img src='https://user-images.githubusercontent.com/42714760/47694575-18ac6d00-dc39-11e8-8ba9-0eb87a1beefc.png' width='480px'/>

**Comment by Hopeshine** [comment]
已纳入“常见问题”文档
