### ISSUE TITLE
用馆员备书软件打印预约凭条，备书的使用步骤。

### ISSUE THREAD

**Issue by jay2505** [DigitalPlatform/dp2#196]
有些图书馆需要使用预约备书打印功能。具体操作如下：

1.首先要有读者在OPAC上预约，读者预约在架书籍需要使用读者账号登录OPAC，搜索出想要的书目，在书目下方有一个预约按钮如下图所示：

<img src='https://user-images.githubusercontent.com/42714760/47836487-711f6e00-dde3-11e8-9843-ae88171241af.png' width='480px'/>

2.如预约成功。则会显示下图所示：

<img src='https://user-images.githubusercontent.com/42714760/47836560-bba0ea80-dde3-11e8-89f4-ccc512d91f85.png' width='480px'/>

3.读者预约成功了之后，就可以使用 备书打印软件来打印预约凭条了。
备书软件下载地址

4.软件打开如下所示，

<img src='https://user-images.githubusercontent.com/42714760/47847361-e9972680-de05-11e8-910b-3e643a4689f7.png' width='480px'/> 

5.服务器地址，是需要填入library服务器的rest通讯协议，具体步骤，需要打开dp2installer。点击菜单下的dp2library，选择实例设置，双击实例名进入到 修改一个实例 的窗口，点击协议绑定的选项，如下图，选择rest那一组地址。

<img src='https://user-images.githubusercontent.com/42714760/47847509-67f3c880-de06-11e8-8dee-ddec3ed51656.png' width='250px'/> 

<img src='https://user-images.githubusercontent.com/42714760/47848097-2ebc5800-de08-11e8-83d3-7380cf3a6a7b.png' width='480px'/> 

<img src='https://user-images.githubusercontent.com/42714760/47847563-9376b300-de06-11e8-8342-ce6df5fa89f3.png' width='480px'/> 

6.在软件中输入上图中的地址，（注意输入上述地址时，要去掉前面的rest.）    ，每个实例的地址不一样，所以需要填入各自图书馆的相应地址。
 
<img src='https://user-images.githubusercontent.com/42714760/47848581-c2425880-de09-11e8-9a94-f3fc5ce10d8a.png' width='430px'/>

<img src='https://user-images.githubusercontent.com/42714760/47848667-0a617b00-de0a-11e8-82a9-ce081ed374d3.png' width='430px'/>

7.在预约到书行，点击右键，选择打印，如下图

<img src='https://user-images.githubusercontent.com/42714760/47848704-2e24c100-de0a-11e8-9433-3a1c35439134.png' width='430px'/>

8.可以选择合适的打印机进行打印。

<img src='https://user-images.githubusercontent.com/42714760/47848735-41379100-de0a-11e8-9322-031d36cdba9e.png' width='430px'/>

9.打印成功后，该预约到书的状态，就会变成已打印状态，也可以再次点击右键重复打印。
<img src='https://user-images.githubusercontent.com/42714760/47848768-514f7080-de0a-11e8-9e0c-b2ad8263bc86.png' width='500px'/>

**Comment by renyh** [comment]
备书模块dp2mini功能已更新，这里的介绍不再适用。
