### ISSUE TITLE
OPAC检索数据库选择“全部”，检索结果中的书目数据库排序是否可以调整？

### ISSUE THREAD

**Issue by renyh** [DigitalPlatform/dp2#274]
OPAC检索结果中书目数据库的排序是依据 系统管理/参与OPAC检索的数据库的顺序来的。如下图：
<img src='https://user-images.githubusercontent.com/13568719/51012618-020b8600-1599-11e9-9592-64aebc330d82.png' width='560'/>

如果要调整检索结果中书目数据库的顺序，可以在上述配置界面，选中数据库，然后点击上移 或下移 命令调整顺序。

**注意调整完之后，要在IIS里回收一下OPAC的应用池，使得OPAC系统重启，这样检索结果就按照新的顺序了。**

<img src='https://user-images.githubusercontent.com/13568719/51012773-da68ed80-1599-11e9-9939-f05cf72f6a45.png' width='560'/>

**Comment by Hopeshine** [comment]
已纳入“OPAC”文档系统
