### ISSUE TITLE
RFID如何绑定1443A（IC）卡

### ISSUE THREAD

**Issue by jackson2293917380** [DigitalPlatform/dp2#302]
1.在菜单栏常用窗口选择“读者查询窗”
![图片](https://user-images.githubusercontent.com/35322799/54406369-d6318b80-4714-11e9-811c-545e140f1c8d.png)
2.检索读者，选择要绑定的，如“宋晓红”，双击进入编辑页，在更多命令选择“绑定卡号”

![图片](https://user-images.githubusercontent.com/35322799/54406561-899a8000-4715-11e9-970c-0116e9d4844a.png)
![图片](https://user-images.githubusercontent.com/35322799/54406609-b64e9780-4715-11e9-97a3-f72c822be39e.png)
3.将IC卡放在rfid读卡区，选择添加“1443A卡”，在选择界面选中IC卡，点击确定，此时绑定卡号界面出现卡号，点击确定。
![图片](https://user-images.githubusercontent.com/35322799/54406698-0594c800-4716-11e9-9df8-65cdde60752a.png)
![图片](https://user-images.githubusercontent.com/35322799/54406778-5e646080-4716-11e9-88bb-adaed0d107ad.png)
![图片](https://user-images.githubusercontent.com/35322799/54406811-848a0080-4716-11e9-97a5-0e5c11ceebe5.png)
4.在读者信息页“证号”一栏出现证号，点击保存，完成绑定。
![图片](https://user-images.githubusercontent.com/35322799/54406899-e5193d80-4716-11e9-985a-305c0c9144af.png)
5.在借书界面，将IC卡放在读卡器读卡区，可以读出“宋晓红”信息。
![图片](https://user-images.githubusercontent.com/35322799/54407007-59ec7780-4717-11e9-84c7-c3fdef1869e4.png)

**Comment by renyh** [comment]
移至RFID使用指南
