### ISSUE TITLE
修改书目查询窗中"检索途径"选项的顺序

### ISSUE THREAD

**Issue by jzhaozhe** [DigitalPlatform/dp2#320]
在书目查询窗中的"检索途径"选项顺序默认是固定的,如果要修改检索途径的排列顺序,请按如下操作:

1.打开dp2内务,依次打开:功能-系统维护-系统管理窗-内核
2.找到"中文图书",找到目录下的"cfgs"-"keys"文件,点击右键选择"下载"用以备份,如果在修改后出现错误,可以使用上传文件,恢复备份,以免出现问题.
![image](https://user-images.githubusercontent.com/47917314/55859317-63e18900-5ba4-11e9-9d0f-d925c41f752f.png)

具体打开的文件位置见下图:

![image](https://user-images.githubusercontent.com/47917314/55855766-fa10b180-5b9a-11e9-82fe-2659294ddc01.png)

3.将要调整到第一行的检索选项,从</keys>以下开始剪切,然后插入到第10行</key>下方,下面以将"主题词"选项排列到"检索途径"第一行为例:
    
----
将此整段剪切

    <table name="Thesaurus" id="4" type="subject">
    <convert>
      <string style="upper,simplify,split" />
    </convert>
    <convertquery>
      <string style="upper,simplify" />
    </convertquery>
    <caption lang="zh-CN">主题词</caption>
    <caption lang="en">Thesaurus</caption>
     </table>

----
将剪切过来的字段粘贴到此代码的下方:

    <?xml version="1.0" encoding="utf-8"?>
    <root>
    <nstable>
       <item prefix="marc" url="http://dp2003.com/UNIMARC" />
      </nstable>
      <key>
        <xpath nstable="">//marc:record/marc:datafield[@tag='010']/marc:subfield[@code='a' or 
     @code='z']</xpath>
       <from>ISBN</from>
        <table ref="ISBN" />
      </key>
          <-----插入此处

修改完成后点击保存,然后退出DP2内务

4.打开服务器远程桌面,打开dp2install管理,点击dp2library-配置实例,找到要修改检索途径的实例,点击右键停止,等待停止之后,再点击启动,完成实例的重启
5.重新打开dp2内务,在书目查询窗的"检索途径"顺序就已经更改了.

注1:要修改"中文图书"目录下的keys文件修改检索途径顺序才会生效,修改其他书目的keys文件无效.

注2:其他的查询窗的"检索途径"排列顺序修改方法相同

**Comment by Hopeshine** [comment]
已纳入文档系统
