### ISSUE TITLE
新系统部署事项清单

### ISSUE THREAD

**Issue by liuzhenliuzhen** [DigitalPlatform/dp2#332]
### 1.1 | 检测Windows更新，安装补丁
文档地址：https://github.com/DigitalPlatform/dp2/wiki/dp2系统服务器环境准备

备注：自己单位自己完成，上门前需要确认完成，拿到用户完成更新的截图，没有更新不上门。

操作是否清楚：清楚（查看Windows版本没有说明路径，已增加路径（Win10路径：【设置】-【系统】））

### 1.2 | 检查防火墙是否打开
文档地址：https://github.com/DigitalPlatform/dp2/wiki/dp2系统服务器环境准备

备注：告之用户，由用户网络中心设置

操作是否清楚：清楚
### 1.3 | 检查ping功能
文档地址：https://github.com/DigitalPlatform/dp2/wiki/dp2系统服务器环境准备

备注：告之用户，由用户网络中心设置

操作是否清楚：清楚
### 1.4  启用IIS组件
文档地址：https://github.com/DigitalPlatform/dp2/wiki/dp2系统服务器环境准备

操作是否清楚：清楚
### 1.5  启用MSMQ组件
文档地址：https://github.com/DigitalPlatform/dp2/wiki/dp2系统服务器环境准备

操作是否清楚：清楚
### 1.6 安装.NET   framework 4.6.2
文档地址：https://github.com/DigitalPlatform/dp2/wiki/dp2系统服务器环境准备

操作是否清楚：清楚
### 1.7  安装数据库（MySQL）
文档地址：https://github.com/DigitalPlatform/dp2/wiki/dp2系统服务器环境准备

操作是否清楚：清楚
### 1.8  安装MongoDB
文档地址：https://github.com/DigitalPlatform/dp2/wiki/MongoDB安装步骤

备注：1.8和1.7安装没有先后顺序

操作是否清楚：清楚

### 2.1 安装dp2Installer（安装实用工具）
文档地址：https://github.com/DigitalPlatform/dp2/issues/194

操作是否清楚：清楚(有疑问：安装好dp2Installer之后，点击菜单“dp2library/工具/安装MongoDB” 来不能配置MongoDb, 提示MongoDB已经安装过了，只能通过配置实例来配置)

### 2.2 安装dp2kernel（数据库内核）
文档地址：https://github.com/DigitalPlatform/dp2/issues/194

操作是否清楚：清楚

### 2.3  安装dp2library（图书馆应用服务器）
文档地址：https://github.com/DigitalPlatform/dp2/issues/194

操作是否清楚：清楚

### 2.4 在实例界面对MySQL、MongoDB进行配置
文档地址：https://github.com/DigitalPlatform/dp2/wiki/dp2标准版服务器安装

操作是否清楚：清楚（安装数据库内核（dp2kernel）里加了若已经安装安装dp2Kernel，点击菜单 dp2Kernel/配置实例）

### 2.5  安装dp2OPAC（公共查询）
文档地址：https://github.com/DigitalPlatform/dp2/wiki/dp2标准版服务器安装

操作是否清楚：清楚

### 2.6  配置计数器
文档地址：https://github.com/DigitalPlatform/dp2/issues/285

操作是否清楚：清楚，添加了回收一次dp2OPAC应用池的说明（点击电脑：开始→设置→控制面板→管理工具→Internet Information Services (IIS)管理器→应用程序池→dp2OPAC）。
### 2.7 显示名称

文档地址：https://github.com/DigitalPlatform/dp2/issues/304
 操作是否清楚：清楚：修改了XML文件，增加了第4 步。
### 2.8  默认网页

文档地址：https://github.com/DigitalPlatform/dp2/issues/334
 操作是否清楚：清楚，添加了打开默认页面的地址：http://localhost/dp2OPAC/searchbiblio.aspx 

### 3.1 通过dp2内务登录新服务器，检查是否连通
在内务登录输入dp2Installer里面dp2Library的实例地址：http://localhost:8001/dp2library/lz_library/：
<img src='https://user-images.githubusercontent.com/49140428/56335542-880a1f00-61cf-11e9-955e-165f043ad293.png' width='450px'/>

 操作是否清楚：清楚

### 3.2  通过浏览器检查dp2OPAC是否正常

浏览器地址：http://localhost/dp2OPAC/searchbiblio.aspx

 操作是否清楚：清楚

### 3.3  检查kernel.library.OPAC日志是否存在异常信息
文档地址：https://github.com/DigitalPlatform/dp2/issues/364
启动dp2Installer V3
第一步点击dp2Library/打开数据文件夹里面的log文件查看是否有异常信息。

第二步点击dp2OPAC/打开数据文件夹里面的log文件查看是否有异常信息。

 操作是否清楚：清楚

**Comment by Hopeshine** [comment]
已纳入文档系统
