### ISSUE TITLE
如何调试dp2kernel?

### ISSUE THREAD

**Issue by distinct2010** [DigitalPlatform/dp2#339]
先将dp2installer设为启动项目，运行后安装dp2kernel和dp2library，安装成功后，将dp2kernel的service注销。然后将dp2kernel设为启动项目，项目属性---调试---启动选项---命令行参数填上console，就可以调试dp2kernel了

**Comment by DigitalPlatform** [comment]
问题已经被移动到 
https://github.com/DigitalPlatform/dp2/issues/348
