### ISSUE TITLE
数据库中records表中的data和newdata什么区别？

### ISSUE THREAD

**Issue by distinct2010** [DigitalPlatform/dp2#340]
data和newdata交替使用，由于修改数据时可能会是一个比较耗时的操作，用range表示前端输出data还是newdata
如果当前range指向data，则修改时将修改后的数据先写入到newdata，然后清空data
具体操作详见DigitalPlatform.rms.db项目中sqlDatabase.cs中的WriteSqlRecord()函数

**Comment by DigitalPlatform** [comment]
问题已经被移动到：
https://github.com/DigitalPlatform/dp2/issues/348
