### ISSUE TITLE
引用项目出现nuget报错该如何解决

### ISSUE THREAD

**Issue by distinct2010** [DigitalPlatform/dp2#361]
新项目中引用了以下项目：AsyncPluggableProtocol，DiffPlex，DigitalPlatform，DigitalPlatform.CommonControl，DigitalPlatform.Core，DigitalPlatform.Drawing，DigitalPlatform.IO，DigitalPlatform.MarcDom，DigitalPlatform.MarcEditor，DigitalPlatform.MarcFixedFieldControl，DigitalPlatform.MarcKernel，DigitalPlatform.MarcQuery，DigitalPlatform.Net，DigitalPlatform.Text，DigitalPlatform.Xml，DigitalPlatform.Z3950
报错提示：这台计算机上缺少此项目引用的NuGet程序包，启用“NuGet程序包还原”可下载这些程序包。有关详细信息，请参阅http://go.microsoft.com/fwlink/?LinkID=322105。缺少的文件是E:\repos\wzy\\.nuget\NuGet.targets
项目DigitalPlatform.Drawing
文件DigitalPlatform.Drawing.csproj
行271
尝试将dp2项目中.nuget文件夹添加到项目中，未解决

**Comment by DigitalPlatform** [comment]
请参阅：
http://go.microsoft.com/fwlink/?LinkID=322105
或者
https://docs.microsoft.com/zh-cn/nuget/Consume-Packages/Package-restore-troubleshooting

**Comment by distinct2010** [comment]
在AsyncPluggableProtocol项目中引用的Microsoft.CSharp等文件全部是黄色三角提示，按照dp2项目中引用路径重新添加引用也不行

**Comment by DigitalPlatform** [comment]
请问最终是怎么处理解决的？

**Comment by distinct2010** [comment]
没解决，无奈后来只能引用DLL文件了,z3950的那个dll是修改什么了吗，原来的代码重新引用了一下DLL现在开始报错了，代码用的是chord里面的z39示例程序里面的------------------ 原始邮件 ------------------
发件人: "谢涛"<notifications@github.com>
发送时间: 2019年4月28日(星期天) 上午10:27
收件人: "DigitalPlatform/dp2"<dp2@noreply.github.com>;
抄送: "distinct2010"<346322583@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [DigitalPlatform/dp2] 引用项目出现nuget报错该如何解决 (#361)



请问最终是怎么处理解决的？
 
&mdash;

**Comment by DigitalPlatform** [comment]
如果你自己用源代码编译这些 DLL，要确保那几个 Project 都是 .NET Framework 是 4.7.2 的。可能是这个原因

**Comment by distinct2010** [comment]
------------------ 原始邮件 ------------------
发件人: "谢涛"<notifications@github.com>;
发送时间: 2019年4月28日(星期天) 中午11:34
收件人: "DigitalPlatform/dp2"<dp2@noreply.github.com>;
抄送: "简单的生活"<346322583@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [DigitalPlatform/dp2] 引用项目出现nuget报错该如何解决 (#361)




如果你自己用源代码编译这些 DLL，要确保那几个 Project 都是 .NET Framework 是 4.7.2 的。可能是这个原因
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

这个我想到了，重新拉取了新代码后我就发现您把所有项目的.net环境改成了4.7.2。我的项目也改成了4.7.2。
