### ISSUE TITLE
（已迁至wiki）实用信息合集

### ISSUE THREAD

**Issue by DigitalPlatform** [DigitalPlatform/dp2#38]
市场推广、服务等所需的常用信息集中放到这里，我定期分类整理到 wiki 中。

**Comment by renyh1013** [comment]
### 云服务器用户单位dp2OPAC公共查询系统网址

[南开大学附属中学](http://123.207.138.139/nkfz/)
[天津中小学联盟](http://123.207.138.139/dpcloud/)
[天津市崇化中学](http://123.207.138.139/chonghua/)
[社科院民族所](http://123.207.138.139/minzusuo/)
[天津图专委](http://123.207.138.139/tjtzw/)

[北京师范大学天津附属中学](http://211.159.153.239/tjbf/)
[天津市南开实验学校](http://211.159.153.239/tj112/)
[天津市河西区教育中心](http://211.159.153.239/tjhxec/)
[广西基督教协会](http://211.159.153.239/cedartrees/)
[江苏省青年管理干部学院](http://211.159.153.239/jsqgy/)

[天津市实验中学](http://211.159.153.239/tjsyzx/)
[中国石油化工股份有限公司北京化工研究院](http://211.159.153.239/bjhgy/)
[天津市瑞景中学](http://211.159.153.239/ruijing/)
[天津市43中学](http://58.87.101.80/tj43zx/)
[津图联盟](http://58.87.101.80/trlib/)

[林科电脑](http://58.87.101.80/linksoft/)
[山东日照党校](http://58.87.101.80/cloud/)
[帮未来图书馆联盟](http://58.87.101.80/zhaohe/)
[广东文理学院](http://58.87.101.80/gdwl/)
[中国纺织研究院](http://58.87.101.80/cta/)

**Comment by renyh1013** [comment]
dp2图书馆集成系统视频地址
一、基础操作系列
1.1基础操作-dp2内务安装](http://dp2003.com/video/1.1基础操作-dp2内务安装.mp4)
