### ISSUE TITLE
如何启用IIS

### ISSUE THREAD

**Issue by renyh** [DigitalPlatform/dp2#393]
启用Windows的IIS服务器，主要是为了部署dp2OPAC系统。

Windows Server 2012 ：服务器管理器-添加角色-Web服务器(IIS),同时在子菜单[应用程序开发]勾选【.NET Extensibility 3.5】、【.NET Extensibility 4.7】、【ASP.NET 3.5】、【ASP.NET 4.7】

<img src='https://user-images.githubusercontent.com/50066879/58240218-2401ea00-7d7d-11e9-9860-80364e81618f.png' width='480px'/>

Win10：【控制面板】-【程序】-【程序与功能】-点击左上方【 启用或关闭windows功能】，勾选IIS，同时勾选【万维网服务】-【应用程序开发】下面的【.NET Extensibility 3.5】、【.NET Extensibility 4.7】、【ASP.NET 3.5】、【ASP.NET 4.7】

**Comment by 792955994** [comment]
![image](https://user-images.githubusercontent.com/57248222/68726468-85a06400-05fc-11ea-8e9c-562a6f310cf2.png)

**Comment by renyh** [comment]
已迁至wiki
