### ISSUE TITLE
保存MARC记录报错的处理

### ISSUE THREAD

**Issue by Hopeshine** [DigitalPlatform/dp2#414]
用户在保存MARC记录时，遇到这样的报错。
![image](https://user-images.githubusercontent.com/33890036/57705462-8af51400-7696-11e9-9cfb-9dcca7efe982.png)

 这是因为启用了 MARC 记录保存时的格式脚本检查功能。如果不希望有这个功能，可以去系统参数对话框关掉就可以了。路径：【帮助】-【参数配置】-【种册窗】，保持“保存书目记录时自动校验数据”为不勾选状态

**Comment by DigitalPlatform** [comment]
内务如何关闭自动校验 MARC 记录功能

**Comment by Hopeshine** [comment]
已纳入“书目”现关文档系统
