### ISSUE TITLE
使用issues时，含有大量的图片会出现消失bug

### ISSUE THREAD

**Issue by wangshunmin** [DigitalPlatform/dp2#422]
今天在编写 SQL SERVER 2017 Develop下载与安装 ，编写有1个小时，在切换txt文件返回，发现编写的文件消失了。
需要每隔一段时间就应该保存。
想办法重现 todo

**Comment by renyh** [comment]
issue里一般不要含大量图片，一是因为github上传图片不方便，二是图片多了导致打开很慢，三是图片太多界面很花，四是图片不是稳定的新版本会变化。正常的步骤都用文字描述，为什么要含大量图片呢？
