### ISSUE TITLE
关于平板模式和桌面模式下界面显示问题

### ISSUE THREAD

**Issue by zhangandding** [DigitalPlatform/dp2#432]
1、在桌面模式下打开dp2SSL，页面显示正常；在平板模式下打开dp2SSL，页面显示不全，如下图
![image](https://user-images.githubusercontent.com/50388563/57997996-08d77600-7b02-11e9-826f-e1ad3e977470.png)
![image](https://user-images.githubusercontent.com/50388563/57998003-1260de00-7b02-11e9-8a03-5ed26c8c389a.png)
![image](https://user-images.githubusercontent.com/50388563/57998008-1bea4600-7b02-11e9-8946-021c6af185c2.png)
2、在平板模式下打开RFID中心以及指纹中心，虽然打开了，也有语音提示，但是软件未打开到桌面，直接就最小化了。谢老师要去查看代码。
3. win10系统一体机在桌面模式下，输入锁屏密码时，键盘显示不出来。需要在开始菜单-设置-轻松使用-键盘  将使用屏幕键盘开关打开。

**Comment by DigitalPlatform** [comment]
问题已解决。用下面一段代码可以同时适应平板模式和普通模式：

```
                window.WindowStyle = WindowStyle.None;
                window.ResizeMode = ResizeMode.CanResize;
                window.WindowState = WindowState.Maximized;

```
