### ISSUE TITLE
校验数据功能移植到新项目

### ISSUE THREAD

**Issue by distinct2010** [DigitalPlatform/dp2#436]
新建了一个项目：对marceditor控件的数据进行校验
private void Button8_Click(object sender, EventArgs e)
        {
            VerifyFilterDocument filter = null;

            VerifyHost host = new VerifyHost();
            host.DetailForm = this;

            using (StreamReader sr = new StreamReader("dp2catalog_marc_verify.fltx"))
            {
                strCode = sr.ReadToEnd();                
            }            

            int nRet = this.PrepareVerifyMarcFilter(
                host,
                strCode,
                out filter,
                out strError);
            if (nRet == -1)
            {
                strError = "编译文件 '" + strCfgFileName + "' 的过程中出错:\r\n" + strError;
                MessageBox.Show(strError);
            }

            try
            {

                nRet = filter.DoRecord(null,
                    this.marcEditor1.Marc,
                    0,
                    out strError);
                if (nRet == -1)
                    MessageBox.Show(strError);

            }
            catch (Exception ex)
            {
                strError = "filter.DoRecord error: " + ExceptionUtil.GetDebugText(ex);
                MessageBox.Show(strError);
            }

        }      
报错信息：Environment.CurrentDirectory + "\\digitalplatform.circulationclient.dll",
                                    Environment.CurrentDirectory + "\\digitalplatform.libraryclient.dll",

                                    Environment.CurrentDirectory + "\\dp2catalog.exe"
将这三句注释后报错:
      编译文件 'dp2catalog_marc_verify.fltx' 的过程中出错:
信息条数:226
(18,7) error CS0246 : 未能找到类型或命名空间名称“dp2Circulation”(是否缺少 using 指令或程序集引用?)
(89,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(79,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(124,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(146,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(114,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(186,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(199,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(212,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(225,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(238,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(251,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(176,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(291,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(304,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(317,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(330,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(343,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(281,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(385,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(375,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(428,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(441,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(454,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(467,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(480,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(493,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(506,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(519,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(418,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(560,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(573,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(595,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(550,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(637,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(627,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(682,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(672,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(724,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(714,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(772,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(792,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(812,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(832,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(852,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(872,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(892,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(912,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(932,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(952,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(972,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(991,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(756,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1049,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1069,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1082,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1095,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1108,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1121,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1039,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1163,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1176,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1196,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1153,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1236,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1249,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1262,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1275,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1288,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1301,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1314,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1327,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1340,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1226,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1382,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1395,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1415,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1436,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1449,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1372,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1489,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1502,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1515,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1528,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1541,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1554,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1567,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1580,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1593,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1479,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1633,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1646,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1623,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1686,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1699,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1712,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1676,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1752,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1765,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1742,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1805,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1818,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1795,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1858,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1848,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1884,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1874,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1910,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1923,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1936,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1949,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1962,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1975,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1988,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2001,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2014,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2027,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2040,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2053,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2066,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2079,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2092,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2105,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2118,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2131,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(1900,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2164,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2177,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2190,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2203,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2216,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2229,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2242,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2255,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2268,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2281,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2294,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2307,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2320,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2333,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2346,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2359,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2372,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2385,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2154,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2418,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2431,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2444,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2457,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2470,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2483,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2496,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2509,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2522,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2535,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2548,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2561,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2574,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2587,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2408,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2620,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2640,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2660,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2610,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2693,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2683,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2726,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2716,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2759,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2749,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2799,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2789,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2832,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2822,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2865,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2855,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2898,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2888,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2931,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2921,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2964,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2954,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3004,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(2994,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3044,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3034,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3077,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3067,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3117,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3107,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3150,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3140,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3190,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3215,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3235,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3180,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3275,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3300,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3320,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3265,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3366,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3386,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3405,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3350,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3464,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3454,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3506,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3496,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3548,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3538,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3592,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3605,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3618,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3640,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3653,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3666,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3582,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3705,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3718,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3731,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3744,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3757,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3770,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(3695,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(60,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)
(22,1) error CS0246 : 未能找到类型或命名空间名称“VerifyHost”(是否缺少 using 指令或程序集引用?)

如果要移植这个校验功能，该如何正确使用

**Comment by DigitalPlatform** [comment]
@distinct2010 

如果是原本给 dp2circulation 或者 dp2catalog 用的 .fltx 脚本，不经过修改是无法用到你的 .exe 程序里面的。你的这个 .exe 程序叫做宿主程序，那么你用的 .fltx 脚本应该是针对你这个宿主来书写的。

例如：
> (18,7) error CS0246 : 未能找到类型或命名空间名称“dp2Circulation”(是否缺少 using 指令或程序集引用?)

编译报错里面说的这个 dp2Circulation 就是 dp2circulation.exe，不是你编写的宿主 .exe。根本对不上。
