### ISSUE TITLE
如何查询读者在借册信息？

### ISSUE THREAD

**Issue by wangshunmin** [DigitalPlatform/dp2#437]
**查询读者在借册信息有三种方法：**

## 一. 实体查询窗查询
启动dp2circulation内务前端，常用窗口-实体查询窗：
检索出需要的册后，向右拖动滚动条，直到看见“借阅者”浏览列，点击借阅者，使借阅者前面的三角指向下方，这个时候有借阅者的册就显示在一起。
<img src='https://user-images.githubusercontent.com/50066879/58402126-2d979480-8092-11e9-92ac-fa60fee018d8.png' width='400px'/>

选择需要导出的册，鼠标右键-导出-到Excel文件，自己定义好文件名，点击保存，此时导出读者在借册信息成功。

如果想查看有在借册的读者信息，可以选中“借阅者”栏有内容的记录后，鼠标右击-选【导出】-【装入读者查询窗，将借者记录】，系统会将对应的读者记录装入一个新开的【读者查询窗】，从而看到当前在借的所有读者信息。

## 二. 读者查询窗查询
启动dp2circulation内务前端，常用窗口-读者查询窗：
检索出需要的读者后，选定要导出的读者记录行。
在浏览列表上，点鼠标右键，导出-“导出读者详情到Excel文件”，此时弹出“导出读者详情”页面
导出读者详情分为三个页面：通用，借阅历史，筛选

在第一个通用页面选中【基本信息】【在借】
以及点击右边按钮【...】用来选择导出文件的路径和文件名
在第三个筛选页面 选中【有在借册】
这个时候返回第一个通用页面，选择右下角的【确定】按钮，此时导出读者在借册信息成功。

如果想更加深入了解导出读者详情功能，可参考
“导出读者详情到 Excel文件新功能说明”
https://github.com/DigitalPlatform/dp2/issues/434

## 三. 读者统计窗查询（通过借阅情况方案，查看读者在借总数）
启动dp2circulation内务前端，常用窗口-读者查询窗：
点击菜单【功能】-【统计窗】-【读者统计窗】

在读者统计窗，使用“借阅统计”，“借阅统计（高级）”，“读者信息打印”、这几个方案都可以查询读者的总的 未还书（册）方案。如果没有这些方案，可以添加方案。
使用“借阅统计（高级）”方案后可以看到：
所有读者的证条码  姓名  未还书，
以及读者的这些合计信息。
具体如何添加使用方案，使用读者统计窗、详情见：
https://github.com/DigitalPlatform/dp2/issues/444

**Comment by renyh** [comment]
已转wiki
