### ISSUE TITLE
如何查询读者借阅历史信息？

### ISSUE THREAD

**Issue by wangshunmin** [DigitalPlatform/dp2#438]
查询读者借阅历史信息有四种方法：

## 一. 读者窗查询（查询单个读者借阅历史信息）
启动dp2circulation内务前端，常用窗口-读者窗
使用扫描枪扫入证条码号（在证条码号边上文本框输入需要查询的证条码号），点击“装载”
查询到该读者信息后，点击读者窗检索工具条下方的“借阅历史”，就能看到该读者的所有借阅历史了。
<img src='https://user-images.githubusercontent.com/50066879/58304531-36386280-7e27-11e9-9575-d20a45ad8438.png' width='300px'/>

注意 在“借阅历史”标签下，有 【首页】【前页】【后页】【末页】【装载全部】这些按钮
有些读者的借阅历史信息很多，首页是不能全部显示的，此时可以通过【前页】、【后页】这些按钮进行翻页。点击【末页】按钮可以直接到最后一页。
点击右下角工具条的【...▼】（更多命令）的按钮，
选择“导出读者信息到Excel文件”，弹出“导出读者详情”页面，**请检查“筛选”页面，“筛选”页面不要选中任何其它选项。在“通用”页面选中“基本信息”，在“借阅历史”页面选中“输出借阅历史”**
点击右侧【...】选择借阅历史日期范围，选择完毕点击【确定】按钮，回到“导出读者详情”页面再次点击【确定】按钮，此时读者借阅历史信息导出成功。

如果想更加深入了解导出读者详情功能，可参考
“导出读者详情到 Excel文件新功能说明”
https://github.com/DigitalPlatform/dp2/issues/434

## 二. 读者查询窗查询（多个读者借阅历史 ）
（此方法能按照读者信息排序，不能按照册信息排序）
启动dp2circulation内务前端，常用窗口-读者查询窗：
检索出多个读者后，选择所有要导出的读者记录行。
在浏览列表上，点鼠标右键，导出-“导出读者详情到Excel文件”，弹出“导出读者详情”页面，**请检查“筛选”页面，“筛选”页面不要选中任何其它选项。在“通用”页面选中“基本信息”，在“借阅历史”页面选中“输出借阅历史”**
点击右侧【...】选择借阅历史日期范围，选择完毕点击【确定】按钮，回到“导出读者详情”页面再次点击【确定】按钮，此时读者借阅历史信息导出成功。

## 三. 读者统计窗查询（通过借阅情况方案，查看读者借阅历史总数）
启动dp2circulation内务前端，常用窗口-读者查询窗：
点击菜单【功能】-【统计窗】-【读者统计窗】

在读者统计窗，使用“借阅统计（高级）”方案。可以查询读者总的历史借阅量，如果没有该方案，可以添加方案。执行完“借阅统计（高级）”方案后，可以看到：
所有读者的证条码  姓名  未还书，历史借阅量以及所有读者加起来的合计信息。

具体如何添加使用方案，使用读者统计窗、详情见：
https://github.com/DigitalPlatform/dp2/issues/444

## 四. OPAC上查询（单个读者借阅历史）
登录OPAC我的图书馆

在浏览器地址栏里面输入服务器对应的OPAC地址。OPAC地址与服务器地址相比，少了中间一段“/dp2library”。
比如，服务器地址为：http://211.159.153.239/dp2library/demo，
 则对应的OPAC地址为http://211.159.153.239/demo。
进入之后，首先会进入检索界面。

### 1.账号登录
单击界面右上角【登录】按钮，进入【登录】对话框。用户先选择登录账户对应的类型，如果要是图书馆工作人员账号登录，需要点击登录对话框右侧向下的小三角，切换到“馆员”类别，然后输入相关的账户名称和密码之后，点击【登录】按钮。
登入后系统自动切换到书目查询窗。

### 2.查询报表
点击 统计信息-报表（登录的账号需要查看报表权限）
点击自定义的年份查看
点击“单个读者的借阅清单”，选择需要查看的某个读者
此时右侧显示
该读者的姓名和证条码号
时间选取范围：
读者借阅历史的信息，包括以下选项：
册条码号 | 摘要 | 借书时间 | 还书时间

如果看不到报表，确认该账号是否有足够的权限查看报表。
以及确认dp2内务系统上是否有将其添加到报表中

### 3.添加“超期读者清单”到报表，并查看
启动dp2circulation内务前端，功能-统计窗-报表窗
在标签“报表配置”选择馆藏地，双击修改。在“报表”标签，选择“超期读者清单”，双击打开，修改创建频率为day,month（可自定义），此时连续点击两次【确定】按钮，增加“超期读者清单”报表成功。此时重新打开OPAC我的图书馆网页，就能查看到该报表了。
如何创建和更新报表详情请看：
https://github.com/DigitalPlatform/dp2/wiki/%E5%A6%82%E4%BD%95%E5%88%9B%E5%BB%BA%E5%92%8C%E6%9B%B4%E6%96%B0%E6%8A%A5%E8%A1%A8

**Comment by renyh** [comment]
已转wiki
