### ISSUE TITLE
恢复数据异常的书目或读者信息

### ISSUE THREAD

**Issue by wangshunmin** [DigitalPlatform/dp2#454]
## 通过日志窗-恢复记录功能恢复数据异常的数据
目前dp2内务支持对书目和读者信息进行恢复处理.

### 1.恢复数据信息
启动dp2circulation内务前端，点击单菜【功能】-【系统维护】-【日志窗】，在 日志窗 页面，点击 ”恢复记录”属性页。

在“恢复记录”页面的第一个浏览列表(序号,记录路径,摘要,操作历史)，鼠标右键选择“装载”，弹出“从日志恢复数据库记录”页面，选择适当的日期范围，例如从书目或者读者进入系统的最早日期到操作当天的日期，如果明确知道是哪一天，也可以选择这一天的日志。在“拟恢复的记录路径（每行一个）” 下方的文本输入框，输入打算恢复的书目的记录路径（如果不知道也可以不输入）。然后点击【确定】按钮。

系统开始查找装载日志信息，等装载完毕，从列表查找异常记录的，点击某个记录路径，在下面方列表可以看到  恢复要使用的日志的文件名,该路径的序号,馆代码,操作类型,操作者。

在需要恢复的某个路径，右键选择“保存回数据库”，恢复这条记录。

### 2.校验信息是否恢复
启动dp2circulation内务前端
【常用窗口】-【xx查询窗】
通过查询该信息的记录路径，校对信息是否正确。

读者记录修复以后，注意执行一下针对这条读者记录检查借阅信息链，如果链条有问题要修复一下。

### 问题一：在日志窗-恢复记录-恢复书目记录时，出现提示“时间戳不匹配”
![image](https://user-images.githubusercontent.com/57248222/69711503-24b87600-113c-11ea-9208-129539026ca2.png)
解决方法：点击“是”即可
备注：此功能可以加一个小框进行勾选“不在弹出”

**Comment by Hopeshine** [comment]
已纳入文档系统
