### ISSUE TITLE
如何删除随系统开机启动的程序？

### ISSUE THREAD

**Issue by wangshunmin** [DigitalPlatform/dp2#455]
实际使用dp2内务程序中，会用到各个模块，有些模块会自启动。
下面以“dp2-指纹中心”、“dp2-RFID中心”这两个程序为例，介绍如何删除自启动程序

### 1.控制面板卸载需要删除的程序
在桌面右键“这台电脑”，选择“属性”。在系统菜单下，选择“控制面板主页”，在“控制面板主页”
选择“卸载程序”，找到“dp2-指纹中心”、“dp2-RFID中心”这两个要删除的程序，选择卸载

### 2.删除开机自启动程序
鼠标移动至系统任务栏，右键选择“任务管理器”。第一次打开任务管理器是简略版的任务管理器，通过任务管理器左下角“详细信息”左边的按钮，调出详情版任务管理器。此时任务管理器左下角变为“简略信息”，再次点击会切换回简略版的任务管理器。
此时点击详情版任务管理器菜单下的“启动”标签，页面切换至“启动”页面。
找到需要删除的自启动程序：“dp2-指纹中心”、“dp2-RFID中心”。鼠标右键，选择“打开文件所在的位置”，在跳出的文件里，分别删除“dp2-指纹中心”、“dp2-RFID中心”。此时重启电脑就不会有这两个程序的提示信息了。

**注意这些操作仅是将程序卸载，在系统启动后不会提醒安装程序。并没有将该程序的配置信息彻底清空。
如要彻底清空需要将该程序的所有安装目录删除干净，这样的操作较为危险，可能会误删除其它系统文件，这里不再做介绍。**

### 1.控制面板卸载需要删除的程序
在桌面右键“计算机”，选择“属性”。在系统菜单下，选择“控制面板主页”，在“控制面板主页”
选择“卸载程序”，找到“dp2-指纹中心”、“dp2-RFID中心”这两个要删除的程序，选择卸载

### 2.删除开机自启动程序
点击win7桌面开始按钮弹出开始菜单
在开始菜单的搜索框内，输入运行搜索运行程序，在开始菜单点击运行图标，启动运行程序。
启动运行程序后，在运行输入MSConfig命令点击回车键。点击回车键后，弹出系统配置对话框。
进入系统配置界面后，选择“启动”标签。在启动页面，查看系统已有的启动项。
找到“dp2-指纹中心”、“dp2-RFID中心”，取消该程序的勾选，点击确定。这时会提醒您需要重启电脑。电脑重启后就生效了。

## 三.使用“dp2-指纹中心”、“dp2-RFID中心”帮助功能删除这两个程序的自启动（特例）

针对“dp2-指纹中心”、“dp2-RFID中心”随系统开机的自启动程序，我们专门开发了功能进行删除开机自启动。
打开“dp2-指纹中心”和“dp2-RFID中心”，选择菜单【帮助】选择“删除开机启动快捷方式”，这样自启动程序就删除了。如果“dp2-指纹中心”、“dp2-RFID中心”这两个程序已经在控制面板删除了，可以通过以下地址重新安装，然后使用帮助功能删除自启动：
https://github.com/DigitalPlatform/dp2/wiki/dp2-系统各模块安装发行包地址

**Comment by renyh** [comment]
文字已迁至wiki，并且在wiki里文字进行了更新，这些的文字无效了。
