### ISSUE TITLE
新的条码校验功能 -- BarcodeValidator

### ISSUE THREAD

**Issue by DigitalPlatform** [DigitalPlatform/dp2#461]
以前 dp2library 服务器校验条码是用的 library.xml 文件中 script 元素内的 VerifyBarcode() 脚本函数。变换册条码是用的 TransformBarcode() 函数。为了提高前端校验条码和变换条码的速度，也可以把这两个函数拷贝创建为 dp2library 数据目录下 cfgs/client 目录下的 client.cs 文件。

但拷贝代码给维护带来不便。维护人员经常会忘记同步修改 client.cs 文件。维护两处代码一致，比较困难。

所以这次新开发了一种 XML 结构的条码校验规则定义方法。在 library.xml 根元素下定义一个 barcodeValidation 元素。

## 样例代码

```
<barcodeValidation>
    <validator location="">
        <patron>
            <CMIS />
            <range value="P0000001-P9999999" transform="result=barcode+'...';message='test';" />
            <range value="R0000001-R9999999" transform="barcode + '---'" />
        </patron>
        <entity>
            <range value="T0000001-T9999999">
            </range>
        </entity>
    </validator>
    <validator location="海淀分馆">
        <patron>
            <CMIS />
            <range value="P000001-P999999" transform="..." />
        </patron>
        <entity>
            <range value="Z00001-Z99999">
            </range>
        </entity>
        <transform>
	result = "K" + barcode
        </transform>
    </validator>
</barcodeValidation>
```

## 结构分析

这一套 XML 结构，既用于定义校验条码号，也用于变换条码号规则。

barcodeValidation 元素下是一个或多个 validator 元素。

每个 validator 元素负责定义一个馆藏地的条码校验规则。location 属性定义了馆藏地名称，一般是一个馆代码或者馆藏地全称。如果馆代码为空字符串，表示这是全局馆藏地。特殊情况下，还可以使用 suppress 属性，用以表明这个馆藏地不打算定义条码校验规则(相当于以前的 C# 条码校验脚本函数返回 -2 的情况)。suppress 属性只要具备，哪怕属性值为空，也是有效的。suppress 的属性值用于定义此种情形下的提示内容，例如“馆藏地 海淀分馆 不打算定义校验规则”。

validator 元素下是 patron 或者 entity 元素。patron 元素负责定义读者证条码号的规则；entity 元素负责定义册条码号的规则。validator 元素下还可以有一个 transform 元素，包含这个分馆的条码变换 javascript 脚本。

patron 或 entity 元素下，可以是两种元素：range CMIS 元素。

range 元素定义了一个或者多个合法号码范围。CMIS 元素表示一个学籍号合法规则。

range 元素可以具备一个 transform 属性，用来定义对应于这个号码范围的特定条码变换 javascript 脚本。

## 条码变换规则脚本

validator/transform 元素内的文本，可以定义特定 validator 元素范畴的条码变换规则 javascript 脚本。

range/@transform 属性值，可以定义特定 range 元素范畴的条码变换规则 javascript 脚本。

当上述两处都定义了脚本的时候，如果条码号匹配上了 range 元素，优先使用 range/@transform 内的脚本，否则使用 validator/transform 内的脚本。

脚本可以是一个表达式。表达式的求值以后的结果字符串，就是变换后的条码号。
脚本中也可以给下列环境变量赋值：

barcode 传入的待变换的条码号字符串
result 返回变换后的条码号
message 返回错误信息。也就是说，如果此变量有值，则表示变换过程出错，变量内容就是错误信息

下面举例说明：

* 变换脚本1
```
result=barcode+'123'
```
利用 result 变量来返回值。算法是在输入的条码号之后附加 '123'

* 变换脚本2
```
barcode + '---'
```
直接用一个表达式返回变换后的字符串。算法是在输入的条码号之后附加 '---'

* 变换脚本3
```
result=barcode+'...';message='test';
```
用到了 result 和 message 两个变量。虽然 message 书写靠后，但不会造成问题。(注意测试验证)
message 变量返回出错信息，即 'test'。

* 变换脚本4
```
if (barcode.length == 5)
	result = "K" + barcode;
else if (barcode.length == 7)
        result = barcode;
else
	message = '待变换的条码号 \''+barcode+'\' 长度不对';
```
脚本代码中可以使用 if 条件分支。

**Comment by DigitalPlatform** [comment]
# 测试要点

* 注意测试原来的 VerifyBarcode() 脚本函数和新的 XML 校验规则之间的关系是否正确。有 XML 校验规则的时候系统会优先使用 XML 校验规则。需要测试验证。

* 在没有配置新的 XML 校验规则的情况下，原来的 VerifyBarcode() 脚本函数功能应该正确。这样可保证新版本服务器对旧配置的用户单位环境的兼容性

* 在没有配置新的 XML 校验规则的情况下，如果原来配置了 client.cs，要测试它的正确性。包括测试条码校验功能，和条码变换功能的正确性。

* 对新的 XML 校验规则，不但要测试校验功能的正确性，也要测试条码变换功能的正确性

* 要用内务的读者查询窗中的批校验读者记录功能进行测试。里面用到了读者证条码号校验的功能

* 要用内务的实体查询窗中的批校验册记录功能进行测试。里面用到了册条码号校验功能

**Comment by renyh** [comment]
如果希望即能支持验证该分馆的读者条码，又能验证该分馆的册条码，设置location时需用枚举法列举值，例如location设为`星洲学校,星洲学校/*`。不能简单的设为”星洲学校*“，这样写有漏洞，比如册记录馆藏地是 "星洲学校1/图书馆"，也匹配上了配置规则里面的 "星洲学校*" 。这显然违背了配置者的原意。

**Comment by Hopeshine** [comment]
以上说的是基本规则，实际上用户的需求有时远比基本规则复杂。

尤其对于总分馆下某分馆的用户，当存在两个以上馆藏地需要转换册条码时，需要谨慎配置。详见文档[](https://github.com/DigitalPlatform/dp2/issues/643)

**Comment by Hopeshine** [comment]
已纳入“校验条码”文档系统
