### ISSUE TITLE
(作废)新的条码校验规则测试

### ISSUE THREAD

**Issue by wangshunmin** [DigitalPlatform/dp2#468]
旧版 dp2library 或 dp2libraryxe 和最新版内务配套测试，内务中系统管理窗的“条码校验”属性页的文本框应该是只读状态(表明 dp2library 或 dp2libraryxe 版本较低，配置条码校验 XML 功能无法使用)。

**Comment by wangshunmin** [comment]
todo

**Comment by wangshunmin** [comment]
todo

**Comment by wangshunmin** [comment]
测试用例1
测试目的：
在没有配置新的 XML 校验规则的情况下，原来的 VerifyBarcode() 脚本函数功能应该正确。这样可保证新版本服务器对旧配置的用户单位环境的兼容性

测试结果;

**Comment by wangshunmin** [comment]
测试用例2
测试预期：
在没有配置新的 XML 校验规则的情况下，原来的 VerifyBarcode() 脚本函数功能应该正确。这样可保证新版本服务器对旧配置的用户单位环境的兼容性

测试结果:
dp2v3+dp2libraryxe 框架版本: 3.1.7099.32910
测试结果与测试预期相同

**Comment by wangshunmin** [comment]
测试用例3
测试预期：
注意测试原来的 VerifyBarcode() 脚本函数和新的 XML 校验规则之间的关系是否正确。有 XML 校验规则的时候系统会优先使用 XML 校验规则。需要测试验证。

测试结果:
dp2v3+dp2libraryxe 框架版本: 3.1.7099.32910
测试结果

**Comment by wangshunmin** [comment]
测试用例4
测试预期：
对新的 XML 校验规则，不但要测试校验功能的正确性，也要测试条码变换功能的正确性
测试结果:
dp2v3+dp2libraryxe 框架版本: 3.1.7099.32910
测试结果

**Comment by wangshunmin** [comment]
测试用例5
测试预期：
要用内务的读者查询窗中的批校验读者记录功能进行测试。里面用到了读者证条码号校验的功能
测试结果:
dp2v3+dp2libraryxe 框架版本: 3.1.7099.32910
测试结果

**Comment by wangshunmin** [comment]
测试用例6
测试预期：
要用内务的实体查询窗中的批校验册记录功能进行测试。里面用到了册条码号校验功能
测试结果:
dp2v3+dp2libraryxe 框架版本: 3.1.7099.32910
测试结果

**Comment by wangshunmin** [comment]
## 测试用例7

快捷出纳窗测试 读者借还操作(规则校验)

内务版本:dp2Circulation 3.4.7103.28333

测试步骤

测试步骤:
启动dp2内务-功能-系统维护-系统管理窗
并选好分馆(第三中学2)
### 1.系统维护窗-条码校验-配置
```
<barcodeValidation>
    <validator location="">
        <patron>
            <CMIS />
            <range value="P0000001-P9999999" transform="result=barcode+'ALL';message='这是全局总管的读者证条码错误提醒信息';" />
            <range value="R0000001-R9999999" transform=" 'R'+ barcode  " />
        </patron>
        <entity>
            <range value="T0000001-T9999999">
            </range>
        </entity>
    </validator>
    <validator location="第三中学2">
        <patron>
            <CMIS />
            <range value="P000001-P999999" transform="P" />
        </patron>
        <entity>
            <range value="Z00001-Z99999" transform="  'Z' + barcode " />
            
        </entity>
        <transform>
	 result = "X" + barcode ;
        </transform>
    </validator>
</barcodeValidation>

```

### 2. 在dp2内务-常用窗口-读者查询窗 使用"批校验读者记录功能"
启动dp2内务,常用窗口-读者查询窗
检索到P000001的读者信息
右键该读者-批处理-快速修改读者记录
在弹出的窗口"快速修改读者记录",新增 字段名"证条码号",字段值"P0000011",
该值是不符合配置的校验规则的.此时点击[确定]按钮,返回窗口"快速修改读者记录",再次点击[确定]按钮
,提示是否要"继续修改",点击[继续修改]按钮.
此时提示修改读者记录1条,需要确认保存.
此时右键该读者 批处理-保存选定的修改
跳出提示:
保存读者记录 第三中学读者2/11 时出错: 条码号 'P0000011' 经验证发现不是一个合法的证条码号(号码 'P0000011' (馆藏地属于 '第三中学2')既不是合法的册条码号，也不是合法的证条码号)。保存操作失败。

请问是否要重试保存此记录? 

![图片](https://user-images.githubusercontent.com/50066879/59411078-0c9ea580-8ded-11e9-8fb7-1f86f9a11caf.png)


此时重新右键该读者-批处理-快速修改读者记录
在弹出的窗口"快速修改读者记录",新增 字段名"证条码号",字段值"P000003",符合配置的校验规则的
此时点击[确定]按钮,返回窗口"快速修改读者记录",再次点击[确定]按钮
此时提示修改读者记录1条,点击[确定]按钮
右键该读者 批处理-保存选定的修改,跳出提示框"处理完成,共保存读者记录1条".

通过符合以及不符合新校验规则 的读者证 
不符合新校验规则 的读者证 保存失败
符合新校验规则 的读者证 保存成功,说明新配置的校验规则 生效了.

**Comment by renyh** [comment]
已将有意义的部分提取，该issue做废。
