### ISSUE TITLE
（作废）新的条码校验功能及配置

### ISSUE THREAD

**Issue by wangshunmin** [DigitalPlatform/dp2#475]
以前 dp2library 服务器校验条码是用的 library.xml 文件中 script 元素内的 VerifyBarcode() 脚本函数。变换册条码是用的 TransformBarcode() 函数。为了提高前端校验条码和变换条码的速度，也可以把这两个函数拷贝创建为 dp2library 数据目录下 cfgs/client 目录下的 client.cs 文件。
之前服务器校验条码维护不便。所以新开发了一种 XML 结构的条码校验规则定义方法。在 library.xml 根元素下定义一个 barcodeValidation 元素。
下面就以一个例子来说明如何配置新的校验规则

### 1.使用"条码校验" 配置校验规则
启动dp2内务-功能-系统维护-系统管理窗选择-条码校验（并选好分馆(第三中学)

复制下列代码:

```
<barcodeValidation>
    <validator location="">
        <patron>
            <CMIS />
            <range value="P0000001-P9999999" transform="result=barcode+'ALL';message='这是全局总馆的读者证条码提醒信息';" />
            <range value="R0000001-R9999999" transform=" 'R'+ barcode  " />
        </patron>
        <entity>
            <range value="T0000001-T9999999">
            </range>
        </entity>
    </validator>
    <validator location="第三中学">
        <patron>
            <CMIS />
            <range value="T000001-T999999" />
            <range value="000001-999999" transform="result='T'+barcode ;" />
        </patron>
        <entity>
            <range value="SZ001-SZ999" />
            <range value="Z001-Z999" transform="result= 'S' + barcode ;" />
        </entity>
        <transform>
	if (barcode.length == 4)
	result = "Z" + barcode;
                 else if (barcode.length == 5)
                  result = barcode;
 else if (barcode.length == 7)
                  result = barcode;
	else
	message = '待变换的输入条码号 \''+barcode+'\' 长度不对';
        </transform>
    </validator>
</barcodeValidation>
```

### 2.XML 结构分析

这一套 XML 结构，既用于定义校验条码号，也用于变换条码号规则。

barcodeValidation 元素下是一个或多个 validator 元素。每个 validator 元素负责定义一个馆藏地的条码校验规则。location 属性定义了馆藏地名称，一般是一个馆代码。如果馆代码为空字符串，表示这是全局馆藏地。从上述代码中可以看出配置了一个全局馆藏地,"第三中学"馆藏地
如果图书馆只有一个总馆,那就可以只配置全局馆藏地`<validator location="">`
如果要设置自己的分馆的规则,可以将`<validator location="第三中学">`改为
`<validator location="自己的分馆馆藏地代码">`

validator 元素下是 patron 或者 entity 元素。validator 元素下还可以有一个 transform 元素，包含这个分馆的条码变换 javascript 脚本。

patron 元素负责定义读者证条码号的规则.
entity 元素负责定义册条码号的规则.
validator 元素下还可以有一个 transform 元素，包含这个分馆的条码变换 javascript 脚本.

range 元素中可以具备一个 transform 属性，用来定义对应于这个号码范围的特定条码变换 javascript 脚本。

### 3.条码变换规则脚本,配置读者证和条码号
以第三中学的脚本为例

```
 <validator location="第三中学">
        <patron>
            <CMIS />
            <range value="T000001-T999999" />
            <range value="000001-999999" transform="result='T'+barcode ;" />
        </patron>
        <entity>
            <range value="SZ001-SZ999" />
            <range value="Z001-Z999" transform="result= 'S' + barcode ;" />
        </entity>
        <transform>
	if (barcode.length == 4)
	result = "S" + barcode;
                 else if (barcode.length == 5)
                  result = barcode;
 else if (barcode.length == 7)
                  result = barcode;
	else
	message = '待变换的输入条码号 \''+barcode+'\' 长度不对';
        </transform>
    </validator>
```

这里读者证条码 `<patron>`下配置了两个range的属性
第一行意思是说,校验规则是学籍号
第二行意思是校验规则为 T000001-T999999, 符合T000001-T999999的读者证号可以保存成功
第三行增加了 transform变换,意思是说,对 000001-999999,符合000001-999999的读者证号进行变换,使其在"快捷出纳窗"借的时候,只要输入000001,变换后就会是T000001

```
 <range value="T000001-T999999" />
 <range value="000001-999999" transform="result='T'+barcode ;" />
```
barcode 传入的待变换的条码号字符串(000001)
result 返回变换后的条码号,这边是'T'+barcode  那么变换后就会是T000001
当然也可以barcode+'GB' 等其它组合的方式,这样变换后就变为了000001GB.
在上述代码,第一行保证了校验规则,第二行实现了变换

册条码校验规则同理

validator 元素下还可以有一个 transform 元素，包含这个分馆的条码变换 javascript 脚本,这个transform 元素是该分馆的全局条码变换,只在读者证条码或者册条码没有配置的时候生效。
该 transform 元素可以使用判断语句.

在第三中学分馆下:保存读者:000111  ,不符合规范,保存T000111,保存成功.

<img src='https://user-images.githubusercontent.com/50066879/59892822-4aaf5100-940d-11e9-8b1e-fbabc44e80fd.png' width='400px'/>

配置变换后效果
借还操作:
<img src='https://user-images.githubusercontent.com/50066879/59892753-fdcb7a80-940c-11e9-991e-0ed6a719e48f.png' width='300px'/>

<img src='https://user-images.githubusercontent.com/50066879/59892781-205d9380-940d-11e9-92de-3ac42af4d95a.png' width='300px'/>

**Comment by renyh** [comment]
意义不大，与#461重复。
