### ISSUE TITLE
如何在内务注册人脸

### ISSUE THREAD

**Issue by zhangandding** [DigitalPlatform/dp2#494]
### 前提准备条件

1. 首先，需要安装dp2内务，下载地址：http://dp2003.com/dp2Circulation/v3/publish.htm

2. 安装dp2-人脸中心，下载地址：https://dp2003.com/facecenter/v1/publish.htm

3. 电脑usb口连接外置的摄像头，如果用户的机器有内置的摄像头，可以直接使用内置的摄像头，不用连接外置的摄像头。用户如果使用多个摄像头，可以在dp2人脸中心中选择任意一个，在下面内容会提到如何选择摄像头。

4. 安装dp2人脸中心过程中，系统会自动下载人脸算法，过程中人脸中心是橙色的。下载完成弹出绿色文字提示“欢迎使用人脸中心，请用书标点此文字继续”，用户书标点击文字，又提示“请配置参数”。

**Comment by zhangandding** [comment]
### dp2-内务设置

**Comment by zhangandding** [comment]
### dp2内务注册人脸

**Comment by zhangandding** [comment]
### dp2内务注册人脸

1. 在dp2内务中点击【常用窗口】-【读者查询窗】，点击放大镜小图标，查询到读者，选择其中一个读者
![image](https://user-images.githubusercontent.com/50388563/60335185-d1e16380-99cf-11e9-994c-583063590fcb.png)

2. 点击小人图标，内务有一个提示“等待登记人脸”
![image](https://user-images.githubusercontent.com/50388563/60335654-073a8100-99d1-11e9-92ff-760a08bb2006.png)

3. 页面切换至dp2-人脸中心，人脸对准摄像头，点击右下角确定按钮
**注：如果注册人脸时周围环境比较昏暗，可以使用一个采光灯，安装使用请参考：https://github.com/DigitalPlatform/dp2/issues/508**
![image](https://user-images.githubusercontent.com/50388563/60793497-669b4c80-a19a-11e9-87e9-93573f4233dc.png)

4. 人脸中心语音提示“获取人脸信息成功”。

5. 页面切换至内务，点击右下角保存按钮。
![image](https://user-images.githubusercontent.com/50388563/60335860-71ebbc80-99d1-11e9-847f-75edef5b1f25.png)

6. 至此，人脸注册成功。

**Comment by renyh** [comment]
已转wiki
