### ISSUE TITLE
在内务使用人脸借书

### ISSUE THREAD

**Issue by zhangandding** [DigitalPlatform/dp2#510]
### 准备工作
1）用人脸作为身份识别，需要先在内务或者dp2ssl中为读者登记好人脸信息。
在内务注册人脸可以参考：https://github.com/DigitalPlatform/dp2/issues/494
在dp2SSL注册人脸可参考：https://github.com/DigitalPlatform/dp2/issues/503

### 借书流程
1. 启动dp2-人脸中心，在左侧配置参数里配置好图书馆服务器地址，用户名以及密码
![image](https://user-images.githubusercontent.com/50388563/60334867-19b3bb00-99cf-11e9-8638-d0d0fdb9253e.png)

2. 点击【文件-启动】，人脸中心语音提示“人脸中心启动成功”。

3. 打开dp2内务，服务器地址应该和上述人脸中心设置的图书馆服务器地址一致。

4. 点击帮助-参数配置，选择指纹和人脸。
![image](https://user-images.githubusercontent.com/50388563/60334493-38658200-99ce-11e9-842d-a96f881848a5.png)

5. 在人脸识别接口，原来输入框内容为空，点击“设为常用值”，输入框被赋上默认值，点击确定
![image](https://user-images.githubusercontent.com/50388563/60334653-97c39200-99ce-11e9-95e0-106451582402.png)

6. 点击常用窗口-快捷出纳窗或者直接点击【借】按钮。

7. 点击下方人脸小图标，系统会调出人脸中心来识别人脸。
<img src='https://user-images.githubusercontent.com/50388563/60867651-f524d200-a25d-11e9-96db-c150b681efe9.png' width='300px'/>

8. 如果识别成功语音提示“很好”，上方出现读者信息；如果识别失败语音提示“无法识别，请调整头部位置”。
<img src='https://user-images.githubusercontent.com/50388563/60867705-138acd80-a25e-11e9-829d-51925a520111.png' width='150px'/>
<img src='https://user-images.githubusercontent.com/50388563/60867767-29988e00-a25e-11e9-81ed-3f76633a1ce6.png' width='150px'/>

9. 识别完读者信息，在下方输入框中输入册条码号或者扫入册条码号，即可完成借书。
<img src='https://user-images.githubusercontent.com/50388563/60868165-0b7f5d80-a25f-11e9-8f1f-079e5625ab89.png' width='300px'/>

**Comment by renyh** [comment]
已迁至wiki 人脸模块相关文档
