### ISSUE TITLE
如何排查图书借还状态与门禁报警不符合

### ISSUE THREAD

**Issue by zhangandding** [DigitalPlatform/dp2#515]
###  在内务中查看图书标志位是否发生改变。
**前提条件：连接RFID-读写器，启动dp2-RFID中心。**

1. 启动dp2内务

2. 点击【功能】-【打开功能窗口】-【RFID工具窗】

3. 将图书放在读写器上，选中该标签。如果图书是被借出了，AFI标志位应该是C2，EAS标志位应该是false。如果AFI标志位不是C2，EAS标志位不是false，则借书时图书标签的标志位修改出现异常。
![image](https://user-images.githubusercontent.com/50388563/61105508-a4ef7f00-a4ac-11e9-8ced-4bbf293c408d.png)
如果图书已经还过了，AFI标志位应该是07，EAS标志位应该是true。如果AFI标志位不是07，EAS标志位不是true，则还书时图书标签的标志位修改出现异常。
![image](https://user-images.githubusercontent.com/50388563/61105404-65289780-a4ac-11e9-9cfd-4a3554b35bda.png)
如果标志位修改出现异常，我们需要去了解用户单位是用的数字平台的内务加工，还是用的其他平台的软件加工。如果是用的数字平台的内务加工出错的，则需要联系数字平台开发人员。

4. 如果图书标签的标志位是正常的，我们需要去排查门禁设置。

**Comment by zhangandding** [comment]
## 在dp2SSL自助借还上还书成功后，正常情况下，带着这本书过门禁，应报警，不能正常通过。如果不报警，则为异常。我们需要排查原因，步骤如下：

###  在内务中查看图书标志位是否发生改变。
**前提条件：连接RFID-读写器，启动dp2-RFID中心。**

1. 启动dp2内务

2. 点击【功能】-【打开功能窗口】-【RFID工具窗】

3. 将图书放在读写器上，选中该标签。如果AFI标志位是07，EAS标志位是true，说明书的状态是借出状态，是正常的。反之，则借书时图书标签的标志位修改出现异常。
![image](https://user-images.githubusercontent.com/50388563/61105404-65289780-a4ac-11e9-9cfd-4a3554b35bda.png)

4. 如果图书标签的标志位是正常的，我们需要去排查门禁设置。

###

**Comment by Hopeshine** [comment]
已纳入文档系统
