### ISSUE TITLE
人脸识别之前需要进行刷新读者库定义的准备工作

### ISSUE THREAD

**Issue by wangshunmin** [DigitalPlatform/dp2#522]
## 为什么要刷新读者库定义

以前的读者库 keys 配置文件中没有“人脸时间戳”这个检索点。需要刷新读者库定义，加上这个检索点，才能正常执行人脸识别功能。

## 如何判断是否需要刷新读者库定义

在内务里面打开一个读者查询窗。

观察检索途径，是否有“人脸时间戳”这个检索途径。如果没有这个检索途径，说明需要刷新读者库定义

## 刷新读者库定义的操作步骤

在内务里面打开系统管理窗。

复选所有读者库。然后用鼠标右键点出上下文菜单，使用“刷新读者库 定义”这个命令。

当跳出提示框"确实要刷新数据库读者的定义"? 选择[是]按钮。

然后会跳出"刷新数据库定义的方式"对话框。选择默认的方式**【结构】**即可**,再勾选中【自动启动重建检索点任务】选项**,点击【确定】按钮，此时会跳出"确认身份"对话框,输入正确的密码后，
跳出对话框
"下列内核数据库的检索点定义已经发生修改,dp2library已经自动启动批处理任务来重建这些数据库的检索点了,请使用批处理任务窗来观察任务的执行情况"

此时选择跳转到dp2内务-【功能】-【系统维护】-【批处理任务窗】
在批处理任务窗,选择任务"重建检索点",用户点击【一直显示进度】按钮,可以实时查看检索进度.处理结束时以看到提示:本轮处理结束。

### 1.dp2内务-常用窗口-读者查询窗
在检索途径右边点击下拉框,【人脸时间戳】如果存在说明刷新读者库成功

### 2.dp2内务-功能-系统维护-系统管理窗
选择【内核】页面
**选择刚才刷新的读者库cfgs配置文件夹
在其中看到"browse_face","browse_facetimestamp"两个文件,说明刷新读者库成功了.**

**Comment by Hopeshine** [comment]
已纳入“人脸”文档系统
