### ISSUE TITLE
(作废)如何使用条码自动转换功能（比如加前缀的情况）

### ISSUE THREAD

**Issue by wangshunmin** [DigitalPlatform/dp2#526]
## 条码转换功能

当用户出现了这样的情况：
册的实体库中登记的册信息是A111111册条码,而书上贴的册条码是111111.扫描枪扫出来的册信息是111111,不能被内务识别。这样的书可能有很多册,需要全部重新贴册条码的.这会产生一大笔费用.为了解决这样的问题，我们数字平台开发出了条码转换功能,该功能可以在借还等操作,通过扫描枪扫描册条码111111,内务自动判断出实际为“A111111”的册信息.

### 1.1 配置左上角【馆藏地】选择
启动dp2内务。在上方任务栏点击【帮助】-【参数配置】，选择【全局】一栏。
在【附加的馆藏地：[每行一个]】下方的输入框输入某馆藏地“星洲学校”。
点击【确定】按钮，【参数配置】页面消失。
选择馆藏地，在框架窗口的左上角，点击【选择分馆[总馆]】下拉列表，选择分馆"星洲学校"。

### 1.2 开启相关校验开关
启动dp2内务。在上方任务栏点击【帮助】-【参数配置】，选择【出纳】一栏。
勾选【校验输入的条码号】

### 1.3 使用"条码校验" 配置校验规则
启动dp2内务。在上方任务栏点击【功能】-【系统维护】-【系统管理窗】，选择【条码校验】一栏。
配置校验规则，示例如下;
```
<barcodeValidation>
    <validator location="星洲*">
        <patron>
            <CMIS />
            <range value="XZP00001-XZP99999" />
        </patron>
         <entity>
            <range value="DPB000001-DPB999999" />
            <range value="000001-999999" transform="result= 'DPB' + barcode ;" />
        </entity>
    </validator>
</barcodeValidation>
```
复制完代码，点击左下角【保存】按钮，关闭dp内务，再次启动dp2内务，条码转换功能就可以使用了。

`<validator location="星洲*">`
location用来设置相关的馆藏地，比如星洲第一学校，星洲第二学校，就可以直接使用"星洲*"
`<range value="DPB000001-DPB999999" />`是普通的校验规则，用来校验册条码格式是否正确

`<range value="000001-999999" transform="result= 'DPB' + barcode ;" />`
是条码转换的规则，上面规则是当扫描枪扫入“000001”的册条码，就会转换为DPB000001的册条码

具体如何配置校验可参考：
https://github.com/DigitalPlatform/dp2/issues/461

## 二.内务dp2使用条码转换
目前条码变换功能支持以下几个模块：
### 1.快捷出纳窗
启动dp2内务，选择快捷出纳窗【借】，识别出读者信息后，扫描枪扫入册的条码信息。
比如 000001，快捷出纳窗 成功识别出 DPB000001的册信息，读者借阅成功。

选择快捷出纳窗【还】，扫描枪扫入册的条码信息“ 000001”，快捷出纳窗 成功识别出 DPB000001的册信息，读者还书成功

### 2.批处理-典藏移交

启动dp2内务，选择批处理-典藏移交
1.点击【从条码号文件】 按钮，装入条码号文件（扫描枪扫出的不带前缀的册条码号），就能自动识别为带有前缀的册条码，并显示在下方的集合内。

2.点击【扫入册条码】按钮，跳出“扫入条码”对话框，使用扫码枪扫描书上的册条码号。在下方的集合内就会识别成带有前缀的册条码。

### 3.批处理-打印财产账

启动dp2内务，选择批处理-打印财产账
在【装载】标签页面，点击【从条码号文件】 按钮，装入条码号文件（扫描枪扫出的不带前缀的册条码号），就能自动识别为带有前缀的册条码。

**Comment by renyh** [comment]
已迁至 https://github.com/DigitalPlatform/dp2/issues/504 下方
