### ISSUE TITLE
用户单位服务器迁移后的公众号配置

### ISSUE THREAD

**Issue by wangshunmin** [DigitalPlatform/dp2#530]
# 概述

用户单位的服务器迁移到数字平台云服务器时，很容易发生忘记禁用用户单位原服务器上 dp2capo 模块的事故。后果是，云服务器上的 dp2capo 模块和用户单位原服务器上的 dp2capo 同时登录访问 dp2mserver，出现报错。

本 issue 描述了合理的迁移操作步骤和方法。

下面是推荐的操作步骤：

## 1) 检查用户单位原服务器，停止各种模块

在Windos服务中，停止各种原有实例的服务.

停止dp2Kernel service，并将启动类型设置为：禁用
停掉dp2Libary service，并将启动类型设置为：禁用
停止dp2capo service，并将启动类型设置为：禁用
打开IIS管理器，在应用程序池，停止dp2OPAC应用池

## 2) 通过 chordInstaller 创建一个dp2capo实例
设置capo代理账户

dpMserver服务器设置:
http://dp2003.com:8083/dp2mserver
检测dpMserver的账号(因为xx之前已经创建过了)
登录dp2内务,通过右侧标签下的[用户管理]查询到xx的mserver账号
并修改密码
点击确定.

## 3) 微信公众号查看图书馆
后台管理
公众号管理-图书馆管理
找到xx的 dp2capo账号名
查看是否正确

## 4) 手机微信上查询xx的书目信息
如果出现 【匹配的通道出现多个】的提示
![图片](https://user-images.githubusercontent.com/50066879/60319158-1953f980-99a8-11e9-88e1-d239daac9b9e.png)

说明有不止一个实例连接了
1.需要在创建新实例前,去将原实例删除或禁用
2.检查(dp2MServer 的) capo_xxx 账号，注意 IP 绑定应该是新的 dp2Capo 模块也就是云服务器所在机器的 IP。_( 操作方法：dp2内务 用户管理-
查看该capo_xx
的账号,发现IP地址还有以前的,删除只保留现在的.发现还是有两个以上实例在访问使用)_

3.修改capo_xx 的密码,确保和以前不一样，也是一种双保险的防范方法
公众号检索书目变正常了

**Comment by Hopeshine** [comment]
已加入文档系统
