### ISSUE TITLE
发现条码校验问题时的排查顺序

### ISSUE THREAD

**Issue by wangshunmin** [DigitalPlatform/dp2#535]
### 当用户在保存册条码出现报错时
比如出现提示：您输入的条码号xxx 格式不正确（馆代码'XX'）无法识别，请重新输入
请注意内务当前图书馆为‘XX’，馆代码选择不当也会造成格式不正确的报错
使用dp2内务 快捷出纳窗（还）操作，可以快速判断该册条码号是否符合校验标准和该册是否已经存在。

可以从以下这几方面考虑

### 1.创建的册条码是否符合.前端校验client.cs
如何判断是否有前端校验client.cs，打开启动dp2内务，功能-系统维护-系统管理窗-内核找到【！】目录下的cfgs\client目录，如果没有client目录或者client目录下面没有client.cs文件，说明没有前端client.cs校验

前端校验client.cs是否与服务器library.xml 的校验是否一致的判断方法：

方法1 直接连接该实例服务器，使用dp2install工具打开该实例的数据文件夹，找到library.xml文件，和在该实例\library_data\cfgs\client目录下的client.cs文件。对比VerifyBarcode函数，创建的册条码是否符合条码校验规则 **（需谨慎操作）**

方法2 启动dp2内务，功能-系统维护-系统管理窗-内核找到【！】目录下的library.xml文件和\cfgs\client目录下的client.cs文件，对比VerifyBarcode函数，创建的册条码是否符合条码校验规则

### 2.如果没有前端校验client.cs ，创建的册条码是否符合服务器校验library.xml 的校验规则

方法1 直接连接该实例服务器，使用dp2install工具打开该实例的数据文件夹，找到library.xml文件对比VerifyBarcode函数，创建的册条码是否符合条码校验规则 **（需谨慎操作）**

方法2 启动dp2内务，功能-系统维护-系统管理窗-内核找到【！】目录下的library.xml文件和\cfgs\client目录下的client.cs文件，对比VerifyBarcode函数，创建的册条码是否符合条码校验规则

### 3.如果使用了新校验规则 ，需要查看创建的册条码是否符合条码校验的规则，条码校验的规则是否与服务器校验library.xml 的校验规则一致
启动dp2内务，功能-系统维护-系统管理窗-条码校验 
对比创建的册条码是否符合条码校验规则

### 4.如何快速检测出是哪里的条码校验出错了？
分别对client.cs，library.xml  设置不同的错误提示。
比如client.c文件中s,在VerifyBarcode函数中增加提示“无法识别client.cs”;
```
strError = "馆代码 '"+strLibraryCodeList+"' 无法识别client.cs";
return 0;
```

比如library.xml文件中,在VerifyBarcode函数中增加提示“服务器第三中学”;
```
strError = strLibraryCodeList + "：既不是服务器第三中学的合法的证条码号，也不是合法的册条码号";
return 0;
```
1.提示了是通过服务端library.xml校验的
2.使用了馆藏地“第三中学”的校验规则

**Comment by renyh** [comment]
已迁至wiki，根据新规则来排错，此issue做废。
