### ISSUE TITLE
如何清除误加的 MSMQ 配置

### ISSUE THREAD

**Issue by wangshunmin** [DigitalPlatform/dp2#542]
## 1.启用MSMQ组件

1.打开 控制面板/程序与功能，点击左上方的 启用或关闭windows功能，找到microsoft Message Queue,勾选MSMQ的服务组件。
2.在dp2installer程序中，点击菜单下的library/工具/启动MSMQ。

如果认证用户单位需要启用MSMQ，由数字平台服务人员启用MSMQ并做好配置工作。
如果是非认证用户，并没有MSMQ需求，自己在【dp2install安装实用工具】中随便点击了【自动配置MSMQ参数】按钮，使得 library.xml 中增加了MSMQ默认参数了， dp2library 初始化 MSMQ 时候就会出错了，提示【此计算机上尚未安装消息队列】等错误

### 实例：
用户在启动dp2内务时候报错：【因系统出于维护状态，MessageQueueCreateFail】
查看用户日志文件，发现dp2library下的日志文件中有出错提醒
【重试探测和尝试创建 MSMQ 队列 '.\private$\dp2library' 失败: System.InvalidOperationException:此计算机上尚未安装消息队列】

![图片](https://user-images.githubusercontent.com/50066879/62913003-ef6e5f00-bdbc-11e9-9947-1a5cd674b6fd.png)

随后了解到，该用户并没有开通过微信公众号，没有相关访问权限。却在dp2install安装实用工具中实例配置界面，点击【自动配置MSMQ参数】按钮，系统自动配置了参数MSMQ，就报了错误。
所以我们需要将【自动配置MSMQ参数】添加的参数进行删除操作。

 **【自动配置MSMQ参数】增加的参数**：
使用dp2install安装实用工具，dp2libary实例安装好之后，进入到实例配置界面，点击“自动配置MSMQ参数“，系统对library.xml自动配置了中如下4个参数：
```
<message dbname="消息" reserveTimeSpan="365day"   defaultQueue=".\private$\dp2library_lib1" />

<arrived dbname="预约到书" reserveTimeSpan="2day" outofReservationThreshold="10" canReserveOnshelf="true"  notifyTypes="dpmail,email,mq"  />

<readersMonitor startTime="23:00"  types="dpmail,email,mq"  />

<circulation patronAdditionalFroms="证号,姓名" verifyBookType="true" verifyReaderType="true"  notifyTypes="mq"  verifyBarcode="true" verifyRegisterNoDup="no" />
```

为了要删除MSMQ配置，需要修改上述4个地方的配置，即删除message节点的defaultQueue属性，删除其它地方的mq。另外，如果在消息队列也要手工删除对应的名称，修改后配置如下：
```
<message dbname="消息" reserveTimeSpan="365day" defaultQueue="" />

 <arrived dbname="预约到书" reserveTimeSpan="2day" outofReservationThreshold="10" canReserveOnshelf="true" notifyTypes="dpmail,email" />

<readersMonitor startTime="23:00" types="dpmail,email" />

<circulation patronAdditionalFroms="证号,姓名" verifyBookType="true" verifyReaderType="true" notifyTypes="" verifyBarcode="true" verifyRegisterNoDup="no" />
```

修改完library.xml以后，重新启动内务，发现可以正常运行了。
需要注意的是：
**arrived 元素里面的notifyTypes属性缺省值是 "dpmail,email"
 circulation 元素里面的 notifyTypes 属性缺省值是空**

**Comment by Hopeshine** [comment]
已纳入文档系统
