### ISSUE TITLE
将dp2Catalog 检索的国图书目记录保存到自己的dp2服务器上 

### ISSUE THREAD

**Issue by wangshunmin** [DigitalPlatform/dp2#545]
## 1.启动 dp2Catalog V3
点击菜单-文件-dp2检索窗-检索出相关书目数据

## 2.单条书目数据保存
双击某条 书目数据，跳出【MARC记录窗】
可以看到在菜单【文件】下方有三个按钮图标，点击第三个图标【另存到（数据库）】，跳出【另存记录】页面，此时可以选择自己的dp2服务器，需要注意搜索的书目的格式，中文图书，英文图书需要区分开。比如搜索出的书目是在中文图书，需要放到自己dp2的中文图书库中，而不是放在西文图书中。
<img src='https://user-images.githubusercontent.com/50066879/63146816-d1a83080-c02e-11e9-8f71-15b5be31ec43.png' width='350px'/>

<img src='https://user-images.githubusercontent.com/50066879/63146874-0a480a00-c02f-11e9-8f98-c82001744e3f.png' width='350px'/>

选择完毕后点击【确定】按钮，保存完毕。

## dp2检索窗数据并选择
在dp2检索窗选中复数的书目记录，鼠标右键-保存选定的5条记录到MARC文件
<img src='https://user-images.githubusercontent.com/50066879/63147197-fea91300-c02f-11e9-95ec-e05dd56d7ff6.png' width='350px'/>

点击确定，书目记录保存为了MARC文件。

### 启动dp2内务
点击菜单【批处理】-从MARC文件中导入
点击右侧【...】按钮，选择刚才在dp2Catalog V3中保存的书目MARC文件，点击【下一步】按钮
，此时在【执行统计】标签页面，可能会有重复的书目记录，如果出现重复的书目记录会跳出提示框【经查重发现书目库中已有N条重复记录(中文图书/1894....)。本次保存操作被拒绝, 是否重试？[重试]重试; [跳过]跳过本条继续后面批处理; [中断]中断批处理】

选择【跳过】按钮跳过重复的记录。此时可以点击【下一步】，点击【打印结果】页面的【打印统计结果】按钮，查看统计结果

如何对重复的数据怎么处理？详情请看：
Z39.50 服务器书目记录替换dp2系统里的简编书目-使用说明
https://github.com/DigitalPlatform/dp2/issues/452

**Comment by Hopeshine** [comment]
已纳入cataloge相关文档系统。
