### ISSUE TITLE
需要的改进环节

### ISSUE THREAD

**Issue by Hopeshine** [DigitalPlatform/dp2#546]
为了方便中小学用户更好地管理书商册登记过程以及读者登记过程，系统需要做如下改进：

1. 保存读者记录前校验读者类别是否与流通权限定义的一致 ，如不一致，提醒用户该读者不能借书。确认后保存

2. 册登记保存记录前校验册类型是否与流通权限定义的一致 ，如不一致，提醒用户该册不能流通。确认后保存

3. 册登记保存记录前校验册价格是否为三个字母加上纯数字形式，如不一致，不能保存并提醒用户修改。

4. 册登记保存记录前校验馆藏地设置是否经过系统定义，如未定义，不能保存并提醒用户修改。

5. 册登记保存记录前根据排架体系校验索取号，如果不符，不能保存并提醒用户修改。

**Comment by DigitalPlatform** [comment]
@Hopeshine 

> 册登记保存记录前校验馆藏地设置是否经过系统定义

这个现在版本就是已经有这个功能的吧

> 册登记保存记录前校验册价格是否为三个字母加上纯数字形式

这个现在版本已经是有的功能

**Comment by DigitalPlatform** [comment]
> 保存读者记录前校验读者类别是否与流通权限定义的一致 ，如不一致，提醒用户该读者不能借书。确认后保存

注意 library.xml 中 circulation 元素的 verifyReaderType 属性值应为 "true"，这个功能才会被启用

> 册登记保存记录前校验册类型是否与流通权限定义的一致 ，如不一致，提醒用户该册不能流通。确认后保存

注意 library.xml 中 circulation 元素的 verifyBookType 属性值应为 "true"，这个功能才会被启用

**Comment by DigitalPlatform** [comment]
留言：

另外，你们测试研讨一下看看。library.xml 中很多和校验有关的参数，因为要兼容以前的默认不校验的效果，所以缺省值都定为不校验。这样的一个缺点就是，希望校验的时候，要去专门配置这些参数。维护者感到麻烦。很多时候忘了去配置，这样数据就放松了限制，等过了几年发现数据中问题很多，再来处理就晚了一点
