### ISSUE TITLE
如何为书目库配置“副标题”检索点

### ISSUE THREAD

**Issue by wangshunmin** [DigitalPlatform/dp2#549]
用户在检索书目信息的时候发现输入副标题信息不能检索出书目记库

## 为书目库配置“副标题”检索点的步骤

需要与用户单位系统管理员沟通，询问之前是否定制过检索点。

如果没有定制过检索点，可通过刷新数据库定义解决问题，因为最新安装包中默认的检索点配置已经包含了副标题这个检索点；如果系统管理员曾经定制过检索点，那就没法简单用刷新数据库定义这个办法，而只能通过直接修改书目库的 keys 配置文件来实现定制检索点了。

### 方法一、如何刷新一个书目库的检索点定义

**注：刷新前需要先将该书目库的 keys 和 browse 配置文件备份下来，以便特殊情况下恢复原来的定义。**

**查看书目库 keys 和 browse 配置文件的方法(菜单)：【功能】-【系统维护】-【系统管理窗】-【内核】-【书目库名称】-【cfgs】-keys 或者【browse】。**

点击【功能】-【系统维护】-【系统管理窗】-【数据库】，找到需要配置标题检索点的书目库，在书目库名称上单击鼠标右键，从右键菜单选择【刷新书目库...的定义】，系统弹出【ManagerForm】提示框，在上面点击【是】按钮，系统弹出【刷新数据库定义的方式】对话框，**注意这里务必选择第一个选项“结构”，不能选错**。这个选项只会刷新书目库的keys配置文件和browse配置文件，然后点击【确定】按钮。

因为刷新数据库是重大操作，系统弹出【确认身份】对话框，要求用户输入当前账号的密码。输入后点击【确定】，相关书目库keys配置文件和browse配置文件被刷新为最新版本。

注：如果当前书目库的browse文件经过了定制，刷新过程修改了，需要回过头来用已备份的文件去将browse恢复。

### 生成检索点

keys文件刷新后，需要重建检索点。

重建检索点步骤：

点击菜单【功能】-【系统维护】-【批处理任务窗】，进入【批处理任务窗】。

在【任务】文本框右侧的下拉列表，选择【重建检索点】，然后点击【开始】按钮，系统弹出【启动重建检索点任务】对话框，从【功能】文本框右侧的下拉列表，选择【重建检索点】，然后在【数据库名】文本框里面输入需要重建检索点的书目库名称（可以输入多个书目库，输入时注意每行只输入一个书目库名称），点击【确定】，系统开始所有设置的库重建检索点。

用户可以点击界面左下角的刷新按钮，让系统显示当前创建进度，然后点击【一直显示进度】，可以从浏览区看到创建进展。如果需要中断操作，可以点击【任务名】文本框右侧的【停止】按钮。

系统处理完毕后提示“任务检索点已成功启动”。

重建检索点完成后，当前库中所有的书目记录增加了 200$b 字段，并且在【书目查询窗】可以选择“标题”为检索途径，实际输入副标题内容，来检索到书目记录。

### 方法二、通过修改相关书目库 keys 配置文件，定制检索点

1.确定要修改的MARC字段

dp2内务-常用窗口-书目查询 选择书目库，查询书目信息，选中某条书目记录并打开。
点击【MARC】按钮，找到【题目说明】，因为这边选择了西文类型图书，查看到【题目说明】是245字段。如果是中文图书就需要在中文图书的书目中查看，一般是200字段。

2.修改 keys 配置文件（为了保证安全，配置前可以先备份 keys 配置文件）
点击【功能】-【系统维护】-【系统管理窗】-【内核】-【书目库名称】-【cfgs】-【keys】
右键 keys ，编辑配置文件。
在内容中适当位置增加：
```
<key>
        <xpath nstable="usmarc">//marc:record/marc:datafield[@tag='245']/marc:subfield[@code='a']    </xpath>
        <from>title</from>
        <table ref="title" />
</key>
```
发现tag='245'，只配置‘a’主标题的检索。
查看书目记录MARC 245字段选项发现'b'是标题其余部分，‘c’是责任者说明。
所以这里为了能通过副标题检索出该书目，只需要添加'b'：标题其余部分。添加后的代码如下：
```
   <key>
        <xpath nstable="usmarc">//marc:record/marc:datafield[@tag='245']/marc:subfield[@code='a'] | //marc:record/marc:datafield[@tag='245']/marc:subfield[@code='b'] </xpath>
        <from>title</from>
        <table ref="title" />
    </key>
```
配置完，保存 keys 配置文件。并执行 **创建检索点** 的步骤就能通过副标题检索出书目了。

**Comment by Hopeshine** [comment]
已纳入"书目"相关文档系统。
