### ISSUE TITLE
RFID中心连接读写器检查清单

### ISSUE THREAD

**Issue by renyh** [DigitalPlatform/dp2#551]
当RFID中心无法识别RFID读写器时，表现为RFID中心是红色背景，界面中间有提示“当前尚未连接读卡器”。遇到这种情况，按下面步骤检查排错，如果哪一步RFID中心正常识别到了读写器，则不用检查后面步骤了。
1. 检查读卡器是否连接了电脑 ，接头是否松动。
读卡器通常通过USB口 或者 COM口 连接电脑， USB口的读写器是直接插电脑，中间不需要转接线。<img width="279" alt="image" src="https://user-images.githubusercontent.com/13568719/63632979-81a31c80-c673-11e9-9132-28fd90edb3e1.png">
对于COM口的读写器，因为目前电脑和笔记本上很少有COM口，所以COM口读写器需要通过USB转接线才能连电脑，如下图。而且需要配置优质的转接线，否则稳定性不太好。（todo 增加连线图）<img width="279" alt="image" src="https://user-images.githubusercontent.com/13568719/63633042-1ad23300-c674-11e9-8a63-8d1746f36ac7.png">

2. 检查读卡器是否有独立电源？微功率的读写器一般是靠USB口供电，没有独立电源；中功率的读写器有独立电源，检查这个独立的电源变换器是否查到了插座上，插座是否打开了开关，确保供电正常。（todo 增加图片）

3. 检查平板RFID读写器是否打开了开关，确保打开了读写器开关。<img width="487" alt="image" src="https://user-images.githubusercontent.com/13568719/63632943-d4300900-c672-11e9-9895-2bee696d66eb.png">

4. 观察读卡器的指示灯(平板型号有)，红灯闪表示读写器仅处于供电状态，不是工作状态，可能是RFID中心没启动，或者未识别到读写器。蓝灯表示读写器处于工作状态，表示RFID中心启动并且识别到了读写器。
![image](https://user-images.githubusercontent.com/13568719/63632531-4b14d400-c66a-11e9-923e-8746db77d561.png)

5. 检查电脑是否打开了其它RFID软件，占用了读写器。如果有启动其它RFID相关软件，退出这些软件，再重启RFID中心，这时再检查RFID中心是否识别到读写器。

6. 如果是USB口读写器，拔掉读写器重新将读写器插上电脑，RFID中心会自动感应到USB口拔插，会自动重新初始化读写器，检查RFID中心是否识别到读写器。

7.  如果是COM口读写器，因为RFID中心对 COM 口读卡器做了优化，需要在 RFID 中心，点击菜单 “帮助/自动探测 COM 口读卡器”，然后看看RFID中心是否识别到读写器。

**Comment by Hopeshine** [comment]
已纳入“RFID功能相关文档”
