### ISSUE TITLE
如何卸载，安装人脸中心？

### ISSUE THREAD

**Issue by wangshunmin** [DigitalPlatform/dp2#552]
## 1.卸载原来的人脸中心
1.控制面板-卸载程序
![图片](https://user-images.githubusercontent.com/50066879/63672435-86eb9d00-c814-11e9-91ba-b39b2b41cc51.png)

2.找到人脸中心
鼠标，右键，卸载
![图片](https://user-images.githubusercontent.com/50066879/63672507-ae426a00-c814-11e9-8bb3-0432ff5e16a7.png)

选择移除人脸中心
![图片](https://user-images.githubusercontent.com/50066879/63672557-c3b79400-c814-11e9-8ea1-fbe0db1900fb.png)

## 2.安装新的人脸中心
下载地址：https://dp2003.com/facecenter/v1/publish.htm
点击【启动】按钮，下载程序，并执行
![图片](https://user-images.githubusercontent.com/50066879/63672611-e21d8f80-c814-11e9-99d3-6abc1a609970.png)

安装：
![图片](https://user-images.githubusercontent.com/50066879/63672650-fbbed700-c814-11e9-8d73-89f53b25202e.png)

下载安装完毕后会提示【】，等待下载算法文件完成

![图片](https://user-images.githubusercontent.com/50066879/63672373-658ab100-c814-11e9-8d98-8d3ef64f6acf.png)

最后点击 人脸中心-文件-重新启动按钮。这样人脸中心就重新安装成功了
![图片](https://user-images.githubusercontent.com/50066879/63672759-417b9f80-c815-11e9-9c4c-d1a2e09b529e.png)

**Comment by renyh** [comment]
已迁至wiki，人脸模块 目录下
