### ISSUE TITLE
如何批清除读者指纹信息

### ISSUE THREAD

**Issue by renyh** [DigitalPlatform/dp2#555]
批清除读者指纹信息步骤：
1. 在内务的读者查询窗，根据班级或者其它条件查出需要清除指纹的读者记录，例如毕业的读者。
2. 在检索结果列表中多选需要清除指纹的读者记录，然后单击右键命令 批处理/快速修改读者记录，在快速修改读者记录窗 新增一项修改动作，字段名选择“指纹”，字段值为空，如下图：
![image](https://user-images.githubusercontent.com/13568719/64083336-1b905680-cd51-11e9-9e5e-bfaba73a349e.png)
然后点击确定。
3. 系统执行预修改，被预修改过的读者记录变成黄色背景，右侧固定面板的属页页显示的指纹字段修改前后变化。
![image](https://user-images.githubusercontent.com/13568719/64083382-cd2f8780-cd51-11e9-9450-74fe6e0b8da2.png)
4. 再在检索结果列表中多选预修改过的行，单击右键命令 批处理/保存选定修改，则正式将修改信息保存到系统里。

**Comment by renyh** [comment]
## 毕业学生为什么要清除指纹信息?

    毕业学生的读者记录不需要删除，状态标记注销即可，以后可以查到该学生在校的借阅记录。只要读者记录在，读者能证明自己的身份，随时可以恢复他的借书能力。

    指纹属敏感信息，应将毕业读者的指纹信息清除掉。指纹信息在读者信息里面不是一个很重要的信息，如果将来需要指纹信息，随时可以重新登记

    另外如果毕业指纹不清除，指纹总数多了，对于指纹 1:N识别增加了难度。因为指纹和人脸识别都不是100%可靠，每种算法当数量增多时误识率也会增大。

**Comment by Hopeshine** [comment]
已纳入“读者管理”文档系统
