### ISSUE TITLE
设置标签打印的格式

### ISSUE THREAD

**Issue by renyh** [DigitalPlatform/dp2#572]
## 页面与标签尺寸和边柜示意图

![image](https://user-images.githubusercontent.com/13568719/65445029-e5338c00-de63-11e9-9fba-813f7ce36b73.png)

**Comment by renyh** [comment]
### 关于两个并排标签的中间缝隙

发现在参数设置里没法设置一行2列标签样式中2个标签中间的缝隙，不过可以转换成标签的内容边柜。
![image](https://user-images.githubusercontent.com/13568719/65445178-35aae980-de64-11e9-9f11-c266bef38664.png)

![image](https://user-images.githubusercontent.com/13568719/65445200-3f345180-de64-11e9-8ae4-c2789e5ee1f8.png)

这样调效果就对了，2个标签中间的缝隙就有了
![image](https://user-images.githubusercontent.com/13568719/65445272-668b1e80-de64-11e9-8ee3-35c67b963628.png)

**Comment by renyh** [comment]
## 文字下调
如果希望文字下调一些，可以设置偏移Y的值 
![image](https://user-images.githubusercontent.com/13568719/65445785-8d962000-de65-11e9-87d1-1584a61b5b09.png)

**Comment by renyh** [comment]
![image](https://user-images.githubusercontent.com/13568719/65446196-6c81ff00-de66-11e9-8193-555f3b234c26.png)

**Comment by renyh** [comment]
### 如何让标签文字不超过标签尺寸范围的

在行设置界面，风格设置为 auto_fit。

现在文字超过尺寸 会后面加...，不论风格是否设了auto_fit，都是一样的效果，记得原来aufo_fix可以把文字缩小。
![image](https://user-images.githubusercontent.com/13568719/65446616-4f016500-de67-11e9-972d-5d93916b2a31.png)
![image](https://user-images.githubusercontent.com/13568719/65446689-77895f00-de67-11e9-8dfe-94e12ca7b8c4.png)

**Comment by DigitalPlatform** [comment]
以前的和标签打印有关的 issue 有两个，可以参考：

https://github.com/DigitalPlatform/dp2/issues/369

https://github.com/DigitalPlatform/dp2/issues/351

注意 line 元素的 style 属性，上述 issue 里面用到了 style="picture"，表示这一行用于定义一张图片。

**Comment by Hopeshine** [comment]
已纳入文档系统
