### ISSUE TITLE
关于实现红泥巴排架的自动化

### ISSUE THREAD

**Issue by Hopeshine** [DigitalPlatform/dp2#587]
### 中图法与红泥巴排架的对应关系

**第一字段：图书分类**

|中图法分类|红泥巴分类|
|-|-|
|A 马、列、毛、邓思想理论|ZZ 马列主义，毛泽东思想，邓小平理论（绿色）|
|B 哲学、宗教	|B 哲学、宗教、心理学（黄色）|
|C 社会科学总论	| C 人文社科（黄色）; CA 社科综合（黄色）|
|D 政治、法律	|CD 政治，法律（黄色）|
|E 军事	|E 军事（黄色）|
|F 经济	|CF 经济（黄色）|
|G 文化、科学、教育、体育|G 文化、教育、体育（黄色）|
|**H 语言、文字**	|H 语言文字（黄色）;N 原版、双语（绿色）|
|**I文学**	|**A 图画书、漫画(红色)**:AA 低幼认知 、AB 纸板书、异型书、玩具书 ，AC 立体书 ，AD 无字书，AE 图画故事书 ，AF 漫画故事书 ，AG 连环画 ;  **I 文学（蓝色)**:IA 诗歌、儿歌、童谣 、 IB 桥梁书 、IC 成长小说；、ID 动物小说 、 IE 侦探故事 、IF 童话、寓言，IH 幻想文学、魔幻小说 ，IK 科幻小说、科普文学 ， IL 历险、探险故事 ，IO 儿童文学选文、作家作品集 ，IG 古典文学 ，IP 传记文学、励志故事 ，IQ 校园文学、青春文学 ，IS 儿童文学散文、随笔，IW 武侠小说 ， IX 戏剧 ，IY 名著改写本、缩写本  ，IZ 儿童文学理论与参考 |
|J 艺术	|J 艺术（绿色）|
|**K历史、地理**	|CZ传记（黄色）;K 历史、地理（绿色）|
|N 自然科学总论	|D 自然百科（黄色）;DA自然百科综合（黄色）;F 科普科技（黄色）;FA科普综合（黄色）|
|O 数理科学和化学|O 数理科学和化学（绿色）|
|Q 生物科学|DD 动物（黄色）;DE 植物（黄色）;FQ 生物科学（黄色）|
|R 医药、卫生|DR人体与健康（黄色）;FR医药、卫生（黄色）|
|S 农业科学|FS 农业科学（黄色）|
|T 工业技术|FT 工业技术（黄色）|
|U 交通运输|FU 交通运输（黄色）|
|V 航空、航天|DP天文学，地球科学（黄色）;	FV航空、航天（黄色）|
|X 环境科学、安全科学|DX环境保护（黄色）|
|Z 综合性图书|Z 综合性图书（绿色）;ZG工具书（绿色）|

### 第二字段：出版社信息。除了红泥巴重点出版社有数字代码，其他的出版社全部用出版社前三个字的首字母。重点出版社编号如下：
|出版社| 编号|
|-|-|
|信谊|001|
|新经典佳心树)|002|
|蒲蒲兰|003|
|启发|004|
|耕林|005|
|海豚传媒|006|
|和英|007|
|蒲公英|008|
|格林文化|009|
|荣信(乐乐趣)| 010|
|麦克米伦|011|
|奇想国|012|
|飓风社|013|
|魔法象|014|
|21世纪|021|
|北京科技|022|
|北京少儿|023|
|春风文艺|024|
|湖北少儿|025|
|湖南少儿|026|
|江苏少儿|027|
|接力出版|028|
|科学普及|029|
|明天出版|030|
|少年儿童|031|
|新疆青少|032|
|新蕾出版|033|
|浙江少儿|034|
|浙江文艺|035|
|中国城市|036|
|中国电力|037|
|中国少年|038|
|童趣出版|039|
|禹田(暖房子)| 040|
|安徽少儿|041|
|天天出版|042|

### 686的实操：
1.	第一字段的判断，第一步原则上是通过690中图分类法去判断，但有时候如果是I712.85，也就是第二字段是 .85 的书，需要继续看215字段的a,标注的如果是40页以内，那么这类书通常是归到了A类，也就是图画书类，这是大类；第二步需要判断是否是立体书，无字书或是漫画书，这个是由225，300，或是606字段去判断。判断结束，再继续分到相应的类。

2.	第一字段的文学类需要判断具体分类，是侦探小说，还是童话寓言，或是历险探险等等，这个需要从225，300或者是606字段判断做初步判断，然后再具体分到相应的类。比如说ISBN: 7-5332-3339-5,题名为《梦幻城堡》，330字段和606字段都出现了科学幻想小说，这本书的690是I561.84，第一科判断是属于I类，但330和606都标注科学幻想，那么这本书最终是归为IK（科幻小说、科普小说），而这本书的225字段标注为“$i外国网络科幻小说精品”因为这本书最终的686写成IK.030.WL.(030是明天出版社的代码，而WL是网络的缩写)

3.	第二字段的判断:所有红泥巴排架法示意图表右侧的有编号的出版社，均属于重点注意出版社，需要分门别类的归到应有的代码中，但有时候并不是所有的这一类出版社都是出现在210的C字段，也需要从225或300字段，但也有特例会出现在200的f字段，比如说人民邮电出版社，通常会在200的f字段出现童趣出版社，这个时候第二字段就不是.RMY.，而是要写成.039.。

4.	第三字段，也是最人性化的一个字段，这个字段说简单点就是系列名，也是通过225和300字段，将一个系列的书用这个字段中出现的两个字的首字母作为这一段的代表，比如说在225字段中出现这样的字“a托马斯和朋友动画故事乐园”,根据统一原则，第三字段写成.TM或者是.LY，也就是托马或是乐园的首字母，这个字段只要是一个系列是统一的就可以，不必纠结是哪两个字，但人工处理时是选择的重点突出的字，一定是能区别于其它套系的书，这样便于图书管理员的查找。再比如：225字段标注“$a米菲绘本系列”那么它的第三字段肯定会是“.MF”。学校在实际使用过程中经常用系列缩写来检索。

**Comment by Hopeshine** [comment]
### 样例数据1：

《你好，月亮》这本书，国图书目数据如下，红泥巴排架分类为：AE.006.HT

001 | -  | 007256278¶
-- | -- | --
005 |   | 20150601004339.0¶
010 | __ | ‡a978-7-5560-2079-9 ‡dCNY18.00¶
100 | __ | ‡a20150601d2015____cemy0chiy50______ea¶
101 | 1_ | ‡achi ‡ceng¶
102 | __ | ‡aCN ‡b420000¶
105 | __ | ‡aa___z___000fy¶
106 | __ | ‡ar¶
200 | 1_ | ‡a你好，月亮 ‡9ni hao ， yue liang ‡f(美)弗朗西斯卡·西蒙文 ‡g(英)本·科特图  ‡g陶莉译¶
210 | __ | ‡a武汉 ‡c长江少年儿童出版社有限公司 ‡d2015¶
215 | __ | ‡a1册 ‡d27cm¶
300 | __ | ‡a海豚绘本花园 383¶
510 | 1_ | ‡aDo you speak English, moon?  ‡zeng¶
606 | 0_ | ‡a图画故事 ‡y美国 ‡z现代¶
686 | __ | ‡aAE.006.HT¶
690 | __ | ‡aI712.85 ‡v5¶
701 | _0 | ‡c(美) ‡a西蒙 ‡9xi meng ‡c(Simon, Francoise) ‡4文¶
702 | _0 | ‡c(英) ‡a科特 ‡9ke te ‡c(Cort, Ben) ‡4图¶
702 | _0 | ‡a陶莉 ‡9tao li ‡4译¶
801 | _0 | ‡aCN ‡b91MARC ‡c20150601¶

由于690$a 内容未I712.85,故必然归到A类（图画、漫画），一级分类AE中的“E”是怎么来的？

从200$f、210$C、225$a、300$a去看出版信息字段，发现300$a中有上述红泥巴排架所定义006编号的出版社信息（海豚传媒），故第二级分类为006。

第三级分类“HT”是怎么来的？书目记录中没有对应信息。

**Comment by Hopeshine** [comment]
样例数据2：《写给孩子的哲学启蒙书》，红泥巴服务器数据如下：

001 |   | 004385671¶
-- | -- | --
005 |   | 20100224091806.0¶
010 | __ | ‡a978-7-5633-8385-6 ‡b精装 ‡dCNY158.00(全6册)¶
100 | __ | ‡a20091212d2009____am_y0chiy0110____ea¶
101 | 1_ | ‡achi ‡cfre¶
102 | __ | ‡aCN ‡b450000¶
105 | __ | ‡aa___z___000yy¶
106 | __ | ‡ar¶
200 | 1_ | ‡a写给孩子的哲学启蒙书 ‡9xie gei hai zi de zhe xue qi meng shu ‡b专著 ‡h1 ‡dLes gouters philo ‡f(法)碧姬·拉贝, (法)米歇尔·毕奇著 ‡g(法)雅克·阿扎姆插图 ‡g潘林，刘岩, 王川娅译  ‡zfre¶
210 | __ | ‡a桂林 ‡c广西师范大学出版社 ‡d2009¶
215 | __ | ‡a6册 ‡c图 ‡d22cm¶
510 | 1_ | ‡aGouters philo ‡zfre¶
606 | 0_ | ‡a人生哲学 ‡j少年读物¶
686 | __ | ‡aB.GXS.QM¶
687 | __ | ‡a117¶
687 | __ | ‡a117¶
690 | __ | ‡aB821 ‡v4¶
701 | _0 | ‡c(法) ‡a拉贝 ‡9la bei ‡c(Labbe, Brigitte) ‡4著¶
701 | _0 | ‡c(法) ‡a毕奇 ‡9bi qi ‡c(Puech, Michel) ‡4著¶
702 | _0 | ‡c(法) ‡a王川娅 ‡9wang chuan ya ‡c(女) ‡4译¶
702 | _0 | ‡c(法) ‡a阿扎姆 ‡9a zha mu ‡c(Azam, Jacques) ‡4插图¶
702 | _0 | ‡a潘林 ‡9pan lin ‡c(女) ‡4译¶
702 | _0 | ‡a刘岩 ‡9liu yan ‡4译¶
801 | _0 | ‡aCN ‡bPUB ‡c20120906¶

690分类的B类对应红泥巴排架的B类，单686$a中B.GXS.QM后面的二级、三级分类是怎么来的?

**Comment by Hopeshine** [comment]
样例数据2：《写给孩子的哲学启蒙书》，红泥巴服务器数据如下：

001 |   | 004385671¶
-- | -- | --
005 |   | 20100224091806.0¶
010 | __ | ‡a978-7-5633-8385-6 ‡b精装 ‡dCNY158.00(全6册)¶
100 | __ | ‡a20091212d2009____am_y0chiy0110____ea¶
101 | 1_ | ‡achi ‡cfre¶
102 | __ | ‡aCN ‡b450000¶
105 | __ | ‡aa___z___000yy¶
106 | __ | ‡ar¶
200 | 1_ | ‡a写给孩子的哲学启蒙书 ‡9xie gei hai zi de zhe xue qi meng shu ‡b专著 ‡h1 ‡dLes gouters philo ‡f(法)碧姬·拉贝, (法)米歇尔·毕奇著 ‡g(法)雅克·阿扎姆插图 ‡g潘林，刘岩, 王川娅译  ‡zfre¶
210 | __ | ‡a桂林 ‡c广西师范大学出版社 ‡d2009¶
215 | __ | ‡a6册 ‡c图 ‡d22cm¶
510 | 1_ | ‡aGouters philo ‡zfre¶
606 | 0_ | ‡a人生哲学 ‡j少年读物¶
686 | __ | ‡aB.GXS.QM¶
687 | __ | ‡a117¶
687 | __ | ‡a117¶
690 | __ | ‡aB821 ‡v4¶
701 | _0 | ‡c(法) ‡a拉贝 ‡9la bei ‡c(Labbe, Brigitte) ‡4著¶
701 | _0 | ‡c(法) ‡a毕奇 ‡9bi qi ‡c(Puech, Michel) ‡4著¶
702 | _0 | ‡c(法) ‡a王川娅 ‡9wang chuan ya ‡c(女) ‡4译¶
702 | _0 | ‡c(法) ‡a阿扎姆 ‡9a zha mu ‡c(Azam, Jacques) ‡4插图¶
702 | _0 | ‡a潘林 ‡9pan lin ‡c(女) ‡4译¶
702 | _0 | ‡a刘岩 ‡9liu yan ‡4译¶
801 | _0 | ‡aCN ‡bPUB ‡c20120906¶

690分类的B类对应红泥巴排架的B类，单686$a中B.GXS.QM后面的二级、三级分类是怎么来的?

**Comment by renyh** [comment]
暂时不用做了
