### ISSUE TITLE
大备份过程中遇到的报错提示及解决方法

### ISSUE THREAD

**Issue by 792955994** [DigitalPlatform/dp2#592]
### 报错一：

<img src='https://user-images.githubusercontent.com/57248222/68468522-28e72700-0253-11ea-9d01-381e577ecc08.png' width='300px'/>

**解决方法：点击确定，重新下载**

***

### 报错二：

<img src='https://user-images.githubusercontent.com/33890036/74701006-5410e780-5240-11ea-8b4f-38dca7164ce3.png' width='400px'/>

可能原因：

1. 网络问题导致下载中断；

2. 下载过程中服务器升级，导致网络中断

**解决方法：**

1. 如果下载过程中服务器没有升级：检查网线是否松动了，无线wifi是否中断，恢复网络后，点击【确定】后重新下载；

2. 如果下载过程中网络没有问题，是因为服务器升级而中断，直接点击【确定】后重新下载

***
### 报错三
<img src='https://user-images.githubusercontent.com/33890036/74701752-c2ef4000-5242-11ea-976b-b58b4783da40.png' width='400px'/>

原因：用户采用了边备份边下载的方式，想把大备份文件下载到其他服务器的共享磁盘上。但因为目标系统的磁盘文件类型不对，比如 FAT32 的磁盘，不支持 2G 以上的大文件，导致下载过程报错。**从报错文字`Type:system.IO.IO Exception`、`System.IO.FileStream.WriteCore (byte[] buffer Int32 offset,In32 cout)`可以判断与磁盘文件类型或者磁盘空间有关。（磁盘空间不足也会出现这样的报错信息）**

**解决方法**：先选择备份下载写入本地电脑硬盘。完成以后再重新拷贝文件到其他服务器磁盘。如果仍然存在问题，说明是磁盘的原因；存储磁盘格式选择为 NTFS 文件系统作为备份存储。

该问题待实际验证。

验证方式：
重现：找一个 U 盘，格式化为 FAT32 文件系统。然后找一个单位的 dp2library 服务器，确保大备份文件大小会超过 2G。然后用内务进行大备份，下载时候选择直接把文件写入 U 盘。这样应该就能暴露出问题。
U 盘如果格式化为 NTFS 文件系统则不会有这个问题

**Comment by renyh** [comment]
![image](https://user-images.githubusercontent.com/13568719/68556039-8e156500-046b-11ea-87f7-53eae70f4ae0.png)

可能是升级了服务器，导致中断，点 确定 重新从断点下载。

**Comment by Hopeshine** [comment]
已纳入“备份与恢复”文档系统。
