### ISSUE TITLE
创建报表checklist

### ISSUE THREAD

**Issue by renyh** [DigitalPlatform/dp2#594]
### 首次创建报表的步骤
1.在dp2内务系统内点击【功能】-【统计窗】-【报表窗】-“开始”下面点击【首次创建本地存储】
2.打开“报表配置”-点击【创建分馆配置】（不需要修改任何配置直接点击确【确定】即可”）或【自动创建全部分馆配置】
3.在dp2内务左下角，点击【设置创建起始日期】会弹出一个对话框“报表创建起始日期”设置为“20180101”后点击确定
4.点击【每日报表】
5. 选择“上传方式”为“dp2library”
6. 点击【上传报表】

### 后续创建报表的步骤
1.点击【每日同步】
2.点击【每日报表】
3.“上传方式”选择【dp2library】
4.点击【上传报表】

**Comment by renyh** [comment]
### 如何重新生成报表

原由：发现有些实例报表创建了单个读者报表131，导致报表尺寸很大，所以需要对某些实例需要重新创建报表。
操作步骤：
1. 先在服务器上删除对应实例的报表，删除前记一下报表目录的尺寸。
2. 在创建报表的本地电脑上，内务登录对应实例，在报表窗检查报表配置，不要创建131报表。
3. 将报表开始时间改为20180101，然后重新生成报表。（此时不需要重建本地存储）
4. 上传报表，然后到服务器查看一下报表尺寸，记录下来。

**Comment by 792955994** [comment]
### 如何在服务器上删除统计报表文件夹
1.在本地电脑打开【windows附件】——【远程桌面连接】
2.在远程桌面连接输入服务器地址和账号密码——点击【连接】——弹出一个安全提示框点击【是】
3.登录到服务器后打开D盘——打开“cloud-data”文件夹——打开需要删除统计报表的实例文件夹（例如：chonghua）——打开“library-data”文件夹——打开“uploud”文件夹——右键“reports”文件夹查看属性记录文件夹大小——删除整个“reports”文件夹

**Comment by renyh** [comment]
已移至wki，关闭该issue
