### ISSUE TITLE
如何进行日志备份

### ISSUE THREAD

**Issue by 792955994** [DigitalPlatform/dp2#595]
### 如何在dp2内务中进行日志备份
1.打开dp2内务点击顶部菜单栏【功能】——【系统维护】——【批处理任务窗】
2.“任务名”——下拉选择【日志备份】——点击【开始】
3.弹出“浏览文件夹”选择下载路径，选择操作日志备份目录下对应的实例文件夹下

**Comment by renyh** [comment]
已迁至wiki
