### ISSUE TITLE
剔旧图书信息统计

### ISSUE THREAD

**Issue by 792955994** [DigitalPlatform/dp2#604]
### 需求：统计出图书馆内所有剔旧掉的图书的馆藏清单，
![image](https://user-images.githubusercontent.com/57248222/69303383-b9f8cd80-0c57-11ea-85e1-59a38869c4cc.png)

分析：该需求所导出的数据既需要从实体记录的状态来定义筛查对象，并且需要导出的内容包含书目信息。

在【功能】-【统计窗】-【书目统计窗】，运行【图书馆藏清单】得到的结果里面所有统计的册数包含剔旧和丢失的数据，无法满足需要。

**处理方式：在【实体查询窗】配置书目列定义，检索出剔旧的图书后导出到excel档。然后在Excel档里面进行统计。**

如何定义显示书目列信息，请参看文档：[内务实体查询窗新增定义书目列、导出册信息 Excel ](https://github.com/DigitalPlatform/dp2/issues/614)

当需要导出的图书信息包含有关书目和册记录的信息时，都可以比照处理。

**Comment by Hopeshine** [comment]
已纳入文档系统
