### ISSUE TITLE
关于规范价格

### ISSUE THREAD

**Issue by 792955994** [DigitalPlatform/dp2#606]
【关于册价格】
册价格对于财产统计和可能的赔偿计算相关，因此规范登记是非常必要的。在册价格中规范的要求是：单册价格、包含货币代码、不包含汉字，比如：CNY12.00
在图书编目的定价记录（010$字段）中常见一些与册价格规范并不相符的形式，利用通配符@price，无法调出合乎规范的结果，这时就必须手工修改了。比如以下几种情形：
1、CNY19.30(含光盘) → 应当修改为 CNY19.30
2、CNY87.50(全套7册) 这种情况是全套书7册，全套87.50，单册12.50，可以修改为两种形式：CNY12.50  或者 CNY87.50/7
3、CNY890.00(全33册) 这种情况当然也可以计算出单册的价格，但结果是个除不尽的数字，必须四舍五入，这种情况建议修改为：CNY890.00/33
4、￥10.80 → 应当修改为 CNY10.80
5、2.80 → 应当修改为 CNY2.80
统一货币代码对于财产统计的准确性很有帮助。

**Comment by renyh** [comment]
已经转移至wiki
