### ISSUE TITLE
如何设计打印标签

### ISSUE THREAD

**Issue by 792955994** [DigitalPlatform/dp2#610]
**一．打印前准备好相关数据来源文件（txt文件）详细步骤参考下方文档**
如何制作条码号文件和记录路径文件
https://github.com/DigitalPlatform/dp2/issues/429

**二．打印标签的操作流程**

参考下方链接视频
http://dp2003.com/video/1.17%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C-%E6%89%93%E5%8D%B0%E4%B9%A6%E8%84%8A%E6%A0%87%E7%AD%BE.mp4

**以下主要讲述打印卷装标签如何设计**

在打印标签的过程中，在【执行统计】点击“下一步”之后，弹出一个对话框显示“共输出标签多少个，……”点击“确定”弹出“标签打印窗
![image](https://user-images.githubusercontent.com/57248222/69853561-33c93080-12c2-11ea-896c-02b892a03362.png)
![image](https://user-images.githubusercontent.com/57248222/69853597-47749700-12c2-11ea-80c3-8537306c5210.png)

在【标签打印窗】点击“标签定义文件名输入框后面的【设计】按钮进入【标签设计】页面
![image](https://user-images.githubusercontent.com/57248222/69853613-4f343b80-12c2-11ea-98b0-c347f9fbc633.png)

**三．标签设计**

**1.	【页面】属性页设计便签页面尺寸**
如果是单页打印纸指的是页面纸张的整体大小，如果是卷状打印纸指的是一排打印标签纸所在页面的大小，如下图
 
![image](https://user-images.githubusercontent.com/57248222/69853626-58250d00-12c2-11ea-9d65-d7ecaa09bc2e.png)

单页标签纸
 
![image](https://user-images.githubusercontent.com/57248222/69853636-5d825780-12c2-11ea-90fc-17fb189d15b6.png)

卷装标签纸

**2.	选择“手动设定页面尺寸”**

页面高度：用直尺一次性测量多个标签的高度（尽量多量一些），然后取平均值
(注意：例如测量五个标签高度时要从第一个标签的左侧至第六个标签的左侧测量，然后取平均值，这个数值包含了标签之间的间距）
例如下图：161÷5＝32.2（毫米）
 
![image](https://user-images.githubusercontent.com/57248222/69853657-670bbf80-12c2-11ea-9a11-3a2e8fea0617.png)

页面宽度=直尺测量整个标签纸的宽度
（注意：普通直尺测量时单位是厘米，系统内使用的单位是毫米，填写时注意将厘米换算成毫米）
 
![image](https://user-images.githubusercontent.com/57248222/69853676-6f63fa80-12c2-11ea-8667-d43c8ca8f3a0.png)

内容边距：固定设置为0,0,0,0
勾选【显示调试线】，以方便预览打印效果，注意在打印时将其关闭。
尺寸单位：选择【毫米】     小数位数：输入1即可
 
![image](https://user-images.githubusercontent.com/57248222/69853699-75f27200-12c2-11ea-8eaf-93d2864677bf.png)

**3.	【标签】属性页设计标签参数**

标签宽度（包含两个标签间距）：用直尺测量整个标签纸所在页面的宽度÷标签数量=标签的平均宽度

注意：实际设置时将数值调小0.5-1毫米
如下图：测量数据84÷2=42          实际填写数据41.5 
![image](https://user-images.githubusercontent.com/57248222/69853713-81459d80-12c2-11ea-8a3d-ae0b58491022.png)

标签高度：用直尺测量单个标签的高度=页面的高度
注意：实际设置时将数字调小0.5-1毫米
如下图：测量数据161÷5=32.2        实际填写数据：31.7
 
![image](https://user-images.githubusercontent.com/57248222/69853722-87d41500-12c2-11ea-90aa-c0e483209be0.png)

如果标签高度/宽度大与或等于页面的宽度/高度可能会导致系统出错（预览效果时会打印无穷多页），无法进行打印。
例如：如图当【标签高度】与【页面高度】相同时系统就会出错，无法预览打印效果
   
![image](https://user-images.githubusercontent.com/57248222/69853733-928eaa00-12c2-11ea-8e8a-5fe907023c66.png)
![image](https://user-images.githubusercontent.com/57248222/69853742-98848b00-12c2-11ea-8164-ed3af0aa8480.png)

内容边距：固定设置为0,0,0,0
（内容边距指的是打印的内容与标签边缘之间的距离）
标签字体:  使用默认字体或选择其他字体都可以
点击【标签字体】按钮可以进行自定义设置字体
勾选【外框】（外框就是辅助设计的参考线）
尺寸单位：选择【毫米】    小数位数：输入1即可
 
![image](https://user-images.githubusercontent.com/57248222/69853755-9fab9900-12c2-11ea-90d7-ebb921eb25ad.png)

**4.	行格式（指的是打印内容的格式）**

“字体”表示的是打印内容的字体和大小
“对齐”表示的是打印内容与打印标签纸的对齐方式
“起始位置”固定为空
“偏移”表示的是打印内容在打印纸上位置移动的距离
①	双击进入“位置”页面
起始位置X，起始位置Y，宽度和高度都不需要设置
偏移X：数值的大小表示标签内容左右移动的距离，数值增大，内容向右移动，数值减小内容向左移动。
偏移Y：数值的大小表示标签内容上下移动的距离，数值增大，
内容向下移动，数值减小内容向上移动。
 
![image](https://user-images.githubusercontent.com/57248222/69853773-aa662e00-12c2-11ea-868b-e41b32566f8f.png)

点击第一行“times New Roman，18pt center”修改的是标签第一行的内容
点击第二行“times New Roman，18pt center”修改的是标签第二行的内容
 
![image](https://user-images.githubusercontent.com/57248222/69853786-b18d3c00-12c2-11ea-92a1-c2635764e517.png)

②	在“times New Roman，18pt center”上右键点击【修改】进入“文字”页面下“风格”设为“text_style:auto_fit” 可以使文字自动缩小适应尺寸，不超出范围
 
![image](https://user-images.githubusercontent.com/57248222/69853796-b81bb380-12c2-11ea-9f91-59aad9445036.png)

行间距固定设置为“0.0”
 
![image](https://user-images.githubusercontent.com/57248222/69853804-bf42c180-12c2-11ea-926a-cac2d9a2dbd8.png)

**五．设置好之后点击【打印】**
 
![image](https://user-images.githubusercontent.com/57248222/69853828-d08bce00-12c2-11ea-863d-c3c90e96193a.png)

使用技巧：在【标签设计】页面【XML】属性页，里面的内容包含所有配置信息，用户可以将这些内容保存到txt文件，拷贝在其他电脑上内务中对应的位置，从而可以在其他电脑上使用相同的方案打印标签，无需重新配置。

**Comment by Hopeshine** [comment]
已纳入“图书管理”文档系统
