### ISSUE TITLE
如何新增书目的690字段与重建索取号并打印标签

### ISSUE THREAD

**Issue by 792955994** [DigitalPlatform/dp2#611]
### 一．如何增加/修改书目的690字段

**第一步**：打开dp2内务，在菜单【常用窗口】—【种册窗】后进入种册窗操作页面，

**第二步**：在页面的上半部分找到“检索工具条”，在【检索】按钮前面的“输入框”输入图书的ISBN号
检索出对应的书目记录

**第三步**：在“书目”信息一栏种中使用滚动条上下滑动找到对应的“690“字段

**第四步**：鼠标左键单击到“690“字段所处的位置后，右键单击后选择【插入新字段-前插】
在原“690“字段上面出现一行空的字段，鼠标左键单击在蓝色”***“的位置输入”690“

**第五步**：在后面黑色的“▼a”后面输入对应的分类号，
点击右下角的【全部保存】按钮，系统会弹出绿色的提示框“记录保存成功”
此时”书目”信息里的“690”字段就增加/修改成功。

**小常识：**
①可在【书目查询窗】中浏览列【中图法分类号】一列看到所有的690字段分类号。
②不建议将原来的690字段删除，可以方便日后想要查看原本690字段的内容时查看。

### 二．如何单个或批量处理创建“索取号”

**1.单个创建索取号**

**总体操作步骤：**
检索出单条册记录——创建索取号——确定完成

**详细操作步骤：**

**第一步**. 先在打开dp2内务【实体查询窗】检索出对应的册记录，在顶部菜单栏找到并点击【常用窗口】在点击打开【实体查询窗】后进入实体查询窗操作页面，在“简单”页面下“检索词”后面的输入框中输入对应的检索词，“实体库”默认是“全部”不需要进行修改，“检索途径”可以根据自己的需求进行选择（常用的检索途径包括“册条码号”“馆藏地”“-id”），“匹配方式”建议选择“中间一致”这样检索的范围更宽，更容易找到需要检索出的信息。

**第二步**.选中册记录鼠标右键【功能-创建索取号】弹出提示框“在后面即将进行的处理过程中，对已经存在索取号的册记录，是否重新创建索取号？“点击选择【是】

**第三步**.弹出提示框“共处理1个册记录”点击确定就完成了本次操作。

**2．如何批量创建“索取号”**

**总体操作流程**：
准备txt导入文件——导入txt文件——选中全部数据——创建索取号——确定完成

**详细操作流程**：

**第一步**.先将所有需要创建索取号的图书册条码号使用扫码枪扫描到“txt”文本文件中

**第二步**.打开dp2内务，在顶部菜单栏找到并点击【常用窗口】点击打开【实体查询窗】后进入实体查询窗操作页面

**第三步**.在下半部分的结果浏览列表空白处，鼠标单击右键点击【导入-从条码号文件中导入】将 第1步创建的“txt”条码号文件导入进来

**第四步**.导入成功后鼠标单击右键点击【全选】

**第五步**.全部选中后鼠标再单击右键点击【功能-创建索取号】弹出提示框“在后面即将进行的处理过程中，对已经存在索取号的册记录，是否重新创建索取号？“——点击选择【是】——弹出提示框“共处理***个册记录”点击确定就完成了本次操作。

**注意**：重建索取号之后一定要记得将原先贴有旧索取号的图书重新帖上新的标签，
打印标签的方法详细方法打开后面链接：https://github.com/DigitalPlatform/dp2/issues/610

**Comment by Hopeshine** [comment]
已纳入“图书管理”文档系统
