### ISSUE TITLE
内务实体查询窗新增定义书目列、导出册信息 Excel 文件功能

### ISSUE THREAD

**Issue by DigitalPlatform** [DigitalPlatform/dp2#614]
# 定义书目列

最新版内务前端的实体查询窗新增了为浏览格式定义书目列的功能。

用法如下：
1) 打开一个实体查询窗；
2) 在浏览列表的空白区或者内容行上点右鼠标键，出现上下文菜单，在里面用“设置书目栏目”命令，会出现一个“书目信息列”对话框；
3) 在对话框里面可以调整列定义。每一行代表一个书目信息列。可以增加、删除列；还可以调整这些列的先后顺序。定义完成后，点“确定”按钮关闭这个对话框，下一次检索的时候，显示的就是刚定义好的书目信息列了。

当第一次开始定义的时候，所出现的书目列是软件默认的一些列。如果删除了全部列并点“确认”按钮退出对话框，下次再打开这个对话框的时候，会再次出现软件默认的列。就是说如果想回到软件默认定义的列，可以通过删除全部列来实现。

注意这些列定义中，"biblio_isbd"这个列是用 ISBD 格式在一个列里面容纳一条书目记录的全部主要信息，如果只定义这样一个书目列，也就可以实现和内务升级以前的版本一样的显示效果。

**Comment by DigitalPlatform** [comment]
# 导出册详细信息 Excel 文件

最新内务前端增加了导出册详细信息 Excel 文件功能。

用法如下：
1) 打开实体查询窗，检索命中一批册记录进入浏览列表；
2) 全选或部分选择想要导出的册信息行(操作方法是在浏览列表上下文菜单上用“全选”命令，或者按住 Ctrl 或 Shift 键点鼠标选择要导出的浏览行)；
3) 在浏览列表上调出上下文菜单(操作方法是在浏览列表上点右鼠标键)，使用“导出/册详细信息到 Excel 文件”命令。会出现一个“保存到册信息 Excel 文件”对话框。用法后面会详述。这里指定输出的 Excel 文件名(文件扩展名为 .xlsx)，点“确定”按钮。软件会把刚才选择的册记录导出创建一个 Excel 文件并自动打开。

# “保存到册信息 Excel 文件”对话框 用法

**Comment by Hopeshine** [comment]
已纳入文档系统
