### ISSUE TITLE
批量清理图书并导出Excel文档 操作步骤

### ISSUE THREAD

**Issue by 792955994** [DigitalPlatform/dp2#615]
**视频链接教程：**
**清理图书流程(保存到不允许流通的馆藏地)**
http://dp2003.com/video/S2019003-清理图书流程(保存到不允许流通的馆藏地).mp4

# 一.创建新的图书清查库
新增/修改/删除馆藏地的操作必须要具备setsystemparameter权限的账号才能进行。用户需要先通过具备setsystemparameter权限的账号进入dp2内务

### 进入【馆藏地】属性页
 在dp2内务中依次点击【功能】-【系统维护】-【系统管理窗】。在打开的【系统管理窗】中，切换到【馆藏地】属性页。

### 进入【馆藏地】对话框
在【馆藏地】属性页的空白处点击鼠标右键，从右键菜单选择【新增】选项；或者点击【馆藏地】属性页下方工具条上的【新增】按钮，系统弹出【馆藏地】对话框。

### 设置馆藏地
在【馆藏地】对话框中，用户在【馆藏地名称】文本框中输入拟定的馆藏地点名称（[馆藏地命名说明](https://github.com/DigitalPlatform/dp2/issues/216)），并根据实际要求决定是否勾选【册条码号可为空】和【允许外借】。

不勾选【册条码号可为空】，表示保存到该馆藏地的册记录必须具有册条码号才能保存成功；勾选，则表示保存到该馆藏地的册记录中册条码号可以为空；

不勾选【允许外借】选项，表示该馆藏地的册不可外借，读者不能将该馆藏的图书借出；勾选，则表示该馆藏地的册可以外借。

如果是总分馆模式，【馆藏地】对话框中第一栏增加显示了【馆代码】文本框，并且【馆代码】文本框的下拉列表会根据当前账号权限进行显示。用户在这里设置所建馆藏地所属的分馆。如果是全局账号建立馆藏地，此处可以设置为【空】，代表总馆。

然后单击【确定】按钮。新建的馆代码显示到【馆藏地】属性页列表中。

### 保存新增的馆藏地
用户需要点击【馆藏地】属性页下方工具条上的【保存】按钮，新增的馆藏地才会正式保存到系统当中。

新增馆藏地后，要记得到【系统维护】-【系统管理窗】-【排架体系】属性页，对新增的馆藏地进行排架定义。这样后续册登记时系统才会根据定义的排架来生成对应的索取号。如何定义排架，请参考文档[如何配置排架体系](https://github.com/DigitalPlatform/dp2/wiki/%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E6%8E%92%E6%9E%B6%E4%BD%93%E7%B3%BB)
用户需要点击【馆藏地】属性页下方工具条上的【保存】按钮，修改的馆藏地才会正式保存到系统当中。

# 二.将清理图书条码号制作成txt文本文档文件
1.在电脑本地新建一个文本文档（.txt后缀，编码为：UTF-8）

2.使用条码枪将所有需要清理的图书的册条码号扫入

3.打开【文件】-点击【保存】

# 三.批处理
打开dp2内务，点击菜单“常用窗口/实体查询窗”，在实体查询窗下方的结果列表空白处右键：【导入】-【从条码号文件导入】导入刚才制作的条码号文件，系统自动装载对应的册记录。
右键全选这些册记录，然后单击右键命令“批处理/快速修改册记录"，系统弹出【快速修改册记录-请制定动作参数】对话框；

点击【新增】，弹出【一个修改动作】对话框，字段名选择“状态”或“馆藏地”
1）如果需要将所选的记录设置为“注销”状态。用户选择【字段名】为“状态”后，【字段值】一栏下拉选择<增，减>，需要增加时，在【增】一栏文本框输入内容，如果需要将图书的状态改为“剔旧”或“下架”，那就在文本输入框内输入“剔旧”或“下架”。（如果需要将已有的状态消除，则在【减】一栏选择对应的内容）。
2）如果要批处理“馆藏地”，选择【字段名】为“馆藏地”，然后【字段值】一栏直接从文本框右侧下拉列表选择设置。
点击【确定】按钮，

3）系统执行预处理，然后弹出提示【修改册记录* 条，修改并未自动保存，请在观察确认后，使用保存命令将修改保存回实体库】。用户点击【确定】，提示框关闭，回到【实体查询窗】。

4）回到【实体查询窗】后，刚才选定的记录仍然出于选中状态（以蓝色背景显示选中），用户在已选择的任意实体记录上单击鼠标右键，从右键菜单选择【批处理】-【保存全部修改】或者【保存选定的修改】，系统弹出提示框，提示【处理完成，共保存实体记录~*~条】。

# 四.将清理图书数据导出表格

**1.检索出清理图书**
1）已经修改过清理图书的状态的，可以通过状态字段检索出来。

2）如果是通过移交到一个特殊馆藏地实现清理图书的，那么可以用馆藏地名字检索出来。

3）还可以将那些清理图书的条码号导入

### 导出Excel文件方法一：
**在【实体查询窗】 用 “册详细信息到 Excel 文件”功能导出文件（推荐使用这个方法）

操作步骤：全部选中检索出的结果，点击右键【导出】——【册详细信息到 Excel 文件】，弹出对话框，配置相关信息确定。

如何配置：
对话框分为两个属性页：“如何输出” 和“配置”。

 **“如何输出”属性页**
在这个属性页指定用于过滤册记录的馆代码，和要创建的 Excel 文件名。

馆代码列表里面，可以选择`[仅总馆]`、`[总馆和全部分馆]`和各个分馆的馆代码。`[仅总馆]`表示本次导出会经过筛选后仅输出馆藏地属于总馆的部分册记录；`[总馆和全部分馆]`表示本次导出要经过删选后输出总馆和全部分馆的册记录信息，其实也就是全部册记录信息。

 **“配置”属性页**
本属性页可以配置输出的书目信息列，和册信息列。

“书目信息列”按钮用于配置书目信息列。点它会出现一个对话框，里面可以定义书目信息列。像书名、作者、出版社等字段都是属于书目信息的列。

“册信息列”按钮用于配置册信息列。点它会出现一个对话框，里面可以定义册信息列。像册条码号、馆藏地、索取号、册价格等字段都是属于册信息的列。

### 列定义对话框用法

对话框右侧的“新增”、“修改”和“删除”按钮用于定义列。“上移”和“下移”按钮用于调整各列的先后顺序。

***
### 导出Excel文件方法二：
**在实体查询窗自定义修改书目信息栏后，导出到Excel文件。**

在实体查询窗下浏览列空白处鼠标右键点击【设置书目栏目】弹出一个【书目信息列】页面，在这个页面可以自定义浏览列中“书目信息列”的内容与排列顺序

1).单击选中其中一条可以通过【上移】【下移】按钮调整它的排列顺序

2)【新增】可以在已有的书目信息列后面自定义增加一条书目信息。
   点击【新增】弹出【一个栏目】页面，
   点击【栏目名】输入框后面的下拉按钮【选择】想要新增的书目信息列，
         【标题文字】可以自定义修改，也可以保持默认名称，
         【栏宽字符数】和【截断字符数】【脚本】不要修改。
   点击【确定】之后回到【书目信息列页面】确认都已修改完成之后点击右下角【确定】。
**点击确定之后实体查询窗下面的浏览列会自动清空**，
点击【检索词】后面的【放大镜】按钮重新检索就可以检索出新配置好的实体书目信息列。

3）将检索出的图书信息右键【全选】中后再右键【导出到Excel文件】

**Comment by 792955994** [comment]
**视频链接教程：**
**清理图书流程(保存到不允许流通的馆藏地)**
http://dp2003.com/video/S2019003-%E6%B8%85%E7%90%86%E5%9B%BE%E4%B9%A6%E6%B5%81%E7%A8%8B(%E4%BF%9D%E5%AD%98%E5%88%B0%E4%B8%8D%E5%85%81%E8%AE%B8%E6%B5%81%E9%80%9A%E7%9A%84%E9%A6%86%E8%97%8F%E5%9C%B0).mp4
### 一.创建新的图书清查库
新增/修改/删除馆藏地的操作必须要具备setsystemparameter权限的账号才能进行。用户需要先通过具备setsystemparameter权限的账号进入dp2内务

# 1. 新增馆藏地
## 1. 进入【馆藏地】属性页
 在dp2内务中依次点击【功能】-【系统维护】-【系统管理窗】。在打开的【系统管理窗】中，切换到【馆藏地】属性页。

## 2.进入【馆藏地】对话框
在【馆藏地】属性页的空白处点击鼠标右键，从右键菜单选择【新增】选项；或者点击【馆藏地】属性页下方工具条上的【新增】按钮，系统弹出【馆藏地】对话框。

## 3. 设置馆藏地
在【馆藏地】对话框中，用户在【馆藏地名称】文本框中输入拟定的馆藏地点名称（[馆藏地命名说明](https://github.com/DigitalPlatform/dp2/issues/216)），并根据实际要求决定是否勾选【册条码号可为空】和【允许外借】。

不勾选【册条码号可为空】，表示保存到该馆藏地的册记录必须具有册条码号才能保存成功；勾选，则表示保存到该馆藏地的册记录中册条码号可以为空；

不勾选【允许外借】选项，表示该馆藏地的册不可外借，读者不能将该馆藏的图书借出；勾选，则表示该馆藏地的册可以外借。

如果是总分馆模式，【馆藏地】对话框中第一栏增加显示了【馆代码】文本框，并且【馆代码】文本框的下拉列表会根据当前账号权限进行显示。用户在这里设置所建馆藏地所属的分馆。如果是全局账号建立馆藏地，此处可以设置为【空】，代表总馆。

然后单击【确定】按钮。新建的馆代码显示到【馆藏地】属性页列表中。

## 4. 保存新增的馆藏地
用户需要点击【馆藏地】属性页下方工具条上的【保存】按钮，新增的馆藏地才会正式保存到系统当中。

新增馆藏地后，要记得到【系统维护】-【系统管理窗】-【排架体系】属性页，对新增的馆藏地进行排架定义。这样后续册登记时系统才会根据定义的排架来生成对应的索取号。如何定义排架，请参考文档[如何配置排架体系](https://github.com/DigitalPlatform/dp2/wiki/%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E6%8E%92%E6%9E%B6%E4%BD%93%E7%B3%BB)

## 5. 如何修改馆藏地
在【馆藏地】属性页里，先选中需要修改的馆藏地，

用户可以通过在所选馆藏地上单击鼠标右键，从右键菜单里面选择【修改】命令；或者点击属性页左下方的窗口工具条上的【修改】按钮；或者直接在需要修改的馆藏地上双击，进入【馆藏地】对话框。

在【馆藏地】对话框里修改相关的内容之后，点击【确定】按钮。此时修改后的馆藏地显示到【馆藏地】属性页列表中。


用户需要点击【馆藏地】属性页下方工具条上的【保存】按钮，修改的馆藏地才会正式保存到系统当中。

## 6. 如何删除馆藏地
在【馆藏地】属性页里，先选中需要删除的馆藏地

用户可以通过在所选馆藏地上单击鼠标右键，从右键菜单里面选择【删除】命令；或者点击属性页左下方的窗口工具条上的【删除】按钮，

系统弹出【ManegerForm】对话框，提醒用户确认是否真的要删除该馆藏地，

用户点击【是】按钮，该馆藏地从【馆藏地】属性页里消失。

用户需要点击【馆藏地】属性页下方工具条上的【保存】按钮，刚才所做的删除才会正式保存到系统当中。
### 二.将清理图书条码号制作成txt文本文档文件
1.在电脑本地新建一个文本文档（.txt后缀，编码为：UTF-8）

2.使用条码枪将所有需要清理的图书的册条码号扫入

3.打开【文件】-点击【保存】


### 三.在实体查询窗种【导入】-【从条码号文件导入】
### 1. 打开dp2内务
点击选择：常用窗口-实体查询窗
在实体查询窗页面，“路径”标签下方空白处右键：【导入】-【从条码号文件导入】导入这样刚才制作的导入文件的数据就全部倒入了

### 四.【全选】-【批处理】-【快速修改册记录】-【保存全部修改】
## 批处理

在已选择的任意册记录上单击鼠标右键，从右键菜单选择【批处理】-【快速修改册记录】，系统弹出【快速修改册记录-请制定动作参数】对话框；

点击【新增】，弹出【一个修改动作】对话框，用户在【字段名】文本框里下拉选择需要修改的字段名，以下以【字段名】为“状态”和“馆藏地”为例描述修改步骤。

1.如果需要将所选的记录设置为“注销”状态。用户选择【字段名】为“状态”后，【字段值】一栏下拉选择<增，减>，需要增加时，在【增】一栏文本框输入内容，如果需要将图书的状态改为“剔旧”或“下架”，那就在文本输入框内输入“剔旧”或“下架”。（如果需要将已有的状态消除，则在【减】一栏选择对应的内容）。

**2.如果要批处理“馆藏地”，选择【字段名】为“馆藏地”，然后【字段值】一栏直接从文本框右侧下拉列表选择设置。**

除了批处理“状态”字段以外，其他字段的处理与批处理“馆藏地”雷同。如果需要处理的【字段值】一栏没有下拉列表时，需要用户自行输入字段值。

3.以上设置好后，点击【确定】按钮，关闭【一个修改动作】对话框，回到【快速修改册记录-请制定动作参数】对话框。

4.用户在【快速修改册记录-请制定动作参数】对话框上点击【确定】按钮，系统弹出提示框，提示【修改册记录* 条，修改并未自动保存，请在观察确认后，使用保存命令将修改保存回实体库】。用户点击【确定】，提示框关闭，回到【实体查询窗】。

保存修改
回到【实体查询窗】后，刚才选定的记录仍然出于选中状态（以蓝色背景显示选中），用户在已选择的任意实体记录上单击鼠标右键，从右键菜单选择【批处理】-【保存全部修改】或者【保存选定的修改】，系统弹出提示框，提示【处理完成，共保存实体记录~*~条】。

### 五.将清理图书数据导出表格

**1.检索出清理图书**
①已经修改过清理图书的状态的，可以通过状态字段检索出来。

②如果是通过移交到一个特殊馆藏地实现清理图书的，那么可以用馆藏地名字检索出来。

③还可以将那些清理图书的条码号导入

**2.在实体查询窗自定义修改书目信息栏后，导出到Excel文件。**

在实体查询窗下浏览列空白处鼠标右键点击【设置书目栏目】弹出一个【书目信息列】页面，在这个页面可以自定义浏览列中“书目信息列”的内容与排列顺序

①.单击选中其中一条可以通过【上移】【下移】按钮调整它的排列顺序

②【新增】可以在已有的书目信息列后面自定义增加一条书目信息。
   点击【新增】弹出【一个栏目】页面，
   点击【栏目名】输入框后面的下拉按钮【选择】想要新增的书目信息列，
         【标题文字】可以自定义修改，也可以保持默认名称，
         【栏宽字符数】和【截断字符数】【脚本】不要修改。
   点击【确定】之后回到【书目信息列页面】确认都已修改完成之后点击右下角【确定】。
**点击确定之后实体查询窗下面的浏览列会自动清空**，
点击【检索词】后面的【放大镜】按钮重新检索就可以检索出新配置好的实体书目信息列。

③将检索出的图书信息右键【全选】中后再右键【导出到Excel文件】

**Comment by Hopeshine** [comment]
已纳入“图书管理”文档系统
