### ISSUE TITLE
如何使用psr步骤记录器

### ISSUE THREAD

**Issue by 792955994** [DigitalPlatform/dp2#619]
打开PSR工具
点击系统开始菜单，在搜索栏搜索PSR，打开PSR问题录制小工具。
<img width="586" alt="image" src="https://user-images.githubusercontent.com/57248222/71159018-e831f300-227f-11ea-82b6-18c0ead5399e.png">

开始记录
打开问题步骤记录器后，可以开始录制了。点击开始记录，并点击最小化，录制开始了。

操作问题
以操作网络连接为例：让网上禁用启用操作。

停止录制
问题录制完成后，点击停止记录，这时会弹出保存界面，输入文件名，点击保存即可。

**Comment by Hopeshine** [comment]
已纳入文档系统
