### ISSUE TITLE
如何转换ISBN号

### ISSUE THREAD

**Issue by 792955994** [DigitalPlatform/dp2#620]
在dp2内务中点击顶部菜单栏[**帮助**]-[**实用工具**]-[**ISBN**]

将需要转换的ISBN号复制粘贴到空白处后

点击下方【**13---10**】或【**10---13**】或【**去掉横杠**】

可以实现10位和13位之间的转换

**Comment by renyh** [comment]
在 服务常见问题 中有记录，此issue关闭。
