### ISSUE TITLE
新安装的OPAC在统计信息下缺少【表/图/报表】子栏目

### ISSUE THREAD

**Issue by renyh** [DigitalPlatform/dp2#668]
最新dp2installer升级过的服务器模块，为一个dp2实例全新安装OPAC，然后在浏览器打开OPAC，发现在【统计信息】下缺少【表/图/报表】子栏目。发下图：
![image](https://user-images.githubusercontent.com/13568719/78749008-ef504e80-799f-11ea-9353-8d79da41c567.png)

**Comment by DigitalPlatform** [comment]
这是因为 dp2installer 和 dp2libraryxe 的安装包文件 opac_app.zip 中缺乏 statis_sidebar.xml 文件的缘故。安装包已经更新。源代码中的两处 copyopac.bat 文件也已经更新。另外还增加了其他几个 *_sidebar.xml 文件，值得注意，测试的时候要观察其实包括 searchbiblio.aspx 和 browse.aspx 等几个页面都是有一行 sidebar 的。

**Comment by renyh** [comment]
dp2installer升级后，opac service 版本为3.0.7403.40630，在浏览器打开OPAC，检查 检索/浏览/书评/统计信息 下级均有了子菜单，符合预期。
