### ISSUE TITLE
问题反馈：修改册条码号并初始化摘要库后不存在的册条码摘要不变

### ISSUE THREAD

**Issue by Hopeshine** [DigitalPlatform/dp2#669]
通过内务修改原来的册条码999为T999，并在【数据库】属性页初始化【书目摘要库】后，在【读者窗】的读者借阅历史中看到册记录999的书目摘要还是原来的摘要。
![image](https://user-images.githubusercontent.com/33890036/78895701-e2b41f00-7aa1-11ea-90b4-71de29f5fc74.png)

**Comment by DigitalPlatform** [comment]
这是设计的效果。mongodb 借阅历史数据库里面以前的记录不会同步修改，还保留了以前的内容，一般来说这样也挺好。
