### ISSUE TITLE
打印订单界面的期刊订购无法正常跳转到种册窗

### ISSUE THREAD

**Issue by jasonliaocn** [DigitalPlatform/dp2#677]
2个问题：
1. 在原始数据中双击某条记录或者右键进入种册窗，均弹出如下错误：

---------------------------
对期-记录路径 '中文期刊订购/12' 进行检索的过程中发生错误: 记录路径 '中文期刊订购/12' 中的数据库名 '中文期刊订购' 不是类型 issue，因此拒绝操作。
---------------------------

调试后发现此数据库对应的数据库名为order。

2. 弹出的提示框不在最顶层，一旦切换到其他程序，必须使用窗口切换功能才能找到弹出框，若没有找到则无法进行任何操作，对用户十分不友好。

**Comment by DigitalPlatform** [comment]
问题已解决，见：

https://github.com/DigitalPlatform/dp2/commit/34532675d9e6c7f800a5d8a2b2de9087ac02af58
