### ISSUE TITLE
订购查询窗口，检索途径能不能添加“书目号”

### ISSUE THREAD

**Issue by jasonliaocn** [DigitalPlatform/dp2#682]
订购查询窗口，检索途径能不能添加“书目号”
传进去的参数都是中文，如果xml节点是<catalogNo>4-641</catalogNo>，那么关键词是如何匹配的呢？
![QQ图片20200424112644](https://user-images.githubusercontent.com/5144443/80172054-87943780-861e-11ea-819f-62476e8fb6df.png)
![QQ图片20200424112652](https://user-images.githubusercontent.com/5144443/80172065-8cf18200-861e-11ea-90bc-5c34a5f541a6.png)
数据库中没有keys_catalogNo，是不是表示不能用这个检索？如何添加？

**Comment by DigitalPlatform** [comment]
看一下“dp2图书馆集成系统参考手册”，里面有关于数据库 keys 配置文件如何配置的介绍

另外可以参考这个 issue:
https://github.com/DigitalPlatform/dp2/issues/198
