### ISSUE TITLE
希望检索匹配算法能自动忽略小语种注音符号的差异

### ISSUE THREAD

**Issue by DigitalPlatform** [DigitalPlatform/dp2#703]
比如“Die apostolischen väter”能等同“Die apostolischen vater”的效果

**Comment by DigitalPlatform** [comment]
最新版 dp2library 和 dp2libraryxe 的 dp2kernel 模块在创建检索点的时候，会对西文小语种的注音符号字符做归一化处理，对检索词也会做归一化处理，这样当利用内务前端或者 OPAC 模块检索书目记录的时候，输入的检索词中无论是具有注音符号的还是没有注音符号的，都能检索命中。

注意升级 dp2library 或 dp2libraryxe 到最新版以后，不要忘了给所有书目库重建一次检索点。如果不重建检索，检索含有注音符号的检索点可能会有问题。

**Comment by Hopeshine** [comment]
测试步骤：
1. 升级服务器
2. 重建检索点
3. 修改原有记录的某些字段为小语种字符
4. 检索测试旧纪录是否实现归一化处理
5. 新建含小语种字符的新记录了
6. 检索测试新记录是否实现了归一化处理

测试结果：
单机版dp2libraryxe 框架版本: 3.1.7478.31849，实现了检索匹配算法自动忽略小语种注音符号的差异。
标准版，版本号 library (3.28.7478.31889),实现了检索匹配算法自动忽略小语种注音符号的差异。

**Comment by DigitalPlatform** [comment]
服务器的新版本（单机版dp2libraryxe 框架版本: 3.1.7478.31849；标准版，版本号 library (3.28.7478.31889)）实现检索匹配算法能自动忽略小语种注音符号的差异。

用户要想实现检索匹配算法能自动忽略小语种注音符号的差异，可以通过一下操作来实现：

### 1.升级服务器

将服务器升级到上述版本以上。标准版服务器升级步骤参考[文档](https://github.com/DigitalPlatform/dp2/issues/194)

## 2.重建检索点

通过dp2内务登录到服务器，点菜单 【功能】/【系统维护】/【批处理任务窗】，进入【批处理任务窗】，在【任务】名一栏下拉选择“重建检索点”，点击【开始】。在弹出的对话框中，输入全部书目库名，如 “中文图书”（这里可以输入多个数据库名，输入时每行一个。输入所有书目库的目的是对所有书目库重建检索点，避免遗漏），点击【确定】按钮，系统提示“任务‘重建检索点’已成功启动 ”，开始执行重建检索点任务。

用户可以点击界面左下角的刷新按钮来观察重建检索点的进度，直到重建完毕。

## 3.重启dp2Library服务器

服务器重启后再重启dp2内务或dp2 OPAC,新增的检索点才会兑现。

标准版服务器重启步骤：在dp2Installer里点【dp2Library】-【配置实例】-右击实例，选择【停止实例】-再右击实例，选择【启动实例】。启动后点【关闭】，再退出dp2Installer。
