### ISSUE TITLE
MARC21 264字段在V3编目检索窗中显示问题

### ISSUE THREAD

**Issue by GUI9527** [DigitalPlatform/dp2#708]
264字段不能在检索窗显示出版者，出版时间，260的正常显示
![IMAG0331](https://user-images.githubusercontent.com/67700756/86431871-8a02c400-bd28-11ea-9c23-e048e9113aea.jpg)
![IMAG0330](https://user-images.githubusercontent.com/67700756/86431877-8d964b00-bd28-11ea-8e99-9c61327fc251.jpg)

**Comment by GUI9527** [comment]
264字段的一些资料
![Screenshot_20200702-123247](https://user-images.githubusercontent.com/67700756/86431966-c59d8e00-bd28-11ea-8502-b6ee1f10f390.png)
![Screenshot_20200702-123238](https://user-images.githubusercontent.com/67700756/86431969-c7675180-bd28-11ea-8b50-ea36a4d3a3cc.png)
![Screenshot_20200702-123226](https://user-images.githubusercontent.com/67700756/86431971-c8987e80-bd28-11ea-80be-97691fc40380.png)
![Screenshot_20200702-123218](https://user-images.githubusercontent.com/67700756/86431972-c9311500-bd28-11ea-8d54-b0a3cbcbf7f9.png)
![Screenshot_20200702-123210](https://user-images.githubusercontent.com/67700756/86431974-c9c9ab80-bd28-11ea-9a27-13ebab28c217.png)

**Comment by DigitalPlatform** [comment]
@GUI9527 

由于国内网络的问题，GitHub 上面的图片大部分时候都显示不出来，所以请把这些参考的内容改用文本方式 paste 过来吧。

**Comment by GUI9527** [comment]
直接来个连接http://catalufer.blog.sohu.com/230991205.html

**Comment by DigitalPlatform** [comment]
@GUI9527 

请构造一个列表。每一行包括一个样例，每个样例包括两个内容：一个是 264 的样例，一个是它被抽取到浏览列表中的期望的显示形态。这样我才能进行开发。样例请尽量概括各种情况，比如，考虑一下每个子字段是否可以重复，重复了以后应该显示成什么样子，都包括在样例中，这样能充分检验软件实现的功能是否正确。

**Comment by GUI9527** [comment]
简单说就是用264取代原来的260，新书目编目将不在使用260，而使用264，国内很多单位依旧使用260，国家图书馆也启用了新规则，新书目编目使用264.您在系统赋予260什么样的功能也赋予264同样的功能就OK了

**Comment by DigitalPlatform** [comment]
@GUI9527 

您的意思是说 260 字段的子字段和原来 260 的子字段一模一样么？请明确一下。

我的要求很简单，就是需要有人把 264 的子字段定义变成样例数据，便于我进行开发。如果没有人做这个事情，就没法做开发啊。我们需要分工协作一下，您把 MARC 数据分析一下，我来实现程序。

您换位想一下就明白了：我是否可以对您说，创建浏览格式的 C# 程序代码非常简单(而且已经是开源的全部可以看到)，您来模仿 260 写一个 264 的函数就可以了？

**Comment by GUI9527** [comment]
问题已自行解决，谢谢
