### ISSUE TITLE
用户需求：创建订购记录时通过码洋和价格计算折扣

### ISSUE THREAD

**Issue by Hopeshine** [DigitalPlatform/dp2#711]
某用户反馈，购书过程中存在一种情况：由于所需要的图书市面少有，购买时议价不是以图书定价为基础来进行的，而是采取“一口价”的方式购买。

比如：某本书出版时定价CNY68,由于出版年代较久，市面稍有，用户为了展览或其他需要，迫切要购买，与书商协商的价格是CNY500或者CNY800. 用户在创建订购记录时想要同时体现图书原来的价格（用书目价格填到“码洋”字段），和实际购买价格（购买价格填到“单价”字段），此时需要是“折扣”字段手动输入一个合适的值，使“码洋”和“单价”之间可以平衡。

希望此时软件可以自动计算“折扣”。

目前内务的版本中“折扣”字段不输入时默认是1.
![image](https://user-images.githubusercontent.com/33890036/86720970-1dedcc00-c058-11ea-961d-876ac8fbe387.png)

**Comment by DigitalPlatform** [comment]
下面介绍一下在内务的订购对话框中，如何根据预先输入的码洋和单价，自动计算并填入折扣值。

1) 如何输入码洋和单价？
在订购对话框里面输入码洋和单价的时候，如果先输入码洋，软件会自动根据输入的码洋和折扣，自动计算并填入单价字段。注意，当折扣字段为空的时候，软件也会当作默认折扣为 1 进行计算。
类似地，如果先输入单价，软件自动根据输入的单价和折扣，自动计算并填入码洋字段。
所以要想输入独立的码洋和单价值(并抑制软件的自动计算)还不是太容易操作。
这里介绍一个操作办法：先在“折扣”列输入一个问号；然后再输入码洋或者单价，软件就无法自动计算了，就不会干扰输入了。

2) 如何自动计算折扣？
当码洋和单价都输入完成后，点一下折扣字段，然后用键盘 Ctrl+A，可以触发自动计算折扣值。

**Comment by Hopeshine** [comment]
测试结果：订购和验收都已实现根据码洋和单价自动计算折扣
内务版本：dp2Circulation 3.10.7493.40415
