### ISSUE TITLE
“我爱图书馆”的借还窗显示时没有当前窗口名称，页面下方也没有菜单选项

### ISSUE THREAD

**Issue by Hopeshine** [DigitalPlatform/dp2#74]
点击“更多/借还窗”进入借还界面时，界面不显示当前窗口名称，下方也没有菜单选项。无论使用什么账号进去都存在这个问题。
以public账号进入借还窗时，界面上方也不显示当前的账号名称和当前图书馆名称。
以读者或者工作人员账号进入借还窗时，界面上方显示的账号名称在界面右上角（不同于其他界面均显示在左上角），且没有显示 当前图书馆名称。
以上，需要修正。 @renyh1013

**Comment by renyh1013** [comment]
已迁至Chord
