### ISSUE TITLE
“我爱图书馆”中，进行馆藏地设置后，书目检索结果仍然能够显示勾选的馆藏以外的册记录信息

### ISSUE THREAD

**Issue by Hopeshine** [DigitalPlatform/dp2#75]
@renyh1013 
“我爱图书馆”中，进行馆藏地设置后，书目检索结果仍然能够显示勾选的馆藏以外的册记录信息。

测试过程如下：当前账号“yinming/星洲学校”，设置中勾选的馆藏地为“班级书架”，简单检索/全部检索，检索结果中显示了馆藏地位于图书馆的册记录信息。

**Comment by renyh1013** [comment]
已迁至Chord
