### ISSUE TITLE
RFID高频点检仪的使用

### ISSUE THREAD

**Issue by Hopeshine** [DigitalPlatform/dp2#757]
RFID高频点检仪是RFID技术下图书盘点所使用到的重要设备。以下介绍该设备的简单操作。

高频盘点仪有两个版本。旧版本界面上蓝牙标记右侧是wifi标志；新版本蓝牙标记右侧是字母B。

新版本的盘点仪可以切换层架标和图书模式，需要搭配新版本的盘点模块使用（版本号：  以上）。
***
## 1.RFID高频点检仪的安装以及开关机
RFID高频点检仪使用之前只需要安装好电池就可以了。

### 安装步骤：

**A.将R-PAN手柄末端向左旋转拧开电池盖**

<img src='https://user-images.githubusercontent.com/33890036/100312289-e5da2c00-2fec-11eb-8a9b-75d09566597f.png' width='200px'/>

**B.安装1节电池，电池正极往里（装反无法开机）。**
<img src='https://user-images.githubusercontent.com/33890036/100312430-436e7880-2fed-11eb-8b64-192429bfd30f.png' width='200px'/>

**C.拧紧电池盖**
<img src='https://user-images.githubusercontent.com/33890036/100312476-66009180-2fed-11eb-9327-15f4f6c3b1e6.png' width='200px'/>

***
### 设备开/关机

**开机**：长按三秒电源键开机，LCD屏亮，蜂鸣器滴一声，开机成功

<img src='https://user-images.githubusercontent.com/33890036/100313254-2cc92100-2fef-11eb-97fd-c56a2db40af8.png' width='200px'/>

开机后界面显示产品名称、版本号、工作模式：
<img src='https://user-images.githubusercontent.com/33890036/100313417-934e3f00-2fef-11eb-8547-995cbc0965f4.png' width='150px'/>

**关机**：设备在开机状态，长按三秒电源键，设备关机
***
### A.工作界面
<img src='https://user-images.githubusercontent.com/33890036/100313567-e3c59c80-2fef-11eb-8fee-5a43fbb59cce.png' width='150px'/>

**界面说明：**

<img src='https://user-images.githubusercontent.com/33890036/100314093-d957d280-2ff0-11eb-8dc8-204436f5910d.png' width='400px'/>

以上界面是盘点仪旧系统所显示的界面。在这个版本下，盘点仪无法区分图书和层架标。也就是说如果同时扫描到图书和层架标上的标签，盘点仪不回去过滤。这种模式在实际盘点中可能造成盘点数据的不准确。

**为了在盘点过程中能够过滤不需要的数据**（要扫层架标时系统过滤同时扫到的图书数据；要扫图书时系统过滤同时扫到的层架标数据），**需要对盘点仪进行升级**。升级后主界面如下图：

新版本开机后主界面上显示B字样：
<img src='https://user-images.githubusercontent.com/33890036/114961901-4edb1700-9e9c-11eb-9e6d-f548fe571c19.png' width='200px'/>

长按L键，B变为L:
<img src='https://user-images.githubusercontent.com/33890036/114961874-41259180-9e9c-11eb-97c5-28d04b9c8222.png' width='200px'/>

高频盘点仪升级步骤请参见[文档](http://dp2003.com:8088/doc/web/#/13?page_id=1905)

### B.主设置菜单
**短按电源键**进入主设置菜单，界面显示如下：
<img src='https://user-images.githubusercontent.com/33890036/100313906-7cf4b300-2ff0-11eb-801e-6c1de92fe28e.png' width='150px'/>

此时可通过R-PAN上的“L按键”“R按键”“电源键”进行功能操作，按键功能说明如下：

序号 | 名称 | 功能|备注
-- | -- | --|--
1 | 短按L按键 | 选择按键，相当于“上一项”|
2 |长按 L按键 | 切换L和B模式|盘点仪新版本适用
3 | R按键 | 选择按键，相当于“下一项”|
4 | 电源键 | 确认键，相当于“确定”功能|

### C.蓝牙设置菜单
主菜单下按L键/R键选择【蓝牙】→短按电源键确认进入蓝牙设置菜单。
<img src='https://user-images.githubusercontent.com/33890036/100314226-1e7c0480-2ff1-11eb-86e5-a3617326abde.png' width='150px'/>

注意界面上显示：蓝牙2.0打开，蓝牙4.0打开，名称显示R-PAN.编号。

### D.射频模块设置菜单
主菜单下按L键/R键选择【射频模块】→短按电源键确认进入射频模块设置菜单。

<img src='https://user-images.githubusercontent.com/33890036/100314542-d5788000-2ff1-11eb-8324-a7ef08760637.png' width='250px'/>

具体事项值如下：
功率值：**0.50W**（此处设置会影响盘点仪的射频信号范围，设置太大可能读到书架背面的标签，造成盘点秩序混乱）
自动关射频：关
只读新标签：关
溢出时间：20秒
匹配AFI：关
AFI值：0

盘点仪射频功率与识别范围：
|射频功率|距离|
|-|-|
|0.25|21cm|
|0.5|	25cm|
|0.75	|27cm|
|1	|27cm|
|1.25	|28cm|
|1.5|	28cm|

### E.工作模式设置菜单
主菜单下按L键/R键选择【模式设置】→按电源键确认进入设置菜单→按R键选择工作模式→按电源键确认进入工作模式设置→按R或L键选择正确的工作模式→最后按电源键确认选择并退出。

设置工作模式为主机控制模式。
<img src='https://user-images.githubusercontent.com/33890036/100314694-2a1bfb00-2ff2-11eb-89cb-ff3de4c4767f.png' width='150px'/>

***
## 3.PC配置工具使用
**A.安装与启动**

在电脑上安装R-Tool软件包，运行可执行文件启动软件。

**B.连接设备**

点检仪支持USB、网络和蓝牙三种通讯接口，盘点一般采用蓝牙模式。
操作软件前先确保设备端的蓝牙功能已经开启。
点检仪所连接的电脑要打开蓝牙功能，并且电脑和点检仪蓝牙配对成功。选配设备时要注意比对盘点仪上所显示的设备名称。
<img src='https://user-images.githubusercontent.com/33890036/100315050-ef669280-2ff2-11eb-841c-c4edde4b2849.png' width='250px'/>

**注**：如果要更换点捡仪蓝牙所连接的设备，需要先在原先所连接的设备中断开蓝牙连接，然后才能将点检仪连接到其他设备上。

**C.蓝牙连接**
按下电源开关开启设备，打开R-TOOL配置软件→弹出搜索设备界面→通信接口：选择【蓝牙】，点击“搜索”，PC与设备连接成功后“已发现的设备”列表中显示新连接的R-PAN设备，点击“开始”进入配置菜单。
<img src='https://user-images.githubusercontent.com/33890036/100315814-3dc86100-2ff4-11eb-892e-9c63e94ba8c2.png' width='250px'/>

**多标签盘点测试**：

盘点仪回到主界面：在“设置”界面选择“完成”后，回到主界面
<img src='https://user-images.githubusercontent.com/33890036/100315920-6fd9c300-2ff4-11eb-9e87-dc9eebaca507.png' width='350px'/>

R-Tool软件发送盘点指令：点击“ISO多标签测试”进入测试页面，在右侧的下拉框选择“盘点操作”，点击“开始”按钮进行盘点：
<img src='https://user-images.githubusercontent.com/33890036/100315979-94359f80-2ff4-11eb-90c0-4168e455a65c.png' width='550px'/>

R-PAN电子标签感应区域靠近标签，按L键“扫描”进行盘点；

<img src='https://user-images.githubusercontent.com/33890036/100316081-c3e4a780-2ff4-11eb-9627-59b8e524a524.png' width='350px'/>

扫描微型物品时，设备不要移动过快，否则容易漏检。

软件实时显示盘点信息

<img src='https://user-images.githubusercontent.com/33890036/100316172-ee366500-2ff4-11eb-9080-d4f2734a0d7f.png' width='500px'/>

扫描完成，按R-PAN上的L键停止扫描，同时单击R-Tool工具软件上的“停止”按钮停止盘点。

**Comment by renyh** [comment]
已转wiki
