### ISSUE TITLE
如何加工层架标信息

### ISSUE THREAD

**Issue by Hopeshine** [DigitalPlatform/dp2#759]
dp2系统层架标的加工，正常的方式是通过专门的脱机模块dp20RFID工具箱来进行。

dp2-RFID工具箱是用来脱机进行RFID加工的软件。根据RFID标签的应用，其中的【写入层架标】界面专门用来加工层架标。

## 准备工作
1）电脑安装“dp2-RFID工具箱” 
电脑的操作系统建议为正版windows10，为了能听到加工中的语音提示，电脑的声音外放要打开。

2）加工前需要一台RFID读写器（RFID读写器建议是USB接口的），RFID读写器要与加工电脑连接好。

3）为了便于扫描层架标上的层架号，加工电脑上还需要连接好一把扫码枪。

3）运行 “dp2-RFID工具箱”，先通过菜单“文件/设置”配置机构代码,如果不设置机构代码，将无法进行加工。如何设置机构代码请参见https://github.com/DigitalPlatform/dp2/issues/767

### 注：

A. **dp2-RFID工具箱 不能与dp2-RFID中心 同时使用**。如果开启dp2-RFID工具箱 时dp2-RFID中心已经打开，会导致dp2-RFID工具箱 无法识别导读写器。因为这两个软件使用的是一个读写器。

B. **不设置机构代码将无法通过dp2-RFID工具箱进行加工**。机构代码表示所加工的物品是属于哪个机构。在加工之前就配好机构代码，可以使后续所加工RFID标签中都具备机构代码信息。

***

## 加工层架标

买来的层架标一般都已经具备的RFID标签，并且层架标上会以一维码或者二维码形式印刷层架号。加工层架标，即给层架标中写入信息，包括层架标的条码(PII字段，即层架标所代表的层架号)、机构代码(OI/AOI）、应用类别（TOU,固定为30，表示层架标）。

### 加工操作步骤

1. 电脑上连接RFID读写器和扫描枪(如果层架号为二维码形式，要注意事先确认好扫码枪支持二维码扫描)，运行“dp2-RFID工具箱”。
2. 点菜单“文件/写入层架标”，打开“扫描并写入 层架标”窗口。
3. 操作第1个层架标，用扫码枪先扫层架标上的条码，然后把层架标放在RFID读写器上，系统自动识别并给层架标中写入信息，写入成功有相应的语音提示，然后从RFID读写器上拿走层架标。然后按照同样的步骤继续操作后面的层架标。

一个层架标加工完成后，在dp2-RFID工具箱主界面上的“写入历史”栏会增加显示刚才所加工的标签信息。

4. 一批层架标加工完成后，关闭“扫描并写入 层架标”窗口。回到主界面，在写入历史中看到本次加工的所有架标标签信息。用户可以通过菜单“文件/导出'写入历史'到Excel文件”把写入历史导出到Excel文件备份。（注：用户可以在备份写入历史之后，可以点击“文件/清除写入历史列表”，把写入历史清掉）

***

### 重要备注：
1.一般情况下是将层架标加工完毕后，再贴到图书架上。

2.特殊情况下，如果已经贴到书架上的层架标需要重新加工，层架标不方便撕下来用读写器识别，也可以用盘点仪去识别层架标上的RFID标签。在识别过程中，由于RFID标签的射频信号具有一定的范围，盘点仪在识别过程中可能会读取到层架标周围图书上的RFID标签信息。所以此种场景下层架标加工时，要注意清理周围的图书，并且加工完成后，需要再次确认加工的结果是否符合预期。

***

另外一种少量加工层架标信息的方式是通过dp2内务【RFID工具窗】来进行，但此处加工由于涉及到人工确定几处设置字段的位置，很容易出错，所以一般只用来测试，不用于实际场景的加工。

1.电脑连接RFID读写器，RFID中心模块启动正常，打开dp2内务的RFID工具窗。
2.把层架标放在RFID读写器上，dp2内务的RFID工具窗显示一条空白标签，如下图：

3.点击界面左侧标签记录，在界面右侧修改信息各字段内容,写完后在左侧选中记录后右击-【保存标签内容】，加工层架标完成。

|字段名称|内容|备注|
|-|-|-|
|AFI|C2|表示外借；07表示在馆|
|DSFID|06|图书馆行业固定值|
|EAS|on|表示在馆内;off/flase表示外借|
|01馆藏单件主标识符|层架标上面的条码值|可以用扫码枪扫入|
|03所属机构|写入本馆机构代码|与图书标签机构代码一致|
|05应用类别|30|层架标固定值，一定要写，否则无法识别为层架标|

**Comment by renyh** [comment]
已转wiki
