### ISSUE TITLE
“我爱图书馆”中，当前图书馆为分馆时，可以看到总馆的公告信息

### ISSUE THREAD

**Issue by Hopeshine** [DigitalPlatform/dp2#78]
@renyh1013 
测试过程中发现当前选择分馆时，能够看到总馆的公告。需要修正。
具体为：当前选择“南开区宜宾里小学”时，可以看到总馆“南开区中小盟学图书馆联盟开盟”的公告。

**Comment by renyh1013** [comment]
已迁至Chord
