### ISSUE TITLE
“我爱图书馆”设置菜单选项页面未实现按照当前账号权限进行显示

### ISSUE THREAD

**Issue by Hopeshine** [DigitalPlatform/dp2#79]
@renyh1013 
1. 当前账号为public时，进入“设置”界面，“监控本馆信息”、“监控消息隐藏敏感字段”选项不显示，“校验输入的条码号”选项处于禁用状态；声音方案一栏下拉列表处于禁用状态。
Web测试结果ic时，“监控本馆信息”、“监控消息隐藏敏感字段”显示，处于禁用状态，“校验输入的条码号”选项处于可用状态；声音方案一栏无默认选择，但下拉列表处于可用状态。

 2. 账号为具有流通权限的读者账号时，“监控本馆信息”、“监控消息隐藏敏感字段”选项不显示；选项“馆藏限定范围”只显示当前账号对应权限的馆藏；“校验输入的条码号”可用且默认不勾选、“声音方案”处于可用状态，且声音方案默认为“提示语音+具体信息语音”。
Web测试结果：当前账号为具有流通权限的读者账号时，“监控本馆信息”、“监控消息隐藏敏感字段”显示，处于禁用状态

**Comment by renyh1013** [comment]
已迁至Chord
