### ISSUE TITLE
“我爱图书馆”读者登记时读者类别，单位，手机号未设置或设置不正确时仍然能够登记成功。

### ISSUE THREAD

**Issue by Hopeshine** [DigitalPlatform/dp2#80]
@renyh1013 
测试工作单相关内容：
1. 新增读者登记时，所有的栏位均需要输入且输入正确才能登记，缺一不可。
Web:X。读者类别，单位，手机号未设置或设置不正确时仍然能够登记成功。
在读者登记界面，输入证条码号XZXP00089—读者类别没有选择—输入姓名“李”—选择性别”男“—不输入单位—不输入手机号—选择目标库”星洲学校读者“—点击“新增”—系统弹出对话框提示操作成功—点击“确定”，对话框关闭，回到读者登记窗，先前的输入保留。

点击“更多/读者登记“—进入”读者登记“界面—证条码号一栏输入XZXP00089,点”装载“—出现读者李的信息。只登记了姓名，性别，目标读者库。（当性别，目标读者库未设置时，系统会弹出相关的操作失败提示）

2. 修改读者登记。证条码号一栏输入读者证条码，点击“装载“—读者登记窗出现该读者相关的登记信息。编辑需要修改栏位的内容—点”保存“。当任何一栏的输入不正确时，系统弹出相关操作失败提示；全部输入正确时，系统提示保存成功。
Web:X。问题同上，读者类别，单位，手机号未设置或设置不正确时系统不会报错。

**Comment by renyh1013** [comment]
已迁至Chord
