### ISSUE TITLE
USMARC数据批检查脚本需求

### ISSUE THREAD

**Issue by Hopeshine** [DigitalPlatform/dp2#800]
用户数据存在两种标准：RDA和AACR2,希望通过单独的脚本来批量检查相关字段，并输出检查结果。

### RDA数据（USMARC格式）要求
|字段|要求|备注|
|-|-|-|
|头标区|头标的第18位为 i|-|
|必备条件|数据里不能存在440字段；必须要有093$a字段和固定子字段 $25；必须要有921$c字段|-|
|040|040  $beng$erda 必备 两个字段不用连着;字段值不考虑大小写|-|
|041|041字段$a ; $b ; $h子字段内容都不能超过三个字母|-|
|100|100 子字段 $q前面没有标识符,  “  ,$d”、 “ ,$c” 字段名必须有逗号，字段末尾如果不是“-”和“)”,那么必须有句点；字段内不能有连续两个及以上句点;$e 如果前面是“-”, 则没有’,’字段名直接是“-$e ” 这里没有后面的逗号|-|
|240|240 末尾不能有句点|-|
|245|245字段末尾必须用句点；如果245字段有$b,必须写作 “ #:$b”、“ #/$c”|子字段名包含前面的空格|
|246|246 末尾不能有句点|-|
|264|264子字段名形态要正确： “$a” 、“#;$a”、“  #:$b”、“ ,#c”字段名形态要正确 (#;$a不是常有字段,当有两个$a时,第二个字段名采取“#;$a”) ；264字段末尾 必须有 句点或者’]’或者’-’;264字段中存在的“.”只能出现在结尾；264.4,  当第二指示符为4时, 末尾不允许有句点 (有可能有两个264字段)|-|
|300|300 子字段格式:  “ #:$b”、“ #;$c”字段名形态要正确;有490的话 300末尾必须有点, 否则没有|子字段名包含前面的空格|
|336，337，338| 必须有336, 337, 338字段, 并且末尾不能有句点;337$a的值不能为“computer”; 338$a的值不能为’’online resource’’|-|
|490|490 默认指示符为0#, 当有830或800时，指示符可以是1#；490不能有$n和$p字段,如果有$x和$v形式要正确：“ ,$x”、“ #;$v”|子字段包含前面的空格|
|500，504|当008字段第24位是“b”时，504字段值中必须有“bibliographical references”的文字(反过来也要成立);在此基础上,如果references后面没有“)”时，必须是句点结尾；当008字段第31位是“1”时，500字段中必须有“$aInclude index“或者504里面有”index”,不能有两个index同时出现|-|
|650|当650中含有$z,或者有651字段时,必须有043字段|-|
|700|700 子字段 $q前面没有标识符,  “ ,$d”、“ ,$c” 字段名必须有逗号和空格；字段中$eeditor中要防止少个e变成 $editor,  当出现$editor时,提示, “editor不是必备” ；700字段的末尾如果不是“-”或“)”,那么必须有句点；字段内不能有连续两个及以上句点|-|
|830|当marc记录中没有490字段时，也不能有830字段。当存在$x和$v时，字段名正确的形式应该写作,“ $x”  “ #;$v”|子字段包含前面的空格|-|

### AACR2数据（USMARC）要求
|字段|要求|备注|
|-|-|-|
|必备条件|数据里不能存在440字段；必须要有093$a字段和固定子字段 $25；必须要有921$c字段|-|
|头标区|当头标从左往右第18位为a|
|040|当008的35-37位不为”eng“时,040 必须有 "$beng",  040字段不能有”$erda“|
|100|100 子字段 $q前面没有标识符,   " ,$d" " ,$c" 字段必须有逗号和空格；字段末尾如果不是’-和)’,那么必须有句点；字段内不能有连续两个及以上句点； 没有$e 字段|-|
|240|240 末尾不能有句点|-|
|245|245字段末尾必须用句点；如果245字段有$b,必须写作 “ #:$b”、“ #/$c”|-|
|246|246 末尾不能有句点|-|
|260|260字段中如果存在$a，形式为" #;$a";  “ #:$b”、“ ,#c” ，形式必须正确，260字段末尾必须以.或-或]来结尾|-|
|264, 336, 337, 338|不能存在264, 336, 337, 338字段|-|
|300|300字段末尾有句点|-|
|490|490 默认指示符为0#, 当有830或800指示符可以是1#;不能有$n和$p字段 ;  如果有$x和$v形式要正确：“ ,$x”、“ #;$v”|-|
|500，504|当008字段第24位是“b”时，504字段值中必须有“bibliographical references”的文字(反过来也要成立);在此基础上,如果references后面没有“)”时，必须是“.”结尾；当008字段第31位是“1”时，500字段中必须有“$aInclude index或者504里面有index”,不能有两个index同时出现|-|
|650|当650中含有$z,或者有651字段时,必须有043字段|-|
|700|700 子字段 $q前面没有标识符,  “ ,$d”、“ ,$c” 字段必须有逗号和空格；字段中$eeditor中要防止少个e变成 $editor,  当出现$editor时,提示, “editor不是必备” ；700字段的末尾如果不是“-”或“)”,那么必须有句点；字段内不能有连续两个及以上句点|-|
|830|当marc记录中没有490字段时，也不能有830字段。当存在$x和$v时，正确的形式应该写作“ ,$x”、“ #;$v”|子字段包含前面的空格|-|

### 样例数据一：
```
  |   | 02145cam_a2200361_i_4500¶
-- | -- | --
001 |   | CAL_022021011142¶
005 |   | 20190903164021.0¶
008 |   | 180816s2019____nvua__________000_0_eng_c¶
010 | __ | ‡a 2018039126¶
020 | __ | ‡a9781948908061 (cloth : alk.  paper)¶
020 | __ | ‡z9781948908054 (ebook)¶
040 | __ | ‡aCoU/DLC ‡beng ‡cCoU ‡erda ‡dDLC¶
042 | __ | ‡apcc¶
043 | __ | ‡an-us-ca¶
050 | 00 | ‡aF868.C45 ‡bB47 2019¶
082 | 00 | ‡a979.4/5 ‡223¶
093 | __ | ‡aK712.9 ‡25¶
099 | __ | ‡aCAL 022021011142¶
100 | 1_ | ‡aBergon,_Frank, ‡eauthor.¶
245 | 10 | ‡aTwo-buck Chuck & the  Marlboro Man : ‡bthe new Old West / ‡cFrank Bergon.¶
246 | 3_ | ‡aTwo-buck Chuck and the Marlboro  Man¶
264 | _1 | ‡aReno : ‡bUniversity of Nevada Press, ‡c[2019]¶
300 | __ | ‡avii, 255 pages : ‡billustrations ; ‡c23 cm¶
336 | __ | ‡atext ‡2rdacontent¶
337 | __ | ‡aunmediated ‡2rdamedia¶
338 | __ | ‡avolume ‡2rdacarrier¶
520 | __ | ‡a"The book debunks stereotypes  and shows how California's Great Central Valley intertwines a vanishing Old West  and an emerging New West to create America's True West, a country of  21st-century rural and small-town Westerners of many races and ethnicities who  often feel ignored or looked down on, several with ties to Nevada, Oregon,  Idaho, New Mexico, Arizona, Wyoming, Oklahoma, and Texas, but all shaped as was  Bergon by California's Great Valley"--Provided by publisher.¶
505 | 0_ | ‡aThe vision of Two-buck Chuck --  Illegal immigrant to valley farmer -- Basque dirt -- Drought in the garden of  the sun -- Valley tolerance -- Black ranch girl -- Chicano vet -- New woman  warrior -- A valley Indian's search for roots -- Native American Okie --  Rebellion in Marlboro country -- West of California : the Marlboro Man.¶
651 | _0 | ‡aCentral Valley (Calif. : Valley)  ‡xSocial life and customs ‡y21st century.¶
651 | _0 | ‡aCentral Valley (Calif. : Valley)  ‡xSocial conditions ‡y21st century.¶
650 | _0 | ‡aCultural pluralism ‡zCalifornia ‡zCentral  Valley.¶
776 | 08 | ‡iOnline version: ‡aBergon, Frank, author. ‡tTwo-buck Chuck & the Marlboro Man ‡dReno : University of Nevada Press, [2019] ‡z9781948908054 ‡w(DLC)  2018041047¶
921 | __ | ‡axx ‡bxx ‡c9781948908061¶
```

**Comment by wudidasu** [comment]
264 字段不是，#c 而是，$c

**Comment by wudidasu** [comment]
数据删掉

**Comment by Hopeshine** [comment]
用户确认不需开发
