### ISSUE TITLE
“我爱图书馆”专业借还界面未实现无权限不显示或禁用

### ISSUE THREAD

**Issue by Hopeshine** [DigitalPlatform/dp2#82]
@renyh1013 
测试发现，无流通权限的账号能够进入专业借还界面，但进行借还操作时系统会提示无操作权限。需要修正。
具体内容参见如下测试工作单：
1. 当前账号不具备借还权限时，点击“更过/专业借还”进入专业借还界面，会出现不具备操作权限的提示行。
Web:X．当前账号为读者账号“殷铭”时进入“专业借还”界面，界面显示出借书/还书子界面。但在上面借书或还书时系统提示不具有权限。

2. 当前账号只具备借书或者还书权限时，点击“更过/专业借还”进入专业借还界面，不具备权限的子界面显示为禁用状态。
Web:X。暂无此功能，无法测试。

**Comment by renyh1013** [comment]
已迁至Chord
