### ISSUE TITLE
facecenter双目摄像头功能测试

### ISSUE THREAD

**Issue by wuayang001** [DigitalPlatform/dp2#828]
2021\06\29
新增活体检测提示信息功能

新算法功能改进-增加了活体检测功能

**Comment by wuayang001** [comment]
TODO

**Comment by wuayang001** [comment]
TODO

**Comment by wuayang001** [comment]
### 测试要点：
### 测试点：

1. 用户的权限测试

2. 使用单目摄像头回归测试人脸中心

3. 活体检测测试
3.1  使用单目摄像头用（黑白照片，彩色照片，短视频）登记人脸。观察是否可以登记
3.2 登记好人脸后，使用单目摄像头（黑白照片，彩色照片，短视频）观察是否可以识别人脸
3.3 使用红外摄像头、可见光摄像头（黑白照片，彩色照片，短视频）观察是否可以登记识别人脸
3.4 登记好人脸后，使用红外摄像头、可见光摄像头（黑白照片，彩色照片，短视频）观察是否可以识别人脸
3.5 仅使用可见光摄像头用（黑白照片，彩色照片，短视频）观察是否可以登记人脸
3.6 登记好人脸后，使用单目摄像头（黑白照片，彩色照片，短视频）观察是否可以识别人脸

4. 摄像头自动休眠测试
4.1 观察不使用时，摄像头休眠时间
4.1.1 当配置参数为空时，观察可见光、红外摄像头不使用后多少秒自动关闭
4.1.2 当配置参数为默认值时，观察可见光、红外摄像头不使用后多少秒自动关闭
4.1.3 测试参数配置的上限值

4.2.1 休眠状态时使用摄像头识别自动开启时间

4.3.2 休眠状态时，主动双击摄像头观察开启时间

5. 摄像头温度测试（厂家提供摄像头最高温度可达75度）
5.1 当两个摄像头都休眠时，运行8小时观察温度
5.2 当红外摄像头一直开着时，运行8小时观察温度
5.3 当可见光摄像头一直开着时，运行8小时观察温度
5.4 当两个摄像头都开着时，运行8小时观察温度变化

6. 摄像头功能测试
6.1 在内务观察是否可以进行登记、删除、修改人脸
6.2 在dp2ssl书柜观察是否可以进行登记、删除、修改人脸
6.3 在dp2ssl自助借还观察是否可以进行登记、删除、修改人脸

7. 新旧人脸兼容测试
7.1 原登记过的人脸，采用双目摄像头观察是否可以正常识别
7.2 原登记过的人脸，不采用双目摄像头观察是否可以正常识别
7.3 新登记人脸时，观察原登记的读者记录是否被替换掉

**Comment by wuayang001** [comment]
### 测试用例 1
### 测试目的：

**Comment by wuayang001** [comment]
### 测试用例 2
### 测试目的：
使用单目摄像头回归测试人脸中心

### 测试步骤：
见issue

**Comment by wuayang001** [comment]
## 测试用例 3.1 
### 测试目的：
 使用单目摄像头用（黑白照片，彩色照片，短视频）登记人脸。观察是否可以登记

### 前提准备：
准备读者（245813）同尺寸的黑白照片、彩色照片、尺寸较小的黑白照片、尺寸较小的彩色照片、人脸动态视频

### 测试步骤：
1. 计算机连接硬件设备单目摄像头（因为本电脑摄像头不能成功启动，所以要借助外来摄像头）
2. 打开人脸中心，连接本地实例”test2“URL，
3. 进入主界面点击【摄像头】-【选择可见光摄像头】为：HD Pro Webcam C920（外部连接摄像头）随后人脸中心主界面上出现视频
4. 打开内务，登录本地实例“test2”

**Comment by wuayang001** [comment]
## 测试用例 3.2 
### 测试目的：
登记好人脸后，使用单目摄像头（黑白照片，彩色照片，短视频）观察是否可以识别人脸

**Comment by wuayang001** [comment]
## 测试用例 3.1 
### 测试目的：
 使用红外摄像头、可见光摄像头（黑白照片，彩色照片，短视频）观察是否可以登记识别人脸

### 前提准备：
准备读者（245813）同尺寸的黑白照片、彩色照片、尺寸较小的黑白照片、尺寸较小的彩色照片、人脸动态视频

### 测试步骤：
1. 计算机连接硬件设备双目摄像头。
2. 打开人脸中心，连接本地实例”test2“URL，
3. 进入主界面点击【摄像头】-【选择可见光摄像头】为：LHT-820CH 选择红外摄像头为：LHT-813H
4. 打开内务，登录本地实例“test2”，选择读者（1001）进入读者窗。
5. 点击右下角人头标志，界面跳出识别人脸对话框。进行人脸登记。
6. 使用以下几种情况扫描人脸：真人识别、同尺寸黑白照片、同尺寸彩色照片、尺寸较小的黑白照片、尺寸较小的彩色照片、手机拍摄的动态视频。

### 测试结果：
20210526-wy：人脸中心测试版版本：1.5.8.0 (64位)厂家4   内务测试版版本：3.17.7801.30168 
当扫描真人时：扫描后人脸识别对话框消失，识别成功，点击保存后，读者信息窗可以新增读者头像。进入快捷出纳窗，使用人脸识别读者成功 符合预期
当扫描到同尺寸黑白照片、同尺寸彩色照片、尺寸较小的黑白照片、尺寸较小的彩色照片、手机拍摄的动态视频时：人脸中心对话框最底部出现灰色提示信息：图像特征提取失败：不是真人。 同时语音提示：`图像特征提取失败：不是真人。请调整头部位置，按确定按钮，重新拍摄。`   符合预期

**Comment by wuayang001** [comment]
## 测试用例 3.4 
### 测试目的：
登记好人脸后，使用红外摄像头、可见光摄像头（黑白照片，彩色照片，短视频）观察是否可以识别人脸

### 前提准备：
读者（1001）用最新算法的人脸中心进行登记过人脸
准备读者（1001）同尺寸的黑白照片、彩色照片、尺寸较小的黑白照片、尺寸较小的彩色照片、人脸动态视频

### 测试步骤：
1. 计算机连接硬件设备单目摄像头（因为本电脑摄像头不能成功启动，所以要借助外来摄像头）
2. 打开人脸中心，连接本地实例”test2“URL，
3. 进入主界面点击【摄像头】-【选择可见光摄像头】为：LHT-820CH随后界面出现彩色图像。选择红外摄像头为：LHT-813H随后界面右上角出现黑白图像
4. 打开内务，登录本地实例“test2”，进入借书快捷出纳窗。
5. 点击右下角人头标志，界面跳出识别人脸对话框。进行人脸识别。
6. 使用以下几种情况扫描人脸：真人识别、同尺寸黑白照片、同尺寸彩色照片、尺寸较小的黑白照片、尺寸较小的彩色照片、手机拍摄的动态视频。

### 测试结果：
20210526-1025-wy：人脸中心测试版版本：1.5.8.0 (64位)厂家4   内务测试版版本：3.17.7801.30168 
当扫描真人时：扫描后人脸识别对话框消失，可以成功识别出读者信息放入图书DPB00002借书成功 符合预期
当扫描到同尺寸黑白照片、同尺寸彩色照片、尺寸较小的黑白照片、尺寸较小的彩色照片、手机拍摄的动态视频时：人脸中心对话框最底部出现灰色提示信息：图像特征提取失败：不是真人。 同时语音提示：`获取人脸特征失败：不是真人。`   符合预期

**Comment by wuayang001** [comment]
## 测试用例 3.3
### 测试目的：
 使用红外摄像头、可见光摄像头（黑白照片，彩色照片，短视频）观察是否可以登记识别人脸

### 前提准备：
准备读者（245813）同尺寸的黑白照片、彩色照片、尺寸较小的黑白照片、尺寸较小的彩色照片、人脸动态视频

### 测试步骤：
1. 计算机连接硬件设备双目摄像头。
2. 打开人脸中心，连接本地实例”test2“URL，
3. 进入主界面点击【摄像头】-【选择可见光摄像头】为：LHT-820CH 选择红外摄像头为：LHT-813H
4. 打开内务，登录本地实例“test2”，选择读者（1001）进入读者窗。
5. 点击右下角人头标志，界面跳出识别人脸对话框。进行人脸登记。
6. 使用以下几种情况扫描人脸：真人识别、同尺寸黑白照片、同尺寸彩色照片、尺寸较小的黑白照片、尺寸较小的彩色照片、手机拍摄的动态视频。

### 测试结果：
20210526-wy：人脸中心测试版版本：1.5.8.0 (64位)厂家4   内务测试版版本：3.17.7801.30168 
当扫描真人时：扫描后人脸识别对话框消失，识别成功，点击保存后，读者信息窗可以新增读者头像。进入快捷出纳窗，使用人脸识别读者成功 符合预期
当扫描到同尺寸黑白照片、同尺寸彩色照片、尺寸较小的黑白照片、尺寸较小的彩色照片、手机拍摄的动态视频时：人脸中心对话框最底部出现灰色提示信息：图像特征提取失败：不是真人。 同时语音提示：`图像特征提取失败：不是真人。请调整头部位置，按确定按钮，重新拍摄。`   符合预期

**Comment by wuayang001** [comment]
## 测试用例 3.6 
### 测试目的：
登记好人脸后，仅使用可见光摄像头（黑白照片，彩色照片，短视频）观察是否可以识别人脸

### 前提准备：
读者（1001）用最新算法的人脸中心进行登记过人脸
准备读者（1001）同尺寸的黑白照片、彩色照片、尺寸较小的黑白照片、尺寸较小的彩色照片、人脸动态视频

### 测试步骤：
1. 计算机连接硬件设备单目摄像头（因为本电脑摄像头不能成功启动，所以要借助外来摄像头）
2. 打开人脸中心，连接本地实例”test2“URL，
3. 进入主界面点击【摄像头】-【选择可见光摄像头】为：LHT-820CH随后界面出现彩色图像。选择红外摄像头为：LHT-813H随后界面右上角出现黑白图像
4. 打开内务，登录本地实例“test2”，进入借书快捷出纳窗。
5. 点击右下角人头标志，界面跳出识别人脸对话框。进行人脸识别。
6. 使用以下几种情况扫描人脸：真人识别、同尺寸黑白照片、同尺寸彩色照片、尺寸较小的黑白照片、尺寸较小的彩色照片、手机拍摄的动态视频。

### 测试结果：
20210526-1025-wy：人脸中心测试版版本：1.5.8.0 (64位)厂家4   内务测试版版本：3.17.7801.30168 
当扫描真人时：扫描后人脸识别对话框消失，可以成功识别出读者信息放入图书DPB00002借书成功 符合预期
当扫描到同尺寸黑白照片、同尺寸彩色照片时：扫描后人脸识别对话框消失，可以成功识别出读者信息放入图书DPB00002借书成功 符合预期
当尺寸较小的黑白照片、尺寸较小的彩色照片、手机拍摄的动态视频时：人脸中心对话框最底部出现灰色提示信息：图像特征提取失败：不是真人。 同时语音提示：`获取人脸特征失败：不是真人。`   符合预期

**Comment by wuayang001** [comment]
todo

**Comment by wuayang001** [comment]
todo

**Comment by wuayang001** [comment]
todo

**Comment by wuayang001** [comment]
todo

**Comment by wuayang001** [comment]
## 测试用例 4.1.1
### 测试目的：
当配置参数为空时，观察可见光、红外摄像头不使用后多少秒自动关闭

### 测试步骤：

**Comment by wuayang001** [comment]
## 测试用例 4.3
### 测试目的：
测试参数配置的上限值
### 测试步骤：
todo

**Comment by wuayang001** [comment]
## 测试用例 4.2.1
### 测试目的：
休眠状态时使用摄像头识别自动开启时间

### 测试步骤：
1.

**Comment by wuayang001** [comment]
## 测试用例 4.3
### 测试目的：
休眠状态时，主动双击摄像头观察开启时间

### 测试步骤：

### 测试结果：
20210526-wy：人脸中心测试版版本：1.5.8.0（64位） 内务测试版：3.17.7801.30168 人脸中心从休眠中使用时开启时间大概0.5秒，测试时感受时间很快，符合预期

**Comment by wuayang001** [comment]
## 测试用例 5
### 测试目的：
当两个摄像头都休眠时，运行8小时观察温度

### 测试步骤：

### 测试结果：

**Comment by wuayang001** [comment]
## 测试用例 5.2
### 测试目的：
当红外摄像头一直开着时，运行8小时观察温度

### 测试步骤：

### 测试结果：

**Comment by wuayang001** [comment]
## 测试用例 5.3
### 测试目的：
当可见光摄像头一直开着时，运行8小时观察温度

### 测试步骤：

### 测试结果：

**Comment by wuayang001** [comment]
## 测试用例 5.4
### 测试目的：
当两个摄像头都开着时，运行8小时观察温度变化

### 测试步骤：

### 测试结果：

**Comment by wuayang001** [comment]
## 测试用例 5.4
### 测试目的：
在内务观察是否可以进行登记、删除、修改人脸

### 测试步骤：

### 测试结果：

**Comment by wuayang001** [comment]
## 测试用例 6.1
### 测试目的：
在dp2ssl书柜观察是否可以进行登记、删除、修改人脸

### 测试步骤：

### 测试结果：

**Comment by wuayang001** [comment]
## 测试用例 6.3
### 测试目的：
在dp2ssl自助借还观察是否可以进行登记、删除、修改人脸


### 测试步骤：

### 测试结果：

**Comment by wuayang001** [comment]
## 测试用例 7.1
### 测试目的：
原登记过的人脸，采用双目摄像头观察是否可以正常识别


### 测试步骤：

### 测试结果：

**Comment by wuayang001** [comment]
## 测试用例 7.2
### 测试目的：
原登记过的人脸，不采用双目摄像头观察是否可以正常识别

### 测试步骤：

### 测试结果：

**Comment by wuayang001** [comment]
## 测试用例 7.3
### 测试目的：
新登记人脸时，观察原登记的读者记录是否被替换掉

### 测试步骤：

### 测试结果：

**Comment by wuayang001** [comment]
## 测试用例 8
### 测试目的：
测试不断登记注册10次人脸观察内存占比

### 测试步骤：
1. 计算机连接硬件设备双目摄像头，
2. 打开人脸中心，登录测试服务器地址。计算机连接硬件设备双目摄像头。选择可见光摄像头为：LHT-820CH随后界面出现彩色图像 选择红外摄像头为：LHT-813H随后界面也出现黑白图像
3. 在计算底部任务栏中右击，选中【任务管理器】，在进程中点击【face center】属性栏。
4. 观察到face center 当前所占内存为：63.6M~63.7M
5. 打开内务进入读者查寻窗，双击进入读者窗，点击左下角人头标志，经人脸注册。
6. 注册完之后，进入快捷出纳窗，点击左下角人头标志，进行人脸识别
7. 重复5-6步骤10次。
8. 随后进入任务管理器中，观察到【face center】属性页中的进程为：

### 测试结果：
20210528-wy：人脸中心测试版版本：1.5.8.0 （64位） 测试结果

**Comment by wuayang001** [comment]
## 测试用例 9
### 测试目的：
启用读者屏时，读者是否可以观察到人脸图像

### 测试前提：
准备一台计算，和一个可供分屏的显示屏

### 测试步骤：
1. 计算机连接双目摄像头，同时连接分屏。分屏选项为“扩展”
2. 打开人脸中心，登录测试服务器地址。计算机连接硬件设备双目摄像头。选择可见光摄像头为：LHT-820CH随后界面出现彩色图像 选择红外摄像头为：LHT-813H随后界面也出现黑白图像
3. 打开人脸中心，在菜单项中选择【窗口】-【切换读者面板所在屏幕】
4. 观察到第二分屏上出现了摄像头拍摄到的图像，但是仅有可见光摄像头，没有红外摄像头。
>红外部分主要是用来活体检测的，图像也和彩色部分是相似的，没有必要显示给读者#817 

5. 打开读者窗，点击左下角人头标志。登记人脸。
6. 观察到分屏的读者窗可以观察到人脸视频。
7. 登记成功后，点击保存。
8. 打开借书快捷出纳窗，点击左下角人头标志。读者窗出现读者识别窗。  符合预期

### 测试结果：
20210528-wy：人脸中心测试版：1.5.8.0 （64位）  内务正式版：3.17.7801.30168   测试结果符合预期

**Comment by wuayang001** [comment]
## 测试用例 10
### 测试目的：
当使用双目摄像头时，使用了厂家1的算法，观察是否可以登记人脸。

### 测试步骤：
1. 计算机连接硬件设备，双目摄像头
2. 打开人脸中心，进入参数配置，将算法换成厂家1（默认厂家4）
3. 回到主界面，选择可见光摄像头和红外线摄像头。观察到界面上出现两个摄像头的影像
4. 进入内务的读者查询窗，选择一个读者。进入读者窗。
5. 点击左下角人头标志，进行人脸登记。
6. 界面跳出人脸识别窗口，扫描到人脸之后，点击右下角【确定】键。
7. 界面出现卡顿，随后出现了报错。   不符合预期

### 测试结果：
20210601-wy：人脸中心测试版：1.5.8.0（64位）   当使用双目摄像头时，使用了厂家1的算法，软件出现系统报错，不是合理的报错，不符合预期

**Comment by wuayang001** [comment]
## 测试用例 11
### 测试目的：
同一个人脸用不同材质纸质识别测试

### 测试结果：

&nbsp; | A4纸 | 光面 | 亚光面 | 白面信封纸 | 棕面信封 | &nbsp;
-- | -- | -- | -- | -- | -- | --
识别100次 | 可以识别出不是真人 | 可以识别出不是真人 | 可以识别出不是真人 | 可以识别出不是真人 | 可以识别出不是真人

**Comment by wuayang001** [comment]
## 测试用例 12
### 测试目的：
各种摄像头识别体验

### 测试结果：
&nbsp; | 厂家双目摄像头 | dp-sxt00315 | dp-sxt00316
-- | -- | -- | --
正常使用温度 | 40℃左右 | ℃左右 | 37℃左右

**Comment by wuayang001** [comment]
## 测试用例 13
### 测试目的：
大量人脸测试

### 测试步骤：
1. 打开内务，登录单机版服务器。
2. 进入读者查询窗，以“人脸时间戳”为检索点进行检索。
3. 选中全部读者，右击选择【导出】-【到XML文件】在跳出的“创建读者XML”属性页中，勾选下方【包含对象文件】选择保存到桌面。
4. 点击确定。退回到桌面后，观察到新增“新建文件夹”
5. 进入文件夹，观察到新增两条文件：读者_141_object_0.met、读者_141_object_0.bin
6. 重命名“.bin”文件为“.png”文件
7. 随后打开图片，用A4纸打印出来，尺寸，像素，分辨率都为默认值。
8. 计算机连接双目摄像头，人脸中心启用厂家4算法，连接单机版的URL。
9. 打开内务进入快捷出纳窗，点击右下角人头标志进行人脸识别。
10. 放入刚打印的照片。语音提示：`获得人脸特征失败，检测到的人脸数为0，接口返回值 0`   符合预期


### 测试结果：
20210610-wy：人脸中心测试版：1.5.8.0（64位）
批量识别50张打印出来的人脸之后，软件可以完全识别出不是真人。测试结果符合预期。

**Comment by wuayang001** [comment]
## 测试用例 14
### 测试目的：
测试活体检测诊断功能

### 测试步骤：
1. 计算机连接双目摄像头
2. 打开人脸中心，选择两个摄像头。
3. 点击左上角【摄像头】-【启动活体检测诊断】
4. 界面上出现的图像中，将人脸放上去之后，可见光界面显示绿色光圈：“真人”。
5. 红外摄像头界面显示绿色光圈：“真人”。

**Comment by Wangzitong922** [comment]
## 测试用例 4.1.3
### 测试目的：
测试参数配置的上限值

### 测试步骤：
1. 计算机连接硬件设备双目摄像头。
2. 打开人脸中心，连接本地实例。
3. 
4. 进入人脸中心参数配置窗，在摄像头参数配置里面，将可见光休眠秒数与红外线休眠秒数设置为空。
5. 重新启动人脸中心，双击将可见光。红外摄像头打开。
6. 点击左侧【开始】菜单，计算开始菜单自动关闭时间

### 测试结果：
20210702-wzt：人脸中心正式版：1.5.9.0（64位）厂家4 内务正式版版本：3.21.7850.17394 dp2SSL绿色版版本：1.8.31.0 测试结果：人脸中心崩溃，报错。

**Comment by Wangzitong922** [comment]
## 测试用例 15
### 测试目的：

拔插摄像头，对人脸中心的内存占用有没有影响

### 测试步骤 15.1：
1. 计算机连接硬件设备双目摄像头。
2. 打开人脸中心，连接本地实例。
3. 配置确认好摄像头的连接没有问题
4. 将摄像头连接线多次拔掉，在插上。
5. 打开人脸中心，多次点击文件--重启人链中心

### 测试结果：
20210702-wzt：人脸中心正式版：1.5.9.0（64位）厂家4 内务正式版版本：3.21.7850.17394 
测试结果：人脸中心所占用的内存不断上涨。不符合预期结果。

**Comment by wuayang001** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/MRwu/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/MRwu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | 单个可见光 | 单个红外线 | 双目摄像头
-- | -- | -- | --
640*480 | 90cm | 89cm | 89cm
800*600 | 115cm | 115cm | 110cm
1024*960 | \ | 137cm | 120cm
1280*720 | 138cm | \
1280*1024 | \ | \ | 150cm



</body>

</html>

**Comment by Wangzitong922** [comment]
## 测试用例 17

### 测试目的：
摄像头不进入休眠状态
###测试步骤：
1. 计算机连接两个硬件设备双目摄像头。
2. 打开人脸中心，连接本地实例”test2“URL。
3. 在【配置参数】中，将【可见光视频休眠（秒数）】与【红外线视频休眠（秒数）】时间设置为0
4. 点击左侧【开始】，观察摄像头会不会进入休眠状态

### 测试结果：
20210714-wzt：人脸中心正式版：1.5.9.0（64位）厂家4 
测试结果：人脸中心不i会进入休眠状态

**Comment by wuayang001** [comment]
## 测试目的：
