### ISSUE TITLE
“我爱图书馆”专业借还界面声音功能配置不合理

### ISSUE THREAD

**Issue by Hopeshine** [DigitalPlatform/dp2#83]
@renyh1013 
测试发现，使用专业借还借还操作时，声音提示有不合理的地方，具体如下：

1. 借还界面默认的声音提示方式为“提示语音+具体信息语音”，点击进入借书界面时语音提示“请扫入读者条码”，扫入后语音朗读读者姓名；扫入图书条码后，操作成功时系统报“成功”并朗读书名，如果操作失败时报“出错”并朗读错误原因；点击进入还书界面时有语音提示“请扫入图书”，扫入册条码后操作成功报“成功”并朗读书名，操作失败报“出错”并朗读错误原因。

Web测试结果:X. 借书成功时只朗读了书名，没有报“成功”；借书失败时只有音效提示，没有报“出错”，也没有报“出错”原因。
还书操作成功时只朗读了书名，没有报“成功”；还书失败时以音效提示，没有语音报“出错”，也没有报“出错”原因。

2. 当声音设置为“简单音效+具体信息语音”，点击进入借书界面时有简单音效，扫入后读者后朗读读者姓名；扫入图书条码后，操作成功时系统报“成功”并朗读书名，如果操作失败时报“出错”并朗读错误原因；点击进入还书界面时有简单音效，扫入册条码后操作成功报“成功”并朗读书名，操作失败报“出错”并朗读错误原因。

Web测试结果:X. 借书成功时只朗读了书名，没有报“成功”；借书失败时只有音效提示，没有报“出错”，也没有报“出错”原因。
还书操作成功时只朗读了书名，没有报“成功”；还书失败时以音效提示，没有语音报“出错”，也没有报“出错”原因。

**Comment by renyh1013** [comment]
已迁至Chord
