### ISSUE TITLE
dp2 batch安装报错

### ISSUE THREAD

**Issue by Wangzitong922** [DigitalPlatform/dp2#832]
todu

**Comment by Wangzitong922** [comment]
### 系统环境：
1、小米笔记本
2、win10、64 位操作系统、Windows 10 家庭中文版、版本号：20H2
3、5月初拿到这台笔记本，在设置-更新与安全-恢复，使用重置此电脑将系统初始化将进行重置
重置完成后，开始使用这台电脑进行日常工作。
工作期间下载了dp2系统各个模块的安装包，安装时没有出现.net framework 4.7.2的报错，之前安装各个模块的在后续使用过程中，一切正常。
今天需要使用到dp2 batch这个模块，去下载安装时，出现了故障。
### 操作步骤
1、打开http://dp2003.com/dp2Batch/v3/publish.htm网址
2、点击左下角安装，通过迅雷下载安装dp2 batch的.exe文件
3、打开dp2 batch的.exe文件进行下载安装
4、弹出提示窗，阅读microsoft .net framework 4.7.2协议，并让我们选择是否接受，
![image](https://user-images.githubusercontent.com/83742478/121340429-2f1f1700-c952-11eb-99d0-85d9fa7edf56.png)
5、选择接受，出现下面提示
![image](https://user-images.githubusercontent.com/83742478/121340692-76a5a300-c952-11eb-9fed-a60d6ea2a2dd.png)
NDP472-KB4054531-Web.exe自最初发布后已经更改。
6、选择取消将会取消安装
7、若选择确认还在弹出同样的错误信息
导致软件安装失败。

**Comment by DigitalPlatform** [comment]
可能是数字签名证书陈旧导致的问题。已经解决。请测试并确认。
