### ISSUE TITLE
“我爱图书馆”专业借还未实现ISBN借还

### ISSUE THREAD

**Issue by Hopeshine** [DigitalPlatform/dp2#84]
测试发现，“我爱图书馆”专业借还未实现ISBN借还。需要修正。

具体测试过程如下：
目标：在还书界面上，可以扫入ISBN进行还书。
Web结果:X.关闭“校验输入的条码号”功能后，未勾选馆藏范围的情况下，当扫入一个ISBN 978-7-5346-5590-6时，系统提示册条码号978-7-5346-5590-6不存在。无法使用ISBN来借还。

**Comment by renyh1013** [comment]
迁移至Chord
