### ISSUE TITLE
系统说明：关于新建读者的缺省密码

### ISSUE THREAD

**Issue by paopaofeng** [DigitalPlatform/dp2#88]
在 dp2内务（dp2Circulation）的“读者窗”新增读者记录时，窗口内未提供“密码”输入框，但是出于安全性考虑，新增的读者数据也是有密码的，缺省的密码分两种情况：

1. 新增的读者信息时包含“**出生日期**”，那么缺省密码是出生日期的全 8位。例如，出生日期是“2018年4月26”，密码则是“20180426”。

2. 新增的读者信息时不包含出生日期，那么密码由系统分配为随机的 6位 数字。这时创建者无法查到密码实际内容，可在“修改密码窗”修改密码。

补充：从卡中心同步新增的读者密码生成规则与由在 dp2内务 `读者窗`创建规则相同。

问：导入的读者密码好像不是身份证的上面的YYMMDD和出生日期里面的YYMMDD
答：如果创建读者时有出生日期，那么密码是8位生日，例如20180603
如果没有出生日期，那么系统会产生一个随机的密码。

问：有没有不能发批量修改或者更新一下？
答：我们一般建议在读者信息里存储手机号，这样读者本人可以用手机号自己找回密码。
由于安全性，一般不建议批量修改读者密码。

**Comment by paopaofeng** [comment]
补充：从卡中心同步新增的读者密码生成规则与由在 dp2内务 `读者窗`创建规则相同。

**Comment by renyh** [comment]
问：导入的读者密码好像不是身份证的上面的YYMMDD和出生日期里面的YYMMDD
答：如果创建读者时有出生日期，那么密码是8位生日，例如20180603
如果没有出生日期，那么系统会产生一个随机的密码。


问：有没有不能发批量修改或者更新一下？
答：我们一般建议在读者信息里存储手机号，这样读者本人可以用手机号自己找回密码。
由于安全性，一般不建议批量修改读者密码。

**Comment by jasonliaocn** [comment]
导入读者时，出生日期一栏填yyyyMMdd，19790905，使用读者证号码和密码登录opac时提示密码错误，试过完整出生日期和yyDDdd，在读者信息界面出生日期显示正确。

**Comment by renyh** [comment]
已转wiki
