### ISSUE TITLE
测试计划：馆员账户“权限”内容末尾含多余字符（比如回车符）

### ISSUE THREAD

**Issue by paopaofeng** [DigitalPlatform/dp2#97]
如题，dp2Library 端馆员账户的“权限”内容末尾处含有非权限代码的字符，测试权限设置是否生效。

**Comment by paopaofeng** [comment]
1. 需要验证馆员账户“权限”内容中末尾带有回车，是全部权限都不生效，还是只有最后一个权限不生效。
2. 在这里又想到另一个一个问题，如果是权限代码的起始位置或中间位置带有回车符，又是什么情况。

**Comment by renyh** [comment]
已验证在权限中间或末尾加空格 或 回车，不影响权限的效果。
